Repository aws/aws-parallelcluster, pull requests merged in 2021-12, with the labels that each got.

#3555 [develop] Fix recipe called as part of cluster update
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#3556 2.11: Improve method to attach a volume to an instance waiting to be attached
  tests/integration-tests/tests/storage/snapshots_factory.py
Labels: skip-changelog-update

#3560 3.0: Improve method to attach a volume to an instance waiting to be attached
  tests/integration-tests/tests/storage/snapshots_factory.py
Labels: skip-changelog-update

#3561 Improve method to attach a volume to an instance waiting to be attached
  tests/integration-tests/tests/storage/snapshots_factory.py
Labels: skip-changelog-update

#3562 2.11: Add missing information to logging message for attach volume result
  tests/integration-tests/tests/storage/snapshots_factory.py
Labels: skip-changelog-update

#3563 Check whether previous cluster config exists
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/recipes/update_head_node.rb
Labels: skip-changelog-update

#3566 Improve PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog-update

#3565 [develop] integ-tests: make test_ad_integration reuse vpc_stack
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
Labels: skip-changelog-update

#3567 [develop] Avoid using DHCP options set in test_ad_integration
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#3570 [develop]Use randomly generated password for AD admin and AD users
  tests/integration-tests/tests/ad_integration/cluster_user.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update, 3.x

#3572 Bump version to 3.1.0b1
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
Labels: skip-changelog-update

#3574 Bump version to 3.1.0b1
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
Labels: skip-changelog-update

#3577 Add missing string formatting
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
Labels: skip-changelog-update

#3578 Split shell command into a sequence of arguments
  scheduler_plugins/plugin_template/tests/render_cfn_template_test.py
  scheduler_plugins/slurm/tests/render_cfn_template_test.py
Labels: skip-changelog-update

#3580 integ-tests: Fix ad_integration tests
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update, 3.x

#3582 Download/install aws-cfn-bootstrap-py3-latest.tar.gz for all OSes besides Amazon Linux
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
Labels: skip-changelog-update, 3.x

#3585 [release-3.0] Disable build AMI test for centos7
  cli/src/pcluster/api/typing_utils.py
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3586 Add validator to PasswordSecretArn
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/schemas/test_schema_validators.py
Labels: skip-changelog-update, 3.x

#3571 Use validator for max compute resources and max queue for scheduler plugin
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update

#3593 integ-tests: fix deletion order of AD integration test
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update, 3.x

#3592 [develop][integ-tests] increase retries on url validation
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update

#3598 Use Jinja SandboxedEnvironment to prevent arbitrary code execution
  cli/src/pcluster/models/cluster.py
Labels: skip-changelog-update

#3600 Additional logging for scheduler plugin definition and CFN template
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update

#3601 Add CreateServiceLinkedRole for build image policy
  api/infrastructure/parallelcluster-api.yaml
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update

#3599 3.x: Disable packages update at instance launch time on Amazon Linux 2
  CHANGELOG.md
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
Labels: 3.x

#3605 2.x: Update Changelog for 2.11.4
  CHANGELOG.md
Labels: 2.x

#3575 Add validation for Requirements config
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/scheduler_plugin_validators.py
  cli/tests/pcluster/example_configs/scheduler_plugin.full.yaml
  cli/tests/pcluster/models/test_cluster.py
  cli/tests/pcluster/validators/test_scheduler_plugin_validators.py
Labels: skip-changelog-update

#3602 Check all user id group pairs inside a security group rule
  CHANGELOG.md
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: 3.x

#3611 Change update policy of DisableManagedDns to UNSUPPORTED
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update, 3.x

#3613 Update AMI List for 2.11.4
  amis.txt
  cloudformation/aws-parallelcluster.cfn.json
Labels: skip-changelog-update

#3609 Execute CloudFormation template download and rendering as part of the dryrun
  cli/src/pcluster/api/controllers/cluster_operations_controller.py
  cli/src/pcluster/models/cluster.py
Labels: skip-changelog-update

#3622 Revert "Fix shared artifacts test for byos"
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
Labels: skip-changelog-update

#3623 3.1.0 Add validation warning message when LDAP is used and required additional SSSD configuration is missing
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/directory_service_validators.py
  cli/tests/pcluster/validators/test_directory_service_validators.py
Labels: skip-changelog-update

#3624 3.1 Fix DomainAddrValidator when checking TLS disablement in SSD additional config
  cli/src/pcluster/validators/directory_service_validators.py
  cli/tests/pcluster/validators/test_directory_service_validators.py
Labels: skip-changelog-update

#3628 Fix configuration parameters used for AWS Batch tests: Vcpus vs vCpus
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_existing_fsx/pcluster.config.yaml
Labels: skip-changelog-update, 3.x
