Repository aws/aws-parallelcluster, pull requests merged in 2022-07, with the labels that each got.

#4145 Add Shellcheck to GitHub Action
  .github/workflows/ci.yml
  cli/src/pcluster/resources/batch/docker/scripts/mount_efs.sh
  cli/src/pcluster/resources/batch/docker/scripts/mount_nfs.sh
  tests/integration-tests/tests/common/data/system-analyzer.sh
  tests/integration-tests/tests/performance_tests/resources/bootstrap/run-scale-test.sh
Labels: skip-changelog-update, 3.x

#4157 [Testing] Make integration tests suppress SchedulerValidator on cluster creation/update when using plugin scheduler
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
Labels: bug, skip-changelog-update, 3.x

#4156 Add integration tests for scontrol reboot functionality
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/slurm/slurm.conf.erb
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_scontrol_reboot/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4169 [Testing] Fix suppression of SchedulerValidator when using scheduler plugin.
  tests/integration-tests/clusters_factory.py
Labels: bug, skip-changelog-update, 3.x

#4168 Add functional integration tests for memory-based scheduling
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/memory_allocation_chars.c
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.mem-based-scheduling.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.update-schedulable-memory.yaml
Labels: skip-changelog-update, 3.x

#4171 Cherry-pick workflow update commit: Add Shellcheck to GitHub Action
  .github/workflows/ci.yml
  api/spec/openapi/ParallelCluster.openapi.yaml
  api/spec/smithy/build.gradle.kts
  cli/src/pcluster/cli/commands/configure/easyconfig.py
  cli/src/pcluster/resources/batch/docker/scripts/mount_efs.sh
  cli/src/pcluster/resources/batch/docker/scripts/mount_nfs.sh
  tests/integration-tests/tests/common/data/system-analyzer.sh
  tests/integration-tests/tests/performance_tests/resources/bootstrap/run-scale-test.sh
  util/generate-ami-list.py
Labels: skip-changelog-update

#4153 [PCluster Configure] Add integration tests for enabling EFA through the pcluster configure wizard
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/configure/test_pcluster_configure.py
  tests/integration-tests/tests/networking/test_placement_group.py
Labels: skip-changelog-update, 3.x

#4174 [PCluster Configure] Improve messaging used when requesting to enable EFA
  cli/src/pcluster/cli/commands/configure/easyconfig.py
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_disabled_efa_no_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_default_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_existing_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_non_existent_placement_group/output.txt
Labels: skip-changelog-update, 3.x

#4176 Integ-tests: only use simple protocol when running NCCL test
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update, 3.x

#4175 [integ-tests] Extend system-analyzer.sh to include /etc/passwd content
  tests/integration-tests/tests/common/data/system-analyzer.sh
Labels: skip-changelog-update

#4136 Adds AWS Budgets support to the configuration file
  cli/requirements.txt
  cli/setup.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/budget_builder.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/example_configs/awsbatch.full.yaml
  cli/tests/pcluster/example_configs/scheduler_plugin.full.yaml
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/schemas/test_schema_validators.py
Labels: skip-changelog-update, 3.x

#4182 [EFA] Improvements on messaging used in the EFA Validator
  cli/src/pcluster/cli/commands/configure/easyconfig.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_disabled_efa_no_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_default_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_existing_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_non_existent_placement_group/output.txt
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#4186 Fix small bug in integ test for scontrol reboot
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4187 Improve NumberOfStorageValidator validator message
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update

#4190 Fix small issues in integration tests
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4183 Budget validation and integration tests
  api/infrastructure/parallelcluster-api.yaml
  cli/src/pcluster/templates/budget_builder.py
  cli/src/pcluster/utils.py
  tests/iam_policies/user-role.cfn.yaml
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/budgets/test_budgets.py
  tests/integration-tests/tests/budgets/test_budgets/test_update_budget_properties/all_budget_categories.yaml
  tests/integration-tests/tests/budgets/test_budgets/test_update_budget_properties/all_budget_categories_updated.yaml
  tests/integration-tests/tests/budgets/test_budgets/test_update_budget_properties/budget_with_notifications.yaml
  tests/integration-tests/tests/budgets/test_budgets/test_update_budget_properties/no_budgets.yaml
  tests/integration-tests/tests/tags/__init__.py
Labels: skip-changelog-update

#4193 [Validation] Removed validation of `DisableSimultaneousMultithreading` and adapted disabling logic accordingly.
  CHANGELOG.md
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_validators_are_called_with_correct_argument/slurm.yaml
  cli/tests/pcluster/validators/test_cluster_validators.py
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
Labels: bug, 3.x

#4197 [Testing] Fix integration tests executing Fabtests by disabling PlacementGroups when running on p4d.24xlarge using ODCR
  tests/integration-tests/tests/efa/test_fabric/test_fabric/pcluster.config.yaml
Labels: bug, skip-changelog-update, 3.x

#4198 [Testing] Fix integration tests covering multiple NICS by disabling PlacementGroups when running on p4d.24xlarge using ODCR
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.yaml
Labels: bug, skip-changelog-update, 3.x

#4194 [ParallelCluster-API] Add missing policies for EcrImageDeletionLambda and ImageBuilderInstance Roles
  CHANGELOG.md
  api/infrastructure/parallelcluster-api.yaml
Labels: bug, 3.x

#4204 [Testing] Fix integration tests executing Fabtests
  tests/integration-tests/tests/efa/test_fabric/test_fabric/install-fabtests.sh
  tests/integration-tests/tests/efa/test_fabric/test_fabric/run-fabtests.sh
Labels: bug, skip-changelog-update, 3.x

#4196 Add validation to address field and cost tags
  api/infrastructure/parallelcluster-api.yaml
  cli/requirements.txt
  cli/setup.py
  cli/src/pcluster/aws/aws_api.py
  cli/src/pcluster/aws/cost_explorer.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/budget_validators.py
  cli/tests/pcluster/schemas/test_schema_validators.py
  cli/tests/pcluster/validators/test_budget_validators.py
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update

#4199 [FsxS3Access] Add missing permissions needed to import/export from S3 when using Fsx for Lustre via API
  CHANGELOG.md
  api/infrastructure/deploy-api.sh
  api/infrastructure/parallelcluster-api.yaml
  tests/iam_policies/user-role.cfn.yaml
Labels: bug, 3.x

#4170 [LICENSING] Add attribution document
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update, 3.x

#4209 [FsxS3Access] Fix integration tests by setting a default for FsxS3Buckets parameter
  api/infrastructure/parallelcluster-api.yaml
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x

#4217 Fix issue in integration test for scontrol reboot
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4219 [Versioning] Add missing entries to changelog for version 3.2.0
  CHANGELOG.md
Labels: 3.x

#4227 Disable awsbatch integration tests
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 2.x

#4230 Cherry-pick: fix issue in integration test for scontrol reboot
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4231 Fix budget cost filtering
  cli/src/pcluster/templates/budget_builder.py
Labels: skip-changelog-update
