Repository aws/aws-parallelcluster, pull requests merged in 2022-08, with the labels that each got.

#4235 [release-2.11] Fix flake8 B2023 warning
  cli/tests/pcluster/config/test_validators.py
  util/generate-ami-list.py
Labels: skip-changelog-update

#4228 [2.x]Upgrade Python runtime used by Lambda functions in AWS Batch integration to python3.9
  CHANGELOG.md
  cloudformation/batch-substack.cfn.json
Labels: 2.x

#4238 Enable back integ tests on AWSBatch
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/configure/test_pcluster_configure/test_pcluster_configure_avoid_bad_subnets/pcluster.config.ini
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_configuration/pcluster.config.ini
  tests/integration-tests/tests/iam/test_iam/test_iam_policies/pcluster.config.ini
  tests/integration-tests/tests/iam/test_iam/test_iam_roles/HIT.ini
  tests/integration-tests/tests/iam/test_iam/test_iam_roles/SIT.ini
  tests/integration-tests/tests/iam/test_iam/test_s3_read_write_resource/pcluster.config.ini
  tests/integration-tests/tests/networking/test_multi_cidr/test_multi_cidr/pcluster.config.ini
  tests/integration-tests/tests/networking/test_security_groups/test_additional_sg_and_ssh_from/pcluster.config.ini
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.ini
  tests/integration-tests/tests/resource_bucket/test_resource_bucket/test_resource_bucket/pcluster.config_awsbatch.ini
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/pcluster.config.ini
  tests/integration-tests/tests/storage/test_ebs/test_ebs_multiple/pcluster.config.ini
  tests/integration-tests/tests/storage/test_efs/test_efs_same_az/pcluster.config.ini
  tests/integration-tests/tests/storage/test_efs/test_existing_efs/pcluster.config.ini
  tests/integration-tests/tests/storage/test_raid/test_raid_performance_mode/pcluster.config.ini
  tests/integration-tests/tests/tags/test_tag_propagation/test_tag_propagation/pcluster.config.ini
  tests/integration-tests/tests/update/test_update/test_update_awsbatch/pcluster.config.ini
  tests/integration-tests/tests/update/test_update/test_update_awsbatch/pcluster.config.update.ini
Labels: skip-changelog-update

#4242 [release-2.11] Fix catch exception on HeadObject operation
  cli/src/pcluster/config/validators.py
Labels: skip-changelog-update

#4243 [integ-tests-2.11.7] Disable awsbatch tests in aws-us-gov and aws-cn
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4244 [integ-tests-2.11.7]Enable workaround only for AWSBatch case
  tests/integration-tests/tests/configure/test_pcluster_configure/test_pcluster_configure_avoid_bad_subnets/pcluster.config.ini
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_configuration/pcluster.config.ini
  tests/integration-tests/tests/iam/test_iam/test_iam_policies/pcluster.config.ini
  tests/integration-tests/tests/iam/test_iam/test_iam_roles/HIT.ini
  tests/integration-tests/tests/iam/test_iam/test_iam_roles/SIT.ini
  tests/integration-tests/tests/iam/test_iam/test_s3_read_write_resource/pcluster.config.ini
  tests/integration-tests/tests/networking/test_multi_cidr/test_multi_cidr/pcluster.config.ini
  tests/integration-tests/tests/networking/test_security_groups/test_additional_sg_and_ssh_from/pcluster.config.ini
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.ini
  tests/integration-tests/tests/resource_bucket/test_resource_bucket/test_resource_bucket/pcluster.config_awsbatch.ini
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/pcluster.config.ini
  tests/integration-tests/tests/storage/test_ebs/test_ebs_multiple/pcluster.config.ini
  tests/integration-tests/tests/storage/test_efs/test_efs_compute_az/pcluster.config.ini
  tests/integration-tests/tests/storage/test_efs/test_efs_same_az/pcluster.config.ini
  tests/integration-tests/tests/storage/test_efs/test_existing_efs/pcluster.config.ini
  tests/integration-tests/tests/storage/test_raid/test_raid_performance_mode/pcluster.config.ini
  tests/integration-tests/tests/tags/test_tag_propagation/test_tag_propagation/pcluster.config.ini
  tests/integration-tests/tests/update/test_update/test_update_awsbatch/pcluster.config.ini
  tests/integration-tests/tests/update/test_update/test_update_awsbatch/pcluster.config.update.ini
Labels: skip-changelog-update

#4249 [integ-tests-2.11.7] Fix test execution due to scheduler value not passed
  tests/integration-tests/tests/update/test_update/test_update_awsbatch/pcluster.config.ini
  tests/integration-tests/tests/update/test_update/test_update_awsbatch/pcluster.config.update.ini
Labels: skip-changelog-update

#4195 Add custom metric filters for common scaling errors to default cloudwatch dashboard
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  tests/integration-tests/tests/dashboard/test_dashboard.py
  tests/integration-tests/tests/dashboard/test_dashboard/test_dashboard/pcluster.config.yaml
Labels: 3.x

#4234 Print last hundreds lines of log to console when build image integration test fails
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#4213 Add test for all validators for scheduler plugin
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_all_validators_are_called/scheduler_plugin_1.yaml
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_all_validators_are_called/scheduler_plugin_2.yaml
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_validators_are_called_with_correct_argument/scheduler_plugin.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_2.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_validators_are_called_with_correct_argument/slurm.yaml
Labels: skip-changelog-update, 3.x

#4248 Change logic to consider --no-delete flag in image stacks
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#4210 Trigger fleet stop when budget threshold is reached
  api/infrastructure/parallelcluster-api.yaml
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/budget_triggered_stop.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/awsbatch_builder.py
  cli/src/pcluster/templates/budget_builder.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/validators/budget_validators.py
  cli/tests/pcluster/example_configs/awsbatch.full.yaml
  cli/tests/pcluster/example_configs/scheduler_plugin.full.yaml
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/validators/test_budget_validators.py
  tests/iam_policies/user-role.cfn.yaml
  tests/integration-tests/tests/budgets/test_budgets.py
  tests/integration-tests/tests/budgets/test_budgets/test_update_budget_properties/budget_with_fleet_stop.yaml
Labels: skip-changelog-update

#4247 [3.3][DFSM] Move head node tags from launch template to instance definition.
  CHANGELOG.md
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: 3.x

#4252 [Tags] Add TODOS related to cluster tags
  cli/src/pcluster/schemas/common_schema.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#4254 Add timeout to run_system_analyzer utility function
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#4224 Backport fix in integration test for scontrol reboot from develop
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4271 Pin smithy-cli version used to build API spec
  api/spec/smithy/build.gradle.kts
Labels: skip-changelog-update

#4259 [develop] Add policies for CreateFleet API call
  api/infrastructure/parallelcluster-api.yaml
  cli/src/pcluster/templates/cdk_builder_utils.py
  tests/iam_policies/cluster-roles.cfn.yaml
  tests/integration-tests/resources/traditional_instance_policy.json
Labels: skip-changelog-update

#4267 Add linux kernel to UpdateOS for Debian platforms
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update, 3.x

#4279 Backport of fix for Smithy from develop
  api/spec/smithy/build.gradle.kts
Labels: skip-changelog-update, 3.x

#4278 Fix DeviceIndex to not exceed MaximumNetworkInterfaces
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#4268 Add linux kernel to UpdateOS for Debian platforms
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update, 3.x

#4277 Print last hundreds lines of log to console when build image integration test fails and --no-delete preserve imagebuilder stack
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#4276 Remove test_sit_efa because are a duplication of test_hit_efa
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/init_osu_benchmarks.sh
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/config.guess
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/config.sub
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/osu-micro-benchmarks-5.7.1.tgz
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_latency
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_latency
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_mbw_mr_submit_openmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_pt2pt_submit_intelmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_pt2pt_submit_openmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/pcluster.config.ini
Labels: skip-changelog-update

#4281 Remove test_sit_efa because are a duplication of test_hit_efa
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/init_osu_benchmarks.sh
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/config.guess
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/config.sub
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/osu-micro-benchmarks-5.7.1.tgz
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_latency
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_latency
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_mbw_mr_submit_openmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_pt2pt_submit_intelmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/osu_pt2pt_submit_openmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_sit_efa/pcluster.config.ini
Labels: skip-changelog-update

#4280 Fix DeviceIndex to not exceed MaximumNetworkInterfaces
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#4251 [Versioning] Add missing entries to changelog for version 3.2.0
  CHANGELOG.md
Labels: 3.x

#4250 [CLI] Add configuration parameters needed to specify multiple instance types for a compute resource
  CHANGELOG.md
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/aws/ec2.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_compute_launch_template_properties/cluster-using-flexible-instance-types.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_compute_launch_template_properties/cluster-using-single-instance-type.yaml
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: component:cli, 3.x

#4275 Update issue templates adding AWS support link
  .github/ISSUE_TEMPLATE/bug_report_2.md
  .github/ISSUE_TEMPLATE/bug_report_3.md
  .github/ISSUE_TEMPLATE/internal_ticket_replica.md
Labels: skip-changelog-update

#4285 Add aws/aws-parallelcluster to codeowners
  .github/CODEOWNERS
Labels: skip-changelog-update

#4292 Fix code linters check related to abstract class
  cli/src/pcluster/api/errors.py
  cli/src/pcluster/aws/common.py
  cli/src/pcluster/cli/commands/common.py
  cli/src/pcluster/cli/exceptions.py
  cli/src/pcluster/config/common.py
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update, 3.x

#4289 Fix slurm_plugin tests by using node package from 3.2
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/recipes/install_cluster_daemons.rb
Labels: skip-changelog-update

#4258 Fix integration test of retrieve slurm nodes
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#4287 Changed integration tests accordingly after changing share storages logical id to be hash of volume name
  tests/integration-tests/tags_utils.py
  tests/integration-tests/tests/networking/test_security_groups.py
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.update.yaml
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.before_update.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_deletion_policy.py
  tests/integration-tests/tests/storage/test_deletion_policy/test_retain_on_deletion/pcluster.config.yaml
  tests/integration-tests/tests/tags/test_tag_propagation.py
  tests/integration-tests/tests/tags/test_tag_propagation/test_tag_propagation/pcluster.config.update.yaml
  tests/integration-tests/tests/tags/test_tag_propagation/test_tag_propagation/pcluster.config.yaml
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#4246 [3.3][DFSM] Add DeletionPolicy to EfsSettings and FsxLustreSettings
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/templates/test_shared_storage.py
  cli/tests/pcluster/templates/test_shared_storage/test_shared_storage_ebs/config.yaml
  cli/tests/pcluster/templates/test_shared_storage/test_shared_storage_efs/config.yaml
  cli/tests/pcluster/templates/test_shared_storage/test_shared_storage_fsx/config.yaml
  cli/tests/pcluster/templates/test_shared_storage/test_shared_storage_security_group/efs.config.yaml
  cli/tests/pcluster/templates/test_shared_storage/test_shared_storage_security_group/fsx-lustre.config.yaml
  cli/tests/pcluster/utils.py
Labels: 3.x

#4294 Fix test_error_handling integration test
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4301 [integ-tests-3.2.0] Fix test_create_imds_secured test
  tests/integration-tests/tests/create/test_create.py
  tests/integration-tests/tests/create/test_create/test_create_imds_secured/pcluster.config.yaml
Labels: skip-changelog-update

#4302 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog-update

#4307 `[cli/setup]` Update setup to reduce warnings in python3.10.
  cli/setup.py
Labels: skip-changelog-update, 3.x

#4309 [3.2.0] Fix integration test failure due to update cluster with pending copied AMI
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#4310 [develop] backport: Fix integration test failure due to update cluster with pending copied AMI
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x
