Repository aws/aws-parallelcluster, pull requests merged in 2022-05, with the labels that each got.

#3997 Exclude CDK version 1.153.0 cause it introduced a breaking change
  cli/setup.py
Labels: skip-changelog-update

#4009 integ-tests: remove assert_no_error_in_log from test_efa
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update, 2.x

#4010 integ-tests: remove assert_no_error_in_log from test_efa
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update, 2.x

#4013 Fix `export-cluster-logs` command filter option
  CHANGELOG.md
  cli/src/pcluster/cli/commands/cluster_logs.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/models/cluster_resources.py
  cli/tests/pcluster/cli/test_export_cluster_logs.py
  cli/tests/pcluster/models/test_cluster_resources.py
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
Labels: 3.x

#4003 Add support for LDAPS to the 1-click AD integration template
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update

#4016 Minor fix to xdist_session_fixture in integ tests
  tests/integration-tests/framework/fixture_utils.py
Labels: skip-changelog-update

#4017 Minor fix to remove duplicate dictionary key in unit test
  cli/tests/pcluster/cli/test_export_cluster_logs.py
Labels: skip-changelog-update, 3.x

#4025 Bump cli to version 2.11.7
  cli/setup.py
  cloudformation/aws-parallelcluster.cfn.json
Labels: skip-changelog-update

#4024 Bump version to 3.1.4
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
Labels: skip-changelog-update, 3.x

#4020 cheery-pick: Add validator for DirectoryService/PasswordSecretArn
  CHANGELOG.md
  cli/src/pcluster/aws/aws_api.py
  cli/src/pcluster/aws/secretsmanager.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/directory_service_validators.py
  cli/tests/pcluster/validators/test_directory_service_validators.py
  cli/tests/pcluster/validators/utils.py
Labels: 3.x

#4018 cherry-pick: Fix export-cluster-logs command filter option
  CHANGELOG.md
  cli/src/pcluster/cli/commands/cluster_logs.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/models/cluster_resources.py
  cli/tests/pcluster/cli/test_export_cluster_logs.py
  cli/tests/pcluster/models/test_cluster_resources.py
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
Labels: 3.x

#4027 [3.1.4] Add `lambda:TagResource` to API stack
  api/infrastructure/parallelcluster-api.yaml
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x

#4026 3.x: Add `lambda:TagResource` to API stack
  api/infrastructure/parallelcluster-api.yaml
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x

#4019 [develop] Specify role name in cfn-init call
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/resources/head_node/user_data.sh
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_get_head_node_role_name/config.yaml
Labels: skip-changelog-update

#4035 Do not execute test_awsbatch_defaults when checking dockerfile deps
  tests/integration-tests/tests/schedulers/test_awsbatch.py
Labels: skip-changelog-update

#4036 Update changelog of 3.1.4
  CHANGELOG.md
Labels: 3.x

#4037 Update 3.1.4 changelog to include JWT
  CHANGELOG.md
Labels: 3.x

#4038 Add changelog entries for 3.1.4
  CHANGELOG.md
Labels: 3.x

#4041 Update AMI List
  amis.txt
  cloudformation/aws-parallelcluster.cfn.json
Labels: skip-changelog-update

#4044 Fix slurm version checked in integration tests: 21.08.8-2
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#4047 Make scheduler as not required in API for backward compatibility
  api/client/src/docs/ClusterInfoSummary.md
  api/client/src/docs/DescribeClusterResponseContent.md
  api/client/src/pcluster_client/model/cluster_info_summary.py
  api/client/src/pcluster_client/model/describe_cluster_response_content.py
  api/spec/openapi/ParallelCluster.openapi.yaml
  api/spec/smithy/model/operations/DescribeCluster.smithy
  api/spec/smithy/model/types/Cluster.smithy
  cli/src/pcluster/api/models/cluster_info_summary.py
  cli/src/pcluster/api/models/describe_cluster_response_content.py
Labels: skip-changelog-update, 3.x

#4043 Add tests for build-image with kernel 4 images
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/createami/test_createami.py
  tests/integration-tests/tests/createami/test_createami/test_kernel4_build_image_run_cluster/image.config.yaml
  tests/integration-tests/tests/createami/test_createami/test_kernel4_build_image_run_cluster/pcluster.config.yaml
Labels: skip-changelog-update

#3898 Import ABC from collections.abc for Python 3.10 compatibility
  util/update_pcluster_configs.py
Labels: skip-changelog-update

#4056 3.x: Add integ-test for queue paramter update
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_queue_parameters_update/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_queue_parameters_update/pcluster.config.update_drain.yaml
  tests/integration-tests/tests/update/test_update/test_queue_parameters_update/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update/test_queue_parameters_update/pcluster.update_drain_without_running_job.yaml
Labels: skip-changelog-update, 3.x

#4067 Add a test to verify the security group attached to the shared EFS/FSxLustre file systems
  cli/tests/pcluster/templates/test_shared_storage.py
  cli/tests/pcluster/templates/test_shared_storage/test_shared_storage_security_group/efs.config.yaml
  cli/tests/pcluster/templates/test_shared_storage/test_shared_storage_security_group/fsx-lustre.config.yaml
Labels: skip-changelog-update

#4070 Revert "Specify role name in cfn-init call"
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/resources/head_node/user_data.sh
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_get_head_node_role_name/config.yaml
Labels: skip-changelog-update

#4071 integ-tests：Add test config for queue parameters update
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x
