Repository aws/aws-parallelcluster, pull requests merged in 2022-03, with the labels that each got.

#3846 [develop] Remove scheduler fixture from createami tests
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#3855 [develop] Use unique tmp folder when preparing scheduler plugin artifacts
  scheduler_plugins/plugin_template/utils/upload_artifacts.sh
  scheduler_plugins/slurm/utils/upload_artifacts.sh
Labels: skip-changelog-update

#3857 Fix integration test test_efa
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#3856 Fix efa test
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#3861 Execute AWSBatchFsxValidator only if SharedStorage is defined
  cli/src/pcluster/config/cluster_config.py
  cli/tests/pcluster/example_configs/awsbatch.full.yaml
  cli/tests/pcluster/example_configs/awsbatch.simple.yaml
Labels: skip-changelog-update, 3.x

#3859 Remove setting default value for DefaultThreadsPerCore
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#3860 [develop] Remove setting default value for DefaultThreadsPerCore
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#3870 Support using custom template with S3 Block Public Access
  cli/src/pcluster/config/validators.py
  tests/integration-tests/test_runner.py
  util/upload-cfn-templates.py
  util/uploadTemplate.sh
Labels: skip-changelog-update

#3882 Bump version to 3.1.3
  CHANGELOG.md
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
Labels: skip-changelog-update

#3871 Integration Tests: cover consistent creation of home directory and SSH key at SSH login and switch user.
  tests/integration-tests/tests/ad_integration/cluster_user.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
Labels: skip-changelog-update

#3893 Integration Tests: cover consistent creation of home directory and SSH key at SSH login and switch user.
  tests/integration-tests/tests/ad_integration/cluster_user.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
Labels: skip-changelog-update

#3891 Allow to specify VPC and Subnet as parameters in the script that deploys APIs
  api/infrastructure/deploy-api.sh
Labels: skip-changelog-update

#3892 Allow to specify VPC and Subnet as parameters in the script that depl…
  api/infrastructure/deploy-api.sh
Labels: skip-changelog-update

#3902 Set paramiko version to 2.10.2 in tests requirements to avoid stuck tests
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update

#3901 Set paramiko version to 2.10.2 in tests requirements to avoid stuck tests
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update

#3903 Fix SCHEDULER_PLUGIN_INTERFACE_VERSION validator
  cli/src/pcluster/config/cluster_config.py
Labels: skip-changelog-update

#3904 [develop] Fix error message when not using a PCluster AMI
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#3909 [Integ 3.1.2] Remove FSx as shared storage from clusters used by AD integration tests. Using EFS as a replacement.
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
Labels: skip-changelog-update

#3907 Remove FSx as shared storage from clusters used by AD integration tests. Using EFS as a replacement.
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
Labels: skip-changelog-update

#3908 [3.1.3] Remove FSx as shared storage from clusters used by AD integration tests. Using EFS as a replacement.
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
Labels: skip-changelog-update

#3911 Revert "Set paramiko version to 2.10.2 in tests requirements"
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update

#3913 Revert "Set paramiko version to 2.10.2 in tests requirements"
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update

#3905 Improve retrieve of custom template with S3 URI
  cli/src/pcluster/utils.py
Labels: skip-changelog-update, 2.x

#3919 Disabled all tests that make use of FSx to avoid hanging
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/new_region.yaml
  tests/integration-tests/configs/pcluster3.yaml
Labels: skip-changelog-update

#3918 Disabled all tests that make use of FSx to avoid hanging
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/new_region.yaml
  tests/integration-tests/configs/pcluster3.yaml
Labels: skip-changelog-update

#3922 Comment-out all FSxLustre storage tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/new_region.yaml
  tests/integration-tests/configs/pcluster3.yaml
Labels: skip-changelog-update

#3920 Comment-out all the test case which use FSxLustre
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/new_region.yaml
  tests/integration-tests/configs/pcluster3.yaml
Labels: skip-changelog-update

#3921 Comment-out all the test case which use FSxLustre
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/new_region.yaml
  tests/integration-tests/configs/pcluster3.yaml
Labels: skip-changelog-update

#3926 [integ-tests] Add logs to better identify test phases
  tests/integration-tests/conftest.py
  tests/integration-tests/remote_command_executor.py
Labels: skip-changelog-update

#3930 Fixes fabric to version 2.6.0
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update

#3929 Fixes fabric to version 2.6.0
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update

#3932 Fixes fabric to version 2.6.0
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update

#3937 Pin minor version of werkzeug and flask
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update, 3.x

#3938 Pin minor version of werkzeug and flask
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update, 3.x
