Repository aws/aws-parallelcluster, pull requests merged in 2022-12, with the labels that each got.

#4635 3.x: Allow cluster creation with no suitable official AMI
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#4638 2.x: Split p4d EFA and multi-NICs tests in separate files
  tests/integration-tests/configs/p4d-efa.yaml
  tests/integration-tests/configs/p4d-multinics.yaml
Labels: skip-changelog-update, 2.x

#4636 Add policies to cluster nodes to allow mounting EFS with EFS utils
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#4639 [develop] Show errors in validators when volume id does not exist
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ebs_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#4642 [3.x] Change parallelcluster inline policy of Headnode
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/tests/pcluster/templates/test_cdk_builder_utils.py
  cli/tests/pcluster/templates/test_cdk_builder_utils/test_iam_resource_prefix_build_in_cdk/resourcePrefix.both_path_n_role_prefix.yaml
  cli/tests/pcluster/templates/test_cdk_builder_utils/test_iam_resource_prefix_build_in_cdk/resourcePrefix.both_path_n_role_prefix_with_s3.yaml
  cli/tests/pcluster/templates/test_cdk_builder_utils/test_iam_resource_prefix_build_in_cdk/resourcePrefix.no_prefix.yaml
  cli/tests/pcluster/templates/test_cdk_builder_utils/test_iam_resource_prefix_build_in_cdk/resourcePrefix.only_path_prefix.yaml
  cli/tests/pcluster/templates/test_cdk_builder_utils/test_iam_resource_prefix_build_in_cdk/resourcePrefix.only_role_prefix.yaml
Labels: skip-changelog-update, 3.x

#4644 2.x: Update AMI List for 2.11.9 release
  amis.txt
  cloudformation/aws-parallelcluster.cfn.json
Labels: skip-changelog-update

#4645 2.x: Add aws-parallelcluster-maintainers to code owners
  .github/CODEOWNERS
Labels: skip-changelog-update, 2.x

#4650 Creates multi-az subnets in pcluster vpc_stacks
  tests/integration-tests/conftest.py
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update, 3.x

#4654 Separate p4d multinics test from other p4d tests
  tests/integration-tests/configs/p4d-efa.yaml
  tests/integration-tests/configs/p4d-multinics.yaml
Labels: skip-changelog-update, 3.x

#4656 [THIS CHANGE MUST NOT BE MERGED] Hard code ODCR in HeadNodeLaunchTemplate
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update, 3.x

#4653 Replace inheritance from Stack with composition in ClusterCdkStack
  cli/src/pcluster/templates/awsbatch_builder.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/slurm_builder.py
Labels: skip-changelog-update

#4655 [3.x] Add hpc6id tests for develop
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#4665 [tox] Replace whitelist_externals with allowlist_externals in tox.ini
  cli/tox.ini
Labels: skip-changelog-update

#4666 [tox] Replace whitelist_externals with allowlist_externals in tox.ini
  cli/tox.ini
Labels: skip-changelog-update

#4667 [tox] Replace whitelist_externals with allowlist_externals in tox.ini
  cli/tox.ini
Labels: skip-changelog-update

#4661 [Integ-tests] rebalance integration tests
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4660 [Integ-tests] rebalance integration tests
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4669 Upgrade Slurm to version 22.05.6
  CHANGELOG.md
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: 3.x

#4433 Add integration test for db server authentication
  tests/integration-tests/tests/schedulers/test_slurm_accounting.py
  tests/integration-tests/tests/schedulers/test_slurm_accounting/resources/require_server_identity.sh
Labels: skip-changelog-update, 3.x

#4672 [Integ-test] Update availability zone in ap-northeast-1
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#4668 [3.x] Integration testing of efs mounting via efs utils
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_efs.py
  tests/integration-tests/tests/storage/test_efs/test_multiple_efs/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4676 Adds resources to ODCR fixture for multi-az integration tests
  tests/integration-tests/conftest.py
Labels: skip-changelog-update, 3.x

#4678 [develop] Adhere to tox INI rules
  awsbatch-cli/tox.ini
  cli/tox.ini
Labels: skip-changelog-update

#4679 [release-3.4] Adhere to tox INI rules
  awsbatch-cli/tox.ini
  cli/tox.ini
Labels: skip-changelog-update

#4685 [3.x] fix Integration testing of efs mounting via efs utils
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#4677 [MultiAz][IntegTests] MultiAz cluster creation and update
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_multi_az_create_and_update/pcluster_create.config.yaml
  tests/integration-tests/tests/update/test_update/test_multi_az_create_and_update/pcluster_update_1.config.yaml
  tests/integration-tests/tests/update/test_update/test_multi_az_create_and_update/pcluster_update_2.config.yaml
Labels: skip-changelog-update, 3.x

#4671 Upgrade Slurm to version 22.05.6
  CHANGELOG.md
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: 3.x

#4688 [release-3.4] Improve SingleInstanceTypeSubnetValidator messaging
  cli/src/pcluster/validators/networking_validators.py
  cli/tests/pcluster/validators/test_networking_validators.py
Labels: skip-changelog-update

#4689 [develop] Improve SingleInstanceTypeSubnetValidator messaging
  cli/src/pcluster/validators/networking_validators.py
  cli/tests/pcluster/validators/test_networking_validators.py
Labels: skip-changelog-update

#4692 [MultiAZ] Shared Storage Integration Tests: External FSx in a MultiAZ cluster
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_fsx_lustre.py
  tests/integration-tests/tests/storage/test_fsx_lustre/test_multi_az_fsx/pcluster-managed-fsx.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_multi_az_fsx/pcluster-unmanaged-fsx.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_multi_az_fsx/s3_test_file
Labels: skip-changelog-update, 3.x

#4698 [release-3.4] Adopt Instances-InstanceType config for multiple_job_submission
  tests/integration-tests/tests/scaling/test_scaling/test_multiple_jobs_submission/pcluster.config.yaml
Labels: skip-changelog-update

#4699 [develop] Use InstanceType config in multiple_job_submission config
  tests/integration-tests/tests/scaling/test_scaling/test_multiple_jobs_submission/pcluster.config.yaml
Labels: skip-changelog-update

#4700 [release-3.4] Use multiaz config for slurm tests only
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.broken.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.recover.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_scaling/pcluster.config.yaml
Labels: skip-changelog-update

#4701 [develop] Use multiaz config for slurm tests only
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.broken.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.recover.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_scaling/pcluster.config.yaml
Labels: skip-changelog-update

#4702 [release-3.4] Use multiaz config for slurm only in test_cloudwatch_logging
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging/test_cloudwatch_logging/pcluster.config.yaml
Labels: skip-changelog-update

#4703 [develop] Use multiaz config for slurm only in test_cloudwatch_logging
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging/test_cloudwatch_logging/pcluster.config.yaml
Labels: skip-changelog-update

#4705 [release-3.4] Creates only one NatGateway in vpc_stacks
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update

#4706 [develop] [MultiAz] Creates only one NatGateway in vpc_stacks
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update

#4690 Add check to prevent security exclusions
  .github/workflows/security_exclusions_checker.yml
Labels: skip-changelog-update

#4704 develop: Limit SSH connection to the cluster from EC2 instance running the test
  tests/integration-tests/conftest.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#4709 3.4: Limit SSH connection access from instance running the test
  tests/integration-tests/conftest.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#4712 [release-3.4] Ensure subnets in VPC stack are in different AZ when at least two are available
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#4713 [develop] Ensure subnets in VPC stack are in different AZ when at lea…
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#4715 3.3: Remove SSH password authentication from the AD Domain Admin node
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#4714 3.4: Remove SSH password authentication from the AD Domain Admin node
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#4716 develop: Remove SSH password authentication from the AD Domain Admin node
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#4717 [release-3.4] Moves back some tests to single-az configuration
  tests/integration-tests/tests/scaling/test_scaling/test_multiple_jobs_submission/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_scaling/pcluster.config.yaml
Labels: skip-changelog-update

#4718 [develop] Moves back some tests to single-az configuration
  tests/integration-tests/tests/scaling/test_scaling/test_multiple_jobs_submission/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_scaling/pcluster.config.yaml
Labels: skip-changelog-update

#4719 [3.x] Avoid calling validators for each compute resource
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update

#4720 develop: Permit SSH access from the bastion in tests using it
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_no_internet_subnet/pcluster.config.yaml
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_private_subnet/pcluster.config.yaml
Labels: skip-changelog-update

#4721 3.4: Permit SSH access from the bastion in tests using it
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_no_internet_subnet/pcluster.config.yaml
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_private_subnet/pcluster.config.yaml
Labels: skip-changelog-update

#4723 3.3: Permit SSH access from the bastion in tests using it
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_no_internet_subnet/pcluster.config.yaml
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_private_subnet/pcluster.config.yaml
Labels: skip-changelog-update

#4708 [fix] failure with AWS Batch when mounting with efs-utils
  tests/integration-tests/tests/storage/test_efs.py
Labels: skip-changelog-update

#4722 Avoid calling validators for each compute resource
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update

#4725 3.4: Do not check for EFA support when there is no selected instance type
  tests/integration-tests/tests/configure/test_pcluster_configure.py
Labels: skip-changelog-update, 3.x

#4724 develop: Do not check for EFA support when there is no selected instance type
  tests/integration-tests/tests/configure/test_pcluster_configure.py
Labels: skip-changelog-update, 3.x

#4680 [3.x] Backport: Integration testing of efs mounting via efs utils
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_efs.py
  tests/integration-tests/tests/storage/test_efs/test_multiple_efs/pcluster.config.yaml
Labels: skip-changelog-update

#4727 3.4: Remove IP restrictions for tests in private subnets
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_no_internet_subnet/pcluster.config.yaml
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_private_subnet/pcluster.config.yaml
Labels: skip-changelog-update

#4726 develop: Remove IP restrictions for tests in private subnets
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_no_internet_subnet/pcluster.config.yaml
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_private_subnet/pcluster.config.yaml
Labels: skip-changelog-update

#4728 3.3: Remove IP restrictions for tests in private subnets
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_no_internet_subnet/pcluster.config.yaml
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_private_subnet/pcluster.config.yaml
Labels: skip-changelog-update

#4729 [Versioning] Bump ParallelCluster AWSBatch CLI version to 1.1.0
  awsbatch-cli/setup.py
Labels: skip-changelog-update

#4652 [3.x] Add Integration tests for Resource Prefix
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/pcluster3.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/framework/credential_providers.py
  tests/integration-tests/tests/iam/test_iam.py
  tests/integration-tests/tests/iam/test_iam/test_iam_resource_prefix/pcluster.config.yaml
  tests/integration-tests/tests/iam/test_iam/test_iam_resource_prefix/user-role-iam-resource-prefix.cfn.yaml
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#4730 Update AWSBatch CLI CHANGELOG.md
  awsbatch-cli/CHANGELOG.md
Labels: skip-changelog-update

#4731 [3.x] Add logs to better identify the timing of the different phases of create-cluster calls
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/templates/cdk_builder.py
Labels: skip-changelog-update

#4733 Add logs to better identify the timing of the different phases of create-cluster calls
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/templates/cdk_builder.py
Labels: skip-changelog-update

#4734 [IntegTests] Shared Storage: Set correct number of external OpenZFS Volumes to be created
  tests/integration-tests/tests/storage/test_fsx_lustre.py
Labels: skip-changelog-update, 3.x

#4735 [3.x] Add Integration tests for Resource Prefix (#4652)
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/pcluster3.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/framework/credential_providers.py
  tests/integration-tests/tests/iam/test_iam.py
  tests/integration-tests/tests/iam/test_iam/test_iam_resource_prefix/pcluster.config.yaml
  tests/integration-tests/tests/iam/test_iam/test_iam_resource_prefix/user-role-iam-resource-prefix.cfn.yaml
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#4737 [Iam] Change update policy for cluster Iam section from SUPPORTED to IGNORED so that the update policy depends on the nested fields.
  cli/src/pcluster/schemas/cluster_schema.py
Labels: bug, skip-changelog-update, 3.x

#4740 [Fix] Passing the expected cluster stack scope to apply permissions boundary to the cluster.
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/templates/test_iam.py
  cli/tests/pcluster/templates/test_iam/test_iam_permissions_boundary/config.yaml
Labels: bug, skip-changelog-update, 3.x

#4741 [Test] Add unit tests covering the generation of cluster stack template.
  cli/tests/pcluster/templates/test_dev_settings.py
  cli/tests/pcluster/templates/test_dev_settings/test_custom_cookbook/config.yaml
  cli/tests/pcluster/templates/test_shared_storage.py
  cli/tests/pcluster/templates/test_shared_storage/test_efs_permissions/config.yaml
  cli/tests/pcluster/test_utils.py
Labels: skip-changelog-update, 3.x

#4743 Upgrade Slurm to version 22.05.7
  CHANGELOG.md
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: 3.x

#4744 Upgrade Slurm to version 22.05.7
  CHANGELOG.md
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: 3.x

#4742 [3.x] Unit Tests for Iam Section of a Cluster
  cli/tests/pcluster/config/test_config_patch.py
Labels: skip-changelog-update, 3.x

#4746 Improve test for dynamic nodes not powering down after cluster update
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_reconfigure_race_condition/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4732 [integ-tests] Fix usage of --use-default-iam-credentials flag
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/conftest.py
  tests/integration-tests/framework/credential_providers.py
Labels: skip-changelog-update

#4758 [IntegTests] Fix fetching order of build-image events when logging
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update, 3.x

#4759 [IntegTests] Fix fetching order of build-image events when logging
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update, 3.x

#4762 [3.x] Fix IMDS related errors in integ tests
  tests/integration-tests/tests/createami/test_createami.py
  tests/integration-tests/tests/createami/test_createami/test_build_image_custom_components/image.config.yaml
  tests/integration-tests/tests/createami/test_createami/test_build_image_wrong_pcluster_version/image.config.yaml
  tests/integration-tests/tests/createami/test_createami/test_invalid_config/image.config.yaml
  tests/integration-tests/tests/createami/test_createami/test_invalid_config/warnings.image.config.yaml
  tests/integration-tests/tests/iam/test_iam_image.py
  tests/integration-tests/tests/iam/test_iam_image/test_iam_roles/image.config.yaml
  tests/integration-tests/tests/pcluster_api/test_api.py
  tests/integration-tests/tests/pcluster_api/test_api/test_custom_image/image.config.yaml
Labels: skip-changelog-update

#4767 [integ-tests-3.4.0] Moving IMDSv1 test in MXP
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4749 [3.x] test non-happy ontap and openfsx mounting flow
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/templates/test_shared_storage.py
  cli/tests/pcluster/templates/test_shared_storage/test_non_happy_ontap_and_openzfs_mounting/config.yaml
Labels: skip-changelog-update
