Repository aws/aws-parallelcluster, pull requests merged in 2022-10, with the labels that each got.

#4398 [Dependencies] Downgrade Slurm to version 21.08.8
  CHANGELOG.md
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: bug, 3.x

#4395 [Release 3.2] Fix benchmark result check in case of osu_bibw test
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#4396 [Develop] Fix benchmark result check in case of osu_bibw test
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#4399 Revert "[Dependencies] Downgrade Slurm to version 21.08.8"
  CHANGELOG.md
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: bug, 3.x

#4390 Add a template to create a serverless database
  cloudformation/database/serverless-database.yaml
Labels: skip-changelog-update, 3.x

#4393 [3.3] Create an update policy for managed placement groups
  cli/src/pcluster/config/config_patch.py
  cli/src/pcluster/config/update_policy.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/config/test_update_policy.py
Labels: skip-changelog-update, 3.x

#4401 [develop] Add validator for accelerator manufacturer
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
  cli/tests/pcluster/validators/test_instance_type_list_validators.py
Labels: skip-changelog-update

#4349 [DFSM] Add INFO message for SharedStorage DeletionPolicy
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster/validators/utils.py
Labels: skip-changelog-update

#4371 [integ-tests] Add integ test for DFSM
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/create/test_create.py
  tests/integration-tests/tests/iam/test_iam.py
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_ebs.py
  tests/integration-tests/tests/storage/test_efs.py
  tests/integration-tests/tests/storage/test_fsx_lustre.py
  tests/integration-tests/tests/storage/test_raid.py
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_drain.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/s3_test_file
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#4403 [DFSM] Make integration test test_overwrite_sg consistent with changes in the security group attached to file systems.
  tests/integration-tests/tests/networking/test_security_groups.py
Labels: bug, skip-changelog-update, 3.x

#4406 [3.x] Integ-tests: Change the number of EFS and FSx used in the integration tests benchmark
  tests/integration-tests/tests/storage/test_efs.py
  tests/integration-tests/tests/storage/test_fsx_lustre.py
Labels: skip-changelog-update

#4400 3.x Clean up of one-click database template
  cloudformation/database/serverless-database.yaml
Labels: skip-changelog-update, 3.x

#4409 [DFSM] Fix cluster configuration used in integration tests: using same instance type for head node and compute nodes.
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_drain.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.yaml
Labels: bug, skip-changelog-update, 3.x

#4410 [Test] Make AWSBatchCommands.submit_command accept partition argument even if unused
  tests/integration-tests/tests/common/schedulers_common.py
Labels: bug, skip-changelog-update, 3.x

#4411 [Test] Make test_fabric use CapacityReservationTarget instead of run_instance_override
  tests/integration-tests/tests/efa/test_fabric.py
  tests/integration-tests/tests/efa/test_fabric/test_fabric/pcluster.config.yaml
  tests/integration-tests/tests/efa/test_fabric/test_fabric/run_instance_override.sh
Labels: skip-changelog-update, 3.x

#4405 [DFSM] Use UpdatePolicy.IGNORED for Ebs/Efs/FSxLustreSettings.
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/config/test_config_patch.py
Labels: skip-changelog-update, 3.x

#4412 Fix test_error_handling integration test
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4414 Fix admin password reference
  cloudformation/database/serverless-database.yaml
Labels: skip-changelog-update, 3.x

#4422 [Parsing] Make YAML parser fail on duplicate keys.
  CHANGELOG.md
  cli/src/pcluster/cli/model.py
  cli/src/pcluster/imagebuilder_utils.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/models/common.py
  cli/src/pcluster/models/s3_bucket.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/utils.py
  cli/tests/pcluster/api/controllers/test_cluster_operations_controller.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/test_utils.py
Labels: bug, 3.x

#4423 Add integ tests configuration file to be used for new OS support
  tests/integration-tests/configs/new_os.yaml
Labels: skip-changelog-update

#4424 Add parameters for CIDR blocks in Slurm accounting database CFN template
  cloudformation/database/serverless-database.yaml
Labels: skip-changelog-update, 3.x

#4425 Disallow hash character in database password
  cloudformation/database/serverless-database.yaml
Labels: skip-changelog-update, 3.x

#4415 [3.3] First integration test for ODCR
  CHANGELOG.md
  tests/integration-tests/README.md
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/pcluster3.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_tests_config.py
  tests/integration-tests/tests/networking/test_on_demand_capacity_reservation.py
  tests/integration-tests/tests/networking/test_on_demand_capacity_reservation/test_odcr/odcr.config.yaml
  tests/integration-tests/tests/networking/test_on_demand_capacity_reservation/test_on_demand_capacity_reservation/pcluster.config.yaml
  tests/integration-tests/utils.py
Labels: 3.x

#4426 3.x Require existing VPC for database cluster
  cloudformation/database/serverless-database.yaml
Labels: skip-changelog-update, 3.x

#4430 [DFSM] Fix default value for DeletionPolicy in EBS/EFS/FSxLustre
  cli/src/pcluster/config/cluster_config.py
Labels: skip-changelog-update, 3.x

#4416 3.x Add integration tests for Slurm Accounting
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/cloudwatch_logging/cloudwatch_logging_boto3_utils.py
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/schedulers/conftest.py
  tests/integration-tests/tests/schedulers/test_slurm_accounting.py
  tests/integration-tests/tests/schedulers/test_slurm_accounting/resources/get_accounting_users.sh
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting_disabled_to_enabled_update/pcluster.config.update.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting_disabled_to_enabled_update/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4428 [DFSM] Make validation of EBS volume id succeed when the volume is attached to the head node.
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/config/common.py
  cli/src/pcluster/config/imagebuilder_config.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/validators/common.py
  cli/src/pcluster/validators/ebs_validators.py
  cli/tests/pcluster/api/controllers/test_cluster_operations_controller.py
  cli/tests/pcluster/config/test_common.py
  cli/tests/pcluster/models/test_cluster.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_ebs_validators.py
Labels: skip-changelog-update, 3.x

#4429 2.x: Modify update policy of tags property
  CHANGELOG.md
  cli/src/pcluster/config/mappings.py
  cli/tests/conftest.py
Labels: 2.x

#4437 Temporarily disable test_protected_mode on Slurm scheduler plugin
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#4436 Require IMDSv2 in PC API Cfn infrastructure
  api/infrastructure/parallelcluster-api.yaml
Labels: skip-changelog-update

#4439 Upgrade Slurm to version 22.05.5
  CHANGELOG.md
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: 3.x

#4374 [Versioning] Bump version to 3.3.0
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
Labels: skip-changelog-update, 3.x

#4431 3.x Upgrade Slurm Accounting template to Serverless V2
  cloudformation/database/serverless-database.yaml
  tests/integration-tests/tests/schedulers/conftest.py
Labels: skip-changelog-update, 3.x

#4443 Fix JobState assertion for memory-based scheduling integ test
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4387 Backport Slurm Reboot Integration Tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_scontrol_reboot/pcluster.config.ini
Labels: skip-changelog-update

#4448 [3.x] Improve Placement Group on Compute Resource level Implementation
  cli/src/pcluster/config/cluster_config.py
  cli/tests/pcluster/config/test_cluster_config.py
Labels: skip-changelog-update

#4450 [develop] Improve instance networking validator
  cli/src/pcluster/validators/instances_validators.py
  cli/tests/pcluster/validators/test_instances_validators.py
Labels: skip-changelog-update

#4451 [Test] Delete the security group created by EBS snapshot factory as soon as possible to mitigate the risk of failing deletion of dependent VPC stack.
  tests/integration-tests/tests/storage/snapshots_factory.py
Labels: skip-changelog-update

#4452 Set DeviceIndex to 0 for all the interfaces for the headnode
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#4455 Fix DeviceIndex value to 1 on secondary interfaces for the headnode
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#4449 [integ-test] Add integration test for DFSM rollback
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_rollback.yaml
Labels: skip-changelog-update

#4458 Remove extra function `is_placement_group_disabled_for_compute_resource`
  cli/src/pcluster/config/cluster_config.py
  cli/tests/pcluster/config/test_cluster_config.py
Labels: skip-changelog-update

#4461 [Test] Move the following integration tests to us-west-2 to reduce the risk of insufficient capacity: test_efa and test_intel_hpc
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4454 [Test] Add fixture to serialize the execution of marked tests according to the adopted instance type
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_fabric.py
  tests/integration-tests/tests/intel_hpc/test_intel_hpc.py
Labels: skip-changelog-update

#4462 [Validators] Pass only strictly required data to SingleSubnetValidator. Added unit tests to verify it is called with expected arguments.
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/networking_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_networking_validators.py
Labels: skip-changelog-update

#4465 Fix Trainium tests
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-installation.sh
Labels: skip-changelog-update

#4464 [3.x] Catch AWSClientError when caching capacity reservation information
  cli/src/pcluster/config/cluster_config.py
Labels: skip-changelog-update

#4470 [Test] Move test_intel_hpc to us-east-2 and make it use c5.18xlarge to reduce the risk of ICEs. Move test_efa using instance_type_1 to us-east-2.
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/intel_hpc/test_intel_hpc/test_intel_hpc/pcluster.config.yaml
Labels: skip-changelog-update

#4471 Make unit tests more robust when region is already set
  cli/tests/conftest.py
  cli/tests/pcluster/api/controllers/test_common.py
Labels: skip-changelog-update

#4466 Integ-tests: Reduce sporadic failures of test_scontrol_reboot
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#4473 [Test] AD integration test: add listing of AD user home directory to ease the troubleshooting of failed removal.
  tests/integration-tests/tests/ad_integration/cluster_user.py
Labels: skip-changelog-update, 3.x

#4479 [LICENSING] Update attribution document
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update

#4478 [Test] Make integration test covering multiple NICS use Capacity Reservation Target when running on p4d.24xlarge.
  tests/integration-tests/tests/multiple_nics/test_multiple_nics.py
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.yaml
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/run_instance_override.sh
Labels: skip-changelog-update

#4481 Make integration test create_ami install vim instead of mysql within the custom script.
  tests/integration-tests/tests/createami/test_createami/test_build_image_custom_components/custom_script.sh
Labels: bug, skip-changelog-update, 3.x

#4480 reduce sporadic failures of integration test_scontrol_reboot in 2.11
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#4487 Moving test_efa_and_placement_group to us-west-2 to avoid ICE
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update
