Repository aws/aws-parallelcluster, pull requests merged in 2022-01, with the labels that each got.

#3625 2.11: Use values obtained with libfabric 1.13 for OSU All-to-All benchmark
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_collective_submit_intelmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_pt2pt_submit_intelmpi.sh
Labels: skip-changelog-update, 2.x

#3626 3.x: Use values obtained with libfabric 1.13 for OSU All-to-All benchmark
  tests/integration-tests/tests/common/data/osu/osu_collective_submit_intelmpi.sh
  tests/integration-tests/tests/common/data/osu/osu_pt2pt_submit_intelmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_alltoall
Labels: skip-changelog-update, 3.x

#3632 [develop] Switch from g3.8xlarge to g4dn.xlarge for dcv test
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_configuration/pcluster.config.yaml
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_with_remote_access/pcluster.config.yaml
Labels: skip-changelog-update

#3634 [release-3.0] Switch from g3.8xlarge to g4dn.xlarge for dcv test
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_configuration/pcluster.config.yaml
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_with_remote_access/pcluster.config.yaml
Labels: skip-changelog-update

#3633 [release-2.11] Switch from g3.8xlarge to g4dn.xlarge for dcv test
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/dcv/test_dcv.py
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_configuration/pcluster.config.ini
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_with_remote_access/pcluster.config.ini
Labels: skip-changelog-update

#3610 Add support for custom tags in plugin definition
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/tags_utils.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_deletion_policy.py
  tests/integration-tests/tests/tags/test_tag_propagation.py
Labels: skip-changelog-update

#3630 3.0: Improve documentation
  cli/src/pcluster/api/pcluster_api.py
  cli/src/pcluster/aws/ec2.py
  cli/src/pcluster/config/config_patch.py
  cli/src/pcluster/models/common.py
  cli/src/pcluster/models/s3_bucket.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/manage_docker_images.py
  cli/src/pcluster/templates/imagebuilder_stack.py
  cli/src/pcluster/utils.py
  cli/src/pcluster/validators/cluster_validators.py
  cloudformation/utils/cfn_formatter.py
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  tests/integration-tests/README.md
  tests/integration-tests/images_factory.py
  tests/integration-tests/s3_common_utils.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/update/test_update.py
  util/generate-ami-list.py
  util/sync_buckets.py
  util/update_pcluster_configs.py
  util/upload-cfn-templates.py
  util/upload-cli.sh
  util/upload-script.py
Labels: skip-changelog-update

#3640 [develop] Switch region and instance type size for dcv test
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_configuration/pcluster.config.yaml
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_with_remote_access/pcluster.config.yaml
Labels: skip-changelog-update

#3641 [release-3.0] Switch region and instance type size for dcv test
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_configuration/pcluster.config.yaml
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_with_remote_access/pcluster.config.yaml
Labels: skip-changelog-update

#3642 [release-2.11] Switch region and instance type size for dcv test
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/dcv/test_dcv.py
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_configuration/pcluster.config.ini
  tests/integration-tests/tests/dcv/test_dcv/test_dcv_with_remote_access/pcluster.config.ini
Labels: skip-changelog-update

#3647 Upgrade Smithy dependencies
  api/client/src/docs/AmiInfo.md
  api/client/src/docs/BuildImageBadRequestExceptionResponseContent.md
  api/client/src/docs/Change.md
  api/client/src/docs/ClusterInfoSummary.md
  api/client/src/docs/ClusterInstance.md
  api/client/src/docs/ConfigValidationMessage.md
  api/client/src/docs/CreateClusterBadRequestExceptionResponseContent.md
  api/client/src/docs/DescribeClusterResponseContent.md
  api/client/src/docs/DescribeImageResponseContent.md
  api/client/src/docs/DryrunOperationExceptionResponseContent.md
  api/client/src/docs/EC2Instance.md
  api/client/src/docs/Ec2AmiInfo.md
  api/client/src/docs/ImageInfoSummary.md
  api/client/src/docs/LogEvent.md
  api/client/src/docs/LogStream.md
  api/client/src/docs/StackEvent.md
  api/client/src/docs/Tag.md
  api/client/src/docs/UpdateClusterBadRequestExceptionResponseContent.md
  api/client/src/docs/UpdateError.md
  api/client/src/pcluster_client/model/ami_info.py
  api/client/src/pcluster_client/model/build_image_bad_request_exception_response_content.py
  api/client/src/pcluster_client/model/change.py
  api/client/src/pcluster_client/model/cluster_info_summary.py
  api/client/src/pcluster_client/model/cluster_instance.py
  api/client/src/pcluster_client/model/config_validation_message.py
  api/client/src/pcluster_client/model/create_cluster_bad_request_exception_response_content.py
  api/client/src/pcluster_client/model/describe_cluster_response_content.py
  api/client/src/pcluster_client/model/describe_image_response_content.py
  api/client/src/pcluster_client/model/dryrun_operation_exception_response_content.py
  api/client/src/pcluster_client/model/ec2_ami_info.py
  api/client/src/pcluster_client/model/ec2_instance.py
  api/client/src/pcluster_client/model/image_info_summary.py
  api/client/src/pcluster_client/model/log_event.py
  api/client/src/pcluster_client/model/log_stream.py
  api/client/src/pcluster_client/model/stack_event.py
  api/client/src/pcluster_client/model/tag.py
  api/client/src/pcluster_client/model/update_cluster_bad_request_exception_response_content.py
  api/client/src/pcluster_client/model/update_error.py
  api/spec/openapi/ParallelCluster.openapi.yaml
  api/spec/smithy/build.gradle.kts
Labels: skip-changelog-update

#3639 [develop] Change build AMI validation for Nvidia/Cuda for ARM case
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3615 [AD integration] improve ad integration tests to test LDAPS with certificate verification
  tests/integration-tests/configs/ad_integration.yaml
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/NLB_SimpleAD.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
Labels: skip-changelog-update

#3648 [develop] Disable scheduler plugin and related integration/unit tests
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/models/test_cluster.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3655 3.1: `[cli]` Add abbreviations for arguments for non-api based commands
  cli/src/pcluster/cli/commands/common.py
  cli/src/pcluster/cli/commands/configure/command.py
  cli/src/pcluster/cli/commands/dcv_connect.py
  cli/src/pcluster/cli/commands/ssh.py
  cli/tests/pcluster/cli/test_configure/TestConfigureCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_dcv_connect.py
  cli/tests/pcluster/cli/test_dcv_connect/TestDcvConnectCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_export_cluster_logs/TestExportClusterLogsCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_export_image_logs/TestExportImageLogsCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_ssh.py
  cli/tests/pcluster/cli/test_ssh/TestSshCommand/test_helper/pcluster-help.txt
Labels: skip-changelog-update, 3.x

#3658 Fix Log4jPatcher test
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update

#3638 Add S3 owner and checksum verification for artifacts referenced by the scheduler plugin
  cli/src/pcluster/aws/s3.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/s3_validators.py
  cli/tests/pcluster/example_configs/scheduler_plugin.full.yaml
  cli/tests/pcluster/models/test_cluster.py
  cli/tests/pcluster/models/test_imagebuilder.py
  cli/tests/pcluster/validators/test_s3_validators.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.yaml
Labels: skip-changelog-update

#3645 Expose sudoer configuration for scheduler plugin system users
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.yaml
Labels: skip-changelog-update

#3661 3.0: Add missing OperatingSystemName to AMI tests
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update

#3663 3.0: Download/install aws-cfn-bootstrap-py3-latest.tar.gz for all OSes besides Amazon Linux
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
Labels: skip-changelog-update

#3591 [release-3.0][integ-tests] increase retries on url validation
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update

#3653 3.x. Modify Intel MPI check to support 2021 version
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#3665 3.1: Fix the way extra.json is merged into the final dna.json
  cli/src/pcluster/resources/compute_node/user_data.sh
Labels: skip-changelog-update

#3670 [byos] Remove ARM tests for byos branch
  tests/integration-tests/configs/byos.yaml
Labels: skip-changelog-update

#3672 Update scheduler plugin examples
  scheduler_plugins/plugin_template/plugin_definition.yaml
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/recipes/config.rb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/recipes/config_head_node.rb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/recipes/finalize_head_node.rb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/recipes/install_slurm.rb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/slurm/99-parallelcluster-slurm.erb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/slurm/parallelcluster_clustermgtd.conf.erb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/slurm/parallelcluster_computemgtd.conf.erb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/slurm/parallelcluster_slurm_resume.conf.erb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/slurm/parallelcluster_slurm_suspend.conf.erb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/slurm/resume_program.erb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/slurm/suspend_program.erb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/supervisord.conf.erb
  scheduler_plugins/slurm/plugin_definition.yaml
  scheduler_plugins/slurm/slurm_plugin_infrastructure.cfn.yaml
Labels: skip-changelog-update

#3674 [byos] Fix location retrieval for scheduler plugin virtual env
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update

#3669 3.1.0: Fix AD integration tests
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#3675 [byos] Fix location retrieval for scheduler plugin virtual env
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update

#3676 3.1.0: AD integration test: saving time by reducing the number of users to create/test
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update

#3677 Improve get_image_log_events test to use the actual first message and not a predefined one
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update, 3.x

#3679 3.x: Fix create AMI test using the string message in assertion
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update, 3.x

#3681 Update scheduler plugin examples
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
  scheduler_plugins/slurm/plugin_definition.yaml
Labels: skip-changelog-update

#3684 3.1.0: Improve AD integration tests: add users via ldapadd rather than adcli
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#3419 Update build-model.sh
  api/spec/build-model.sh
Labels: skip-changelog-update

#3686 Fix typo in networking stack for public-subnet
  cloudformation/networking/public-private.cfn.json
Labels: skip-changelog-update

#3687 Update scheduler plugin examples
  scheduler_plugins/plugin_template/artifacts/handlers/compute_configure.sh
  scheduler_plugins/plugin_template/artifacts/handlers/compute_finalize.sh
  scheduler_plugins/plugin_template/artifacts/handlers/compute_init.sh
  scheduler_plugins/plugin_template/artifacts/handlers/head_cluster_update.sh
  scheduler_plugins/plugin_template/artifacts/handlers/head_compute_fleet_update.sh
  scheduler_plugins/plugin_template/artifacts/handlers/head_configure.sh
  scheduler_plugins/plugin_template/artifacts/handlers/head_finalize.sh
  scheduler_plugins/plugin_template/artifacts/handlers/head_init.sh
  scheduler_plugins/plugin_template/examples/cluster_configuration.yaml
  scheduler_plugins/plugin_template/plugin_definition.yaml
  scheduler_plugins/plugin_template/utils/upload_artifacts.sh
  scheduler_plugins/slurm/artifacts/handlers/head_compute_fleet_update.sh
  scheduler_plugins/slurm/plugin_definition.yaml
  scheduler_plugins/slurm/slurm_plugin_infrastructure.cfn.yaml
  scheduler_plugins/slurm/utils/upload_artifacts.sh
Labels: skip-changelog-update

#3688 [byos] Add check for clusterstatusmgtd presence in CloudWatch
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
Labels: skip-changelog-update

#3690 Improve get_image_log_events test to use the actual first message and not a predefined one
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update, 3.x

#3697 AD Integration tests: remove test cases covering LDAPS without certificate verification
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update

#3673 Signal CloudFormation with an explicit error
  cli/src/pcluster/resources/head_node/user_data.sh
Labels: skip-changelog-update

#3698 Improve message when a S3 bucket is not found or the permission to the bucket is denied
  cli/src/pcluster/validators/s3_validators.py
Labels: skip-changelog-update

#3682 Change Regex of SupportedParallelClusterVersions to support alpha and beta versions
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/validators/test_scheduler_plugin_validators.py
Labels: skip-changelog-update

#3695 3.1.0: Integration tests: add retry with exponential backoff to SSH commands
  tests/integration-tests/remote_command_executor.py
Labels: skip-changelog-update

#3699 [byos] Merge from develop
  CHANGELOG.md
  api/infrastructure/parallelcluster-api.yaml
  api/spec/build-model.sh
  cli/requirements.txt
  cli/setup.py
  cli/src/pcluster/cli/commands/common.py
  cli/src/pcluster/cli/commands/configure/command.py
  cli/src/pcluster/cli/commands/dcv_connect.py
  cli/src/pcluster/cli/commands/ssh.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/cli/test_configure/TestConfigureCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_dcv_connect.py
  cli/tests/pcluster/cli/test_dcv_connect/TestDcvConnectCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_export_cluster_logs/TestExportClusterLogsCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_export_image_logs/TestExportImageLogsCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_ssh.py
  cli/tests/pcluster/cli/test_ssh/TestSshCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_head_node_dna_json/awsbatch-imds-secured-false.head-node.dna.json
  cli/tests/pcluster/templates/test_cluster_stack/test_head_node_dna_json/scheduler-plugin-imds-secured-true.head-node.dna.json
  cloudformation/networking/public-private.cfn.json
  tests/integration-tests/configs/ad_integration.yaml
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/remote_command_executor.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/ad_integration/cluster_user.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/NLB_SimpleAD.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
  tests/integration-tests/tests/createami/test_createami.py
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_no_internet_subnet/osu_pt2pt_submit_openmpi.sh
Labels: skip-changelog-update

#3702 3.x: Fix assertion in number of instances in Security Groups overwrite test
  tests/integration-tests/tests/networking/test_security_groups.py
Labels: skip-changelog-update

#3691 Integ-tests: Test URL of DCV connect is accessible
  CHANGELOG.md
  tests/integration-tests/requirements.txt
  tests/integration-tests/tests/dcv/test_dcv.py
Labels: 2.x

#3706 Integ-tests: Temporarily disable DCV test.
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3710 3.x: Improve get_cluster_log_events test looking for the actual first message
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
Labels: skip-changelog-update, 3.x

#3713 3.x: Fix test_pcluster_get_cluster_log_events test assertion
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
Labels: skip-changelog-update

#3714 [develop] Fix check for image build in progress
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#3716 Integ-tests: Improve test_ad_integration
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/workload.sh
Labels: skip-changelog-update

#3704 Integ-tests: Test URL of DCV connect is accessible
  tests/integration-tests/tests/dcv/test_dcv.py
Labels: skip-changelog-update, 3.x
