Repository aws/aws-parallelcluster, pull requests merged in 2022-06, with the labels that each got.

#4069 develop: Do not test FSx security groups when using AWS Batch
  tests/integration-tests/tests/networking/test_security_groups.py
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.update.yaml
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.yaml
Labels: skip-changelog-update

#4075 Fix code style error after Pylint 2.14
  cli/src/pcluster/config/common.py
Labels: skip-changelog-update

#4074 Fix test_fsx_lustre_backup
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update, 3.x

#4082 Make volume id in OpenZFS and Ontap as required parameters
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update

#4080 [develop] HeadNode RootVolume DeleteOnTermination cannot be updated
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update

#4084 HeadNode Imds cannot be updated
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update

#4088 Align OSU benchmark threshold to current version tests
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_latency
Labels: skip-changelog-update

#4083 `pcluster configure` Add error message when there is an exception writing configuration file
  cli/src/pcluster/cli/commands/configure/easyconfig.py
  cli/tests/pcluster/cli/configure/test_pcluster_configure.py
Labels: skip-changelog-update, 3.x

#4089 Add ODCR to p4d test
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/p4d.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/pcluster.config.ini
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/run_instance_override.sh
Labels: skip-changelog-update, 2.x

#4095 [develop] Update no response action
  .github/no-response.yml
  .github/workflows/no-response.yml
Labels: skip-changelog-update

#4096 [develop] Grant write permission to No Response GitHub Action
  .github/workflows/no-response.yml
Labels: skip-changelog-update

#4098 Move OSU benchmark to run only in develop branch
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4099 Move OSU benchmark to run only in develop branch
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4104 Change region to test_ad_integration
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4103 Change region to test_ad_integration
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4092 Adds parallelcluster:cluster-name tag to the resources on the stack
  CHANGELOG.md
  cli/src/pcluster/models/cluster.py
  cli/tests/pcluster/models/test_cluster.py
  tests/integration-tests/tests/tags/test_tag_propagation.py
  tests/integration-tests/tests/tags/test_tag_propagation/test_tag_propagation/pcluster.config.update.yaml
Labels: 3.x

#4097 Move OSU benchmark to run only in develop branch
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4106 Add FSx for Ontap and OpenZFS to test_ad_integration tests
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update2.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4108 integ-tests: fix VPC endpoints of secrets manager in China
  tests/integration-tests/tests/networking/test_cluster_networking.py
Labels: skip-changelog-update, 3.x

#4109 Execute OSU benchmarks on clusters with 32 compute nodes and multi-treading disabled.
  tests/integration-tests/tests/common/data/osu/osu_collective_submit_intelmpi.sh
  tests/integration-tests/tests/common/data/osu/osu_collective_submit_openmpi.sh
  tests/integration-tests/tests/common/data/osu/osu_mbw_mr_submit_openmpi.sh
  tests/integration-tests/tests/common/data/osu/osu_pt2pt_submit_intelmpi.sh
  tests/integration-tests/tests/common/data/osu/osu_pt2pt_submit_openmpi.sh
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_latency
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_latency
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
Labels: skip-changelog-update

#4112 Move c5n.18xlarge to run only in develop
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4117 Expose internal memory-based scheduling parameters as Chef parameters
  cli/tests/pcluster/example_configs/slurm.full.yaml
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4100 Not require PlacementGroup/Enabled to be set to true when using PlacementGroup/Id with EFA
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update

#4128 Move efa tests to run also in develop
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4126 Change installation path of cfn-bootstrap
  cli/src/pcluster/resources/head_node/user_data.sh
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#4118 Prompt user to enable EFA for supported instance-types when using the pcluster configure wizard
  CHANGELOG.md
  cli/src/pcluster/cli/commands/configure/easyconfig.py
  cli/src/pcluster/cli/commands/configure/utils.py
  cli/tests/pcluster/cli/configure/test_pcluster_configure.py
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_disabled_efa_no_placement_group/error.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_disabled_efa_no_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_disabled_efa_no_placement_group/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_efa_not_supported/error.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_efa_not_supported/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_efa_not_supported/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_default_placement_group/error.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_default_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_default_placement_group/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_existing_placement_group/error.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_existing_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_existing_placement_group/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_non_existent_placement_group/error.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_non_existent_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_non_existent_placement_group/pcluster.config.yaml
Labels: 3.x

#4125 Add missing change for EFAPlacemetGroup validation for scheduler plugin queue
  cli/src/pcluster/config/cluster_config.py
Labels: skip-changelog-update, 3.x

#4124 Wip/devel/mem sched expose realmemory
  CHANGELOG.md
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.update_scheduling.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.yaml
Labels: 3.x

#4130 Improve validation message when a CFN stack is found with the same name as the given image-id
  cli/src/pcluster/models/imagebuilder.py
Labels: skip-changelog-update

#4132 Fix scheduler plugin integ. test with SchedulableMemory parameter
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_x86_64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_x86_64.yaml
Labels: skip-changelog-update, 3.x

#4135 Change Changelog for IMDS IPv6 lockdown
  CHANGELOG.md
Labels: 3.x

#4140 [Versioning] Fix version bumping scripts to make them use GNU sed instead of BSD sed on Mac OS.
  util/bump-awsbatch-cli-version.sh
  util/bump-version.sh
Labels: skip-changelog-update, 3.x

#4115 Fixed bug that prevented generating log widgets
  cli/src/pcluster/templates/cw_dashboard_builder.py
Labels: skip-changelog-update

#4142 Fix bug where EbsVolumeIopsValidator compared NoneType with Int
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/models/test_cluster.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster/validators/test_ebs_validators.py
Labels: skip-changelog-update, 3.x

#4141 [Versioning] Bump version to 3.2.0b2
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
Labels: skip-changelog-update, 3.x

#4143 Fix integration tests for snapshot EBS and alinux2
  tests/integration-tests/tests/storage/test_ebs.py
Labels: skip-changelog-update

#4144 Integ-tests: Fix test_scheduler_plugin
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_x86_64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_x86_64.yaml
Labels: skip-changelog-update, 3.x

#4147 [Versioning] Update changelog entries for release 3.2.0.
  CHANGELOG.md
Labels: 3.x

#4150 [Testing] Make multiple-nics integration tests use reserved capacity when running p4d.24xlarge instances.
  tests/integration-tests/tests/multiple_nics/test_multiple_nics.py
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.yaml
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/run_instance_override.sh
Labels: skip-changelog-update, 3.x

#4149 [Scheduler Plugin] Add validator to disable Scheduler Plugin
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_scheduling_validators.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
Labels: skip-changelog-update, 3.x
