Repository aws/aws-parallelcluster, pull requests merged in 2022-02, with the labels that each got.

#3705 Integ-tests: Fix fixture deletion order to ensure the last update to remove log is successful
  tests/integration-tests/tests/networking/test_cluster_networking.py
Labels: skip-changelog-update, 3.x

#3689 Update CLI Python dependencies
  cli/requirements.txt
  cli/setup.py
  cli/tests/pcluster/api/test_flask_app.py
Labels: skip-changelog-update

#3729 Add p4d tests for single OS
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3734 Enable scheduler plugin tests for all OSes
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3701 inte-tests: Enable additional tests for plugin scheduler
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.before_update.yaml
Labels: skip-changelog-update

#3731 Develop: Use re:Post as the forum
  README.md
Labels: skip-changelog-update

#3741 [byos] Make test_scheduler_plugin_integration compatible with ubuntu18
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.before_update.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.yaml
Labels: skip-changelog-update

#3742 Integ-test: Spread test_ad_integration test to different regions
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#3744 Not using duplicate construct id for HeadNodeSecurityGroupComputeIngress
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#3743 Fix UrlValidator for SchedulerPluginCloudFormationInfrastructure
  cli/src/pcluster/config/cluster_config.py
Labels: skip-changelog-update

#3736 Do not grant system users sudo privileges in case GrantSudoPrivileges is set to false
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/scheduler_plugin_validators.py
  cli/tests/pcluster/validators/test_scheduler_plugin_validators.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.before_update.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/pcluster.config.yaml
Labels: skip-changelog-update

#3748 [develop] Add retries on batch docker image build
  cli/src/pcluster/resources/batch/docker/build-docker-images.sh
Labels: skip-changelog-update

#3715 Change update policy of Tags to not support Tags section update
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/schemas/common_schema.py
Labels: skip-changelog-update

#3758 Move some AD integration tests from ap-northeast-1 to us-west-2
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3737 [release-3.0] Add p4d tests for single OS
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3755 [develop] Add test to check min NodeJS version
  cli/src/pcluster/api/controllers/cluster_operations_controller.py
  cli/src/pcluster/api/controllers/image_operations_controller.py
  cli/src/pcluster/api/flask_app.py
  cli/src/pcluster/api/util.py
  cli/src/pcluster/constants.py
  cli/tests/pcluster/api/test_util.py
  cli/tests/pcluster/cli/test_build_image.py
  cli/tests/pcluster/cli/test_build_image/TestBuildImageCommand/test_nodejs_wrong_version_error/config.yaml
  cli/tests/pcluster/cli/test_create_cluster.py
  cli/tests/pcluster/cli/test_create_cluster/TestCreateClusterCommand/test_nodejs_incompatible_version_error/config.yaml
  cli/tests/pcluster/cli/test_create_cluster/TestCreateClusterCommand/test_nodejs_wrong_version_error/config.yaml
  cli/tests/pcluster/cli/test_update_cluster.py
  cli/tests/pcluster/cli/test_update_cluster/TestUpdateClusterCommand/test_nodejs_wrong_version_error/config.yaml
Labels: skip-changelog-update

#3760 Move some AD integration tests from PDX to DUB
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3763 3.1 `[ad-integration]` Update admin node UserData to persist resolv.conf.
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update

#3773 Bump version to 3.2.0
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
Labels: skip-changelog-update

#3767 Integ-tests: Add SecretsManager VPC endpoint
  tests/integration-tests/tests/networking/test_cluster_networking.py
Labels: skip-changelog-update, 3.x

#3762 Add BucketOwner and Checksum for SchedulerDefinition
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  scheduler_plugins/plugin_template/examples/cluster_configuration.yaml
  scheduler_plugins/plugin_template/utils/upload_artifacts.sh
  scheduler_plugins/slurm/examples/cluster_configuration.yaml
  scheduler_plugins/slurm/utils/upload_artifacts.sh
Labels: skip-changelog-update

#3783 Bump version to 2.11.5
  cli/setup.py
  cloudformation/aws-parallelcluster.cfn.json
Labels: skip-changelog-update

#3786 Disable PlacementGroup in case of p4d.24xlarge
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
Labels: skip-changelog-update

#3771 [integ-test] Add test for invoke-scheduler-plugin-event-handler script
  cli/src/pcluster/resources/compute_node/user_data.sh
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
Labels: skip-changelog-update

#3784 Add support for NEW_CHANGED_DELETED FSx import policy
  CHANGELOG.md
  cli/src/pcluster/config/mappings.py
  cli/src/pcluster/examples/config
  cli/tests/pcluster/config/test_section_fsx.py
  tests/integration-tests/tests/storage/test_fsx_lustre.py
Labels: 2.x

#3793 Integ-tests: fix test framework
  tests/integration-tests/conftest_tests_config.py
Labels: skip-changelog-update

#3757 2.x: Re-enable DCV tests
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 2.x

#3796 Integ-tests-framework: Relax test_runner url check to accept s3 url
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update

#3790 Add prolog and epilog test in cluster without internet access
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/networking/test_cluster_networking.py
Labels: skip-changelog-update

#3789 Add prolog and epilog test in cluster without internet access
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/networking/test_cluster_networking.py
Labels: skip-changelog-update

#3802 Integ-tests: Move test_head_node_stop to us-east-2
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3782 Add imagebuilder test for scheduler plugin
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update

#3810 Move test_no_errors_in_logs before cluster update
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
Labels: skip-changelog-update

#3806 Integ-tests: Fix scaling test framework
  tests/integration-tests/README.md
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_tests_config.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/disable_hyperthreading/test_disable_hyperthreading.py
Labels: skip-changelog-update

#3812 2.x Increase timeout of head node instance to 1h
  CHANGELOG.md
  cloudformation/master-server-substack.cfn.yaml
  tests/integration-tests/configs/develop.yaml
Labels: 2.x

#3813 2.x: Re-enable p4d daily tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/pcluster.config.ini
Labels: skip-changelog-update, 2.x

#3815 Fix test parametrization
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/arm_pl/test_arm_pl.py
  tests/integration-tests/tests/cfn-init/test_cfn_init.py
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging.py
  tests/integration-tests/tests/createami/test_createami.py
  tests/integration-tests/tests/disable_hyperthreading/test_disable_hyperthreading.py
  tests/integration-tests/tests/iam/test_iam_image.py
  tests/integration-tests/tests/intel_hpc/test_intel_hpc.py
  tests/integration-tests/tests/scaling/test_mpi.py
  tests/integration-tests/tests/scaling/test_scaling.py
  tests/integration-tests/tests/schedulers/test_awsbatch.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/storage/test_ebs.py
  tests/integration-tests/tests/storage/test_efs.py
  tests/integration-tests/tests/storage/test_ephemeral.py
  tests/integration-tests/tests/storage/test_fsx_lustre.py
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#3814 2.x: Add govcloud and china owners for Ubuntu20
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 2.x

#3817 [develop] Fix ordering for get_scheduler_commands parameters
  tests/integration-tests/tests/common/schedulers_common.py
Labels: skip-changelog-update

#3822 Fix hash of Slurm 21.08.6
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
Labels: skip-changelog-update

#3823 Fix hash of Slurm 21.08.6
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
Labels: skip-changelog-update

#3830 Fix test parametrization
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#3831 Fix test parametrization
  tests/integration-tests/tests/common/mpi_common.py
  tests/integration-tests/tests/dns/test_dns.py
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/scaling/test_mpi.py
Labels: skip-changelog-update

#3832 Wrap shared bucket fixture boto3 calls with aws_credential_provider
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#3833 Fix usage of scheduler_commands_factory
  tests/integration-tests/benchmarks/test_scheduler_performance.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update

#3824 Test plugin log file permission
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
Labels: skip-changelog-update

#3825 Add systemuser validator
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/scheduler_plugin_validators.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/validators/test_scheduler_plugin_validators.py
Labels: skip-changelog-update

#3829 2.x: Fix NCCL tests using the right version of CUDA
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/nccl_benchmarks/init_nccl_benchmarks.sh
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/nccl_benchmarks/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update, 2.x

#3835 [develop] Wrap scheduler definition uploader with credential provider
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#3836 [develop] Add region to upload_artifacts util
  scheduler_plugins/plugin_template/utils/upload_artifacts.sh
  scheduler_plugins/slurm/utils/upload_artifacts.sh
Labels: skip-changelog-update

#3839 2.x: Upgrade NCCL benchmark version to 2.10.0
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/nccl_benchmarks/init_nccl_benchmarks.sh
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/nccl_benchmarks/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update, 2.x

#3840 Fix for xdist session
  tests/integration-tests/framework/fixture_utils.py
Labels: skip-changelog-update

#3841 Rename slurm scheduler plugin in tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update

#3805 2.x: Execute OSU benchmarks on 32 nodes and multi-threading disabled
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_latency
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_latency
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_collective_submit_intelmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_collective_submit_openmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_mbw_mr_submit_openmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_pt2pt_submit_intelmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_pt2pt_submit_openmpi.sh
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/pcluster.config.ini
Labels: skip-changelog-update, 2.x

#3843 Fix scheduler_plugin_configuration fixture when scheduler not present
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#3844 Fix dynamic retrieval of clustermgtd config path
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#3845 Fix parameters for fsx lustre test in private subnet
  tests/integration-tests/tests/networking/test_cluster_networking.py
Labels: skip-changelog-update
