Repository aws/aws-parallelcluster, pull requests merged in 2022-09, with the labels that each got.

#4313 [3.2.0] Move test_intel_hpc to us-east-2
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#4314 [develop] Move test_efa and test_intel_hpc to us-east-2
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x

#4308 [3.2.x] Add Name field to PlacementGroup for Scheduling.SlurmQueues.Networking
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
  cli/tests/requirements.txt
Labels: enhancement, 3.x

#4315 Describe default value of bucket-prefix in helper of export-logs command
  cli/src/pcluster/cli/commands/cluster_logs.py
  cli/src/pcluster/cli/commands/common.py
  cli/src/pcluster/cli/commands/image_logs.py
  cli/tests/pcluster/cli/test_export_cluster_logs/TestExportClusterLogsCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_export_image_logs/TestExportImageLogsCommand/test_helper/pcluster-help.txt
Labels: skip-changelog-update, 3.x

#4303 [API] Encrypt the EcrImageBuilder SNSTopic using the default AWS SNS KeyMasterKey
  CHANGELOG.md
  api/infrastructure/parallelcluster-api.yaml
Labels: 3.x

#4305 3.x Change CUDA install validation test to support both v11.4 and v11.x > 11.4 for ARM
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#4327 Fix comment
  cli/src/pcluster/aws/ec2.py
Labels: skip-changelog-update

#4323 [develop] Fix test using cheaper instance type
  tests/integration-tests/tests/update/test_update/test_update_instance_list/pcluster.config.update.remove.yaml
  tests/integration-tests/tests/update/test_update/test_update_instance_list/pcluster.config.update.yaml
Labels: skip-changelog-update

#4332 [develop] Fix test using instance with same number of vCPUs
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_update_instance_list/pcluster.config.update.remove.yaml
  tests/integration-tests/tests/update/test_update/test_update_instance_list/pcluster.config.update.yaml
Labels: skip-changelog-update

#4333 [develop] Switch from InstanceType to single instance in InstanceTypeList
  cli/src/pcluster/cli/commands/configure/easyconfig.py
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_disabled_efa_no_placement_group/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_efa_not_supported/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_default_placement_group/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_existing_placement_group/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_non_existent_placement_group/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_filtered_subnets_by_az/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_no_automation_no_awsbatch_no_errors/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_no_input_no_automation_no_errors/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_subnet_automation_no_awsbatch_no_errors/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_subnet_automation_no_awsbatch_no_errors_empty_vpc/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_vpc_automation_no_awsbatch_no_errors/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_vpc_automation_no_vpc_in_region/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_vpc_automation_no_vpc_in_region_public/pcluster.config.yaml
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_with_region_arg/pcluster.config.yaml
Labels: skip-changelog-update

#4334 [develop] Fix InstanceType name
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/pcluster.config.yaml
Labels: skip-changelog-update

#4336 [develop] Fix tests using InstanceTypeList
  tests/integration-tests/tests/configure/test_pcluster_configure.py
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#4337 [develop] Change jinja environment to be SandboxedEnvironment
  cli/tests/conftest.py
  scheduler_plugins/plugin_template/tests/render_cfn_template_test.py
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  scheduler_plugins/slurm/tests/render_cfn_template_test.py
  tests/integration-tests/conftest.py
  tests/integration-tests/framework/tests_configuration/config_generator.py
  tests/integration-tests/framework/tests_configuration/config_renderer.py
  tests/integration-tests/tests/storage/kms_key_factory.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#4338 [develop] Fix scheduler plugin test
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/pcluster.config.yaml
Labels: skip-changelog-update

#4339 Fix Trainium test assertion and region test distribution
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/trainium/test_trainium.py
Labels: skip-changelog-update

#4329 3.x Fix missing ParalellCluster cuda_version tag on AMIs
  cli/src/pcluster/resources/imagebuilder/parallelcluster_tag.yaml
Labels: skip-changelog-update, 3.x

#4340 [FIT] Add integration test for create-fleet and run-instances overrides
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tags_utils.py
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_overrides/launch_override.sh
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_overrides/pcluster.config.yaml
Labels: skip-changelog-update

#4304 [CLI] Include validation checks for Compute Resources with multiple instance types
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/common.py
  cli/src/pcluster/validators/instance_type_list_validators.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_instance_type_list_validators.py
Labels: skip-changelog-update, 3.x

#4343 Change tests for Trainium to make them more stable
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-ccl.sh
Labels: skip-changelog-update

#4345 Move Neuron package names into Secret Manager
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-installation.sh
Labels: skip-changelog-update

#4346 Move package names into Secret Manager
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-installation.sh
Labels: skip-changelog-update

#4352 [CLI] Verify that there are no duplicate instance types in an InstanceTypeList
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
Labels: skip-changelog-update, 3.x

#4354 [3.2] Move test_ad_integration to eu-west-1 to void error with fsx in ap-northeast-1c
  tests/integration-tests/configs/ad_integration.yaml
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4357 Fix undefined variable name in API client
  api/client/resources/api_client.py.patch
  api/client/resources/sigv4_auth.py
  api/client/src/pcluster_client/api_client.py
  api/client/src/pcluster_client/sigv4_auth.py
Labels: skip-changelog-update

#4353 Add unit test to verify CFN limits of generated template
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full.all_resources.yaml
Labels: skip-changelog-update

#4359 [3.x] Fix ODCR usage with Flexible Instance Types
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
Labels: skip-changelog-update

#4363 integ-test: Fix test_scheduler_plugin failed by ODCR PRs
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_x86_64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_x86_64.yaml
Labels: skip-changelog-update

#4369 [develop] Add dryrun validator test SlurmFlexibleComputeResource
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update

#4370 [3.x] integ-test: Fix test_slurm scheduler plugin
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/templates/default/slurm/cgroup.conf.erb
Labels: skip-changelog-update

#4372 Add validation recipe call to image validation
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#4376 [develop] Fix scheduler plugin test
  tests/integration-tests/tests/schedulers/test_slurm/test_error_handling/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_scaling/pcluster.config.yaml
Labels: skip-changelog-update

#4377 Fix code-linter B026 error in awsbatch-cli test
  awsbatch-cli/tests/conftest.py
Labels: skip-changelog-update

#4379 [Release-3.2] Fix code-linter B026 error in awsbatch-cli test
  awsbatch-cli/tests/conftest.py
Labels: skip-changelog-update

#4355 Move test_ad_integration to eu-west-1 to void error with fsx in ap-northeast-1c
  tests/integration-tests/configs/ad_integration.yaml
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4331 3.x Update integration test to use normalized directory name for CUDA rather than versioned directory name.
  scheduler_plugins/slurm/utils/upload_artifacts.sh
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/init_nccl_benchmarks.sh
Labels: skip-changelog-update, 3.x

#4380 [3.x] Validate capacity reservation if capacity reservation target is specified on compute resource or queue
  cli/src/pcluster/config/cluster_config.py
Labels: skip-changelog-update

#4365 3.3 Add validation between Placement Groups (PG) and On Demand Capacity Reservations (ODCRs)
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
  tests/integration-tests/README.md
  tests/integration-tests/tests/networking/test_on_demand_capacity_reservation/test_odcr/odcr.config.yaml
Labels: skip-changelog-update

#4356 Add support for Slurm Accounting
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/validators/database_validators.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_2.yaml
  cli/tests/pcluster/validators/test_database_validators.py
Labels: 3.x

#4381 [3.3] Add validator to prevent configs with CapacityReservationId and not InstanceType
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update

#4382 Rename cuda_sample_versions to cuda_samples_version
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#4383 [3.3] Update PG/ODCR validator to only check if the cr_target exists and account for no id or arn
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_all_validators_are_called/scheduler_plugin_1.yaml
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update

#4385 [CLI] Improve messaging used for CapacityType/AllocationStrategy Validation
  cli/src/pcluster/validators/instance_type_list_validators.py
  cli/tests/pcluster/validators/test_instance_type_list_validators.py
Labels: skip-changelog-update

#4388 [develop] Fix scheduler plugin test
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.broken.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.recover.yaml
Labels: skip-changelog-update

#4386 [3.3] Add validation for the Capacity Reservation Resource Group to be created from the cli
  api/infrastructure/parallelcluster-api.yaml
  cli/src/pcluster/aws/resource_groups.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/aws/test_resource_groups.py
  cli/tests/pcluster/validators/test_ec2_validators.py
  tests/iam_policies/user-role.cfn.yaml
  tests/integration-tests/tests/networking/test_on_demand_capacity_reservation/test_odcr/odcr.config.yaml
Labels: skip-changelog-update

#4389 [IntegrationTests] Use capacity-optimized allocation strategy to reduce InsufficientInstanceCapacity errors
  tests/integration-tests/tests/intel_hpc/test_intel_hpc/test_intel_hpc/pcluster.config.yaml
Labels: skip-changelog-update, 3.x
