Repository aws/aws-parallelcluster, pull requests merged in 2022-04, with the labels that each got.

#3897 Add system report function to collect system information on cluster
  tests/integration-tests/README.md
  tests/integration-tests/remote_command_executor.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/common/data/system-analyzer.sh
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/disable_hyperthreading/test_disable_hyperthreading.py
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#3914 Improve security group validation for FSx and EFS
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#3941 [Release-2.11] Add system report function to collect system information on cluster
  tests/integration-tests/README.md
  tests/integration-tests/remote_command_executor.py
  tests/integration-tests/tests/common/data/system-analyzer.sh
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/disable_hyperthreading/test_disable_hyperthreading.py
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#3942 Integ-tests: ensure EIP is not left over if VPC orInternet Gateway creation fails.
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update, 3.x

#3948 Fix run_system_analyzer to get the scheduler as an argument
  cli/tox.ini
  tests/integration-tests/README.md
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/disable_hyperthreading/test_disable_hyperthreading.py
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#3949 Use Python 3.9 for Code Checks
  .github/workflows/ci.yml
Labels: skip-changelog-update, 3.x

#3956 2.x: Manage exception in case of missing networking
  CHANGELOG.md
  cli/src/pcluster/cli.py
Labels: 2.x

#3957 Add CLI logs to bug report templates.
  .github/ISSUE_TEMPLATE/bug_report_2.md
  .github/ISSUE_TEMPLATE/bug_report_3.md
Labels: skip-changelog-update

#3950 Add validation for volume type not support IOPS
  cli/src/pcluster/validators/ebs_validators.py
  cli/tests/pcluster/validators/test_ebs_validators.py
Labels: skip-changelog-update, 3.x

#3958 Use Python 3.9 for Code Checks
  .github/workflows/ci.yml
Labels: skip-changelog-update, 3.x

#3959 Integ-tests: Add benchmark configuration to multiple EFS and FSx
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/pcluster3.yaml
Labels: skip-changelog-update, 3.x

#3967 Moving EFA tests from me-south-1 to eu-central-1
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#3969 Revert "Update aws-cdk-aws-cloudwatch requirement in /cli"
  cli/requirements.txt
Labels: skip-changelog-update, 3.x

#3971 [release-2.11] Increase sts credentials duration to 4h
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#3973 [ad integration] Fix integration tests: using the correct variable for head node instance type and setting max count equal to the first update.
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update2.yaml
Labels: skip-changelog-update

#3972 [develop] Improve message when custom component fails
  cli/src/pcluster/resources/imagebuilder/custom_script.yaml
Labels: skip-changelog-update

#3975 Update AMI List
  amis.txt
  cloudformation/aws-parallelcluster.cfn.json
Labels: skip-changelog-update

#3979 Integ-tests: ensure EIP is not left over if VPC orInternet Gateway creation fails.
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update, 2.x

#3978 Integ-tests: ensure EIP is not left over if VPC orInternet Gateway creation fails.
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update, 3.x

#3983 [integration tests] Remove switch-user from SSM command that creates directory users
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#3974 [integ-test] fast instance capacity failover
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/overrides.sh
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_config_update/pcluster.config.update.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_config_update/pcluster.config.update_scheduling.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_config_update/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#3986 [integration tests] Remove switch-user from SSM command that creates directory users
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#3970 Improve EFS and EBS boto3 calls to reduce pcluster CLI/API running time
  cli/src/pcluster/api/flask_app.py
  cli/src/pcluster/aws/aws_api.py
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/aws/ec2.py
  cli/src/pcluster/aws/efs.py
  cli/src/pcluster/aws/fsx.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/aws/test_ec2.py
  cli/tests/pcluster/aws/test_fsx.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#3987 [integration tests] Make AD integration tests create directories with random unique names to avoid collision when using a single VPC
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update

#3982 [integration tests] Make AD integration tests create directories with random unique names to avoid collision when using a single VPC
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update

#3994 3.x: Do not require Enabled set to true when passing an existing Placement Group Id
  CHANGELOG.md
  cli/src/pcluster/templates/cluster_stack.py
  tests/integration-tests/tests/networking/test_placement_group/test_placement_group/pcluster.config.yaml
Labels: 3.x

#3981 Add validator to prevent using reserved directories as mount dirs
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#3996 Upgrade Slurm to version 21.08.7
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
Labels: skip-changelog-update

#3998 [release-3.1] Exclude CDK version 1.153.0 cause it introduced a breaking change
  cli/setup.py
Labels: skip-changelog-update

#4000 Switch the order of insuffcient capacity integration test
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#3999 Fix bug in shared mount directory list
  cli/src/pcluster/config/cluster_config.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_validators_are_called_with_correct_argument/slurm.yaml
Labels: skip-changelog-update, 3.x
