Repository aws/aws-parallelcluster, pull requests merged in 2022-11, with the labels that each got.

#4477 Update tabulate requirement to >=0.8.8,<=0.8.10
  awsbatch-cli/requirements.txt
  awsbatch-cli/setup.py
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update, 3.x

#4475 Update tabulate requirement from >=0.8.2,<0.8.10 to >=0.8.8,<=0.8.10
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update, 2.x

#4495 [2.11] Backport fix integration tests for snapshot EBS and alinux2
  tests/integration-tests/tests/storage/test_ebs.py
Labels: skip-changelog-update, 2.x

#4496 [2.11] Backport align osu benchmark
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_hit_efa/osu_benchmarks/results/c5n.18xlarge/openmpi/osu_latency
Labels: skip-changelog-update, 2.x

#4500 [2.11] Backport Fix benchmark result check in case of osu_bibw test
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update, 2.x

#4502 3.3: Move c6gn.16xlarge tests to us-east-1
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x

#4503 develop: Move c6gn.16xlarge tests to us-east-1
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x

#4504 2.x: Move c6gn.16xlarge tests to us-east-1
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 2.x

#4505 2.11.7: Move c6gn.16xlarge tests to us-east-1
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 2.x

#4507 Fix description of FsxArchitectureOsValidator
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update, 3.x

#4508 [2.x][integ-tests] Fix test_ebs_snapshot volume size
  tests/integration-tests/tests/storage/test_ebs.py
Labels: skip-changelog-update, 2.x

#4510 [3.1][Integ tests] Fix test_ebs volume size
  tests/integration-tests/tests/storage/test_ebs.py
Labels: skip-changelog-update

#4511 develop: Install efibootmgr before updating Ubuntu OS packages
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#4512 3.1: Install efibootmgr before updating Ubuntu OS packages
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#4514 [3.1.x] Move the following integration tests regions to reduce the risk of insufficient capacity: test_efa and test_intel_hpc
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4515 [3.1.x] Remove Ubuntu 18 test in gov cloud aligning with develop
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4516 [3.1.x]Align instance type for intel_hpc test with develop
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4517 [2.11] Disable build_ami and runtime bake with ubuntu18 DLAMI in gov-cloud
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 2.x

#4522 Remove unneeded mock
  cli/tests/pcluster/validators/test_networking_validators.py
Labels: skip-changelog-update, 3.x

#4509 Update changelog for 2.11.8
  CHANGELOG.md
Labels: 2.x

#4527 [2.x][Integ-tests] use Capacity Reservation in multiple NICS test
  tests/integration-tests/tests/multiple_nics/test_multiple_nics.py
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.ini
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/run_instance_override.sh
Labels: skip-changelog-update, 2.x

#4523 [3.x] Integ-tests: improve test_multiple_efs
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_efs.py
Labels: skip-changelog-update

#4528 Add INFO messages in the log to better identify bottlenecks in the cluster creation
  cli/src/pcluster/models/cluster.py
Labels: skip-changelog-update

#4521 [MultiAZ] Include SubnetID only when using RunInstances API
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#4533 [3.x] Integ-tests: Fix test_multiple_efs
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_efs.py
Labels: skip-changelog-update

#4534 Remove empty capacity reservation id/resource group ARN from dict in launch template validator
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/templates/test_cdk_builder_utils.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: bug, skip-changelog-update, 3.x

#4536 [integ-tests-3.3.0] Allow fetching of deprecated Centos 7 images
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#4538 [integ-tests] Backport Allow fetching of deprecated Centos 7 images
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#4539 Update AMI List
  amis.txt
  cloudformation/aws-parallelcluster.cfn.json
Labels: skip-changelog-update

#4540 [surface head node bootstrap errors] rename error message file for both chef and custom scripts
  cli/src/pcluster/resources/head_node/user_data.sh
Labels: skip-changelog-update, 3.x

#4520 Allow to specify a VcpConfig for PCluster Lambdas
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/config/common.py
  cli/src/pcluster/config/imagebuilder_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/schemas/common_schema.py
  cli/src/pcluster/schemas/imagebuilder_schema.py
  cli/src/pcluster/templates/awsbatch_builder.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/imagebuilder_stack.py
  cli/src/pcluster/templates/slurm_builder.py
  cli/src/pcluster/validators/networking_validators.py
  cli/tests/pcluster/config/dummy_imagebuilder_config.py
  cli/tests/pcluster/schemas/test_common_schema.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_imagebuilder_stack.py
  cli/tests/pcluster/utils.py
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_all_validators_are_called/scheduler_plugin_1.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_networking_validators.py
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: 3.x

#4543 Remove unused configuration setting in build image configuration in integration tests
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: skip-changelog-update

#4545 [integ-tests] Add default security group ID to outputs of VPC stack
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update, 3.x

#4537 [develop] Add validator to avoid managed FSx storage with multiple subnets
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update

#4546 Add assert_lambda_vpc_settings_are_correct to integration tests
  tests/integration-tests/tests/common/assertions.py
Labels: skip-changelog-update

#4542 Add ComputeConsoleLogging parameters to cluster configuration schema
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/monitoring_validators.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/schemas/test_schema_validators.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full.all_resources.yaml
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_monitoring_validators.py
Labels: skip-changelog-update, 3.x

#4549 [integ-tests] Add integration test for LambdaFunctionsVpcConfig in test_build_image
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/createami/test_createami.py
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: skip-changelog-update, 3.x

#4547 Add subnet_id -> az mapping property at queue level
  cli/src/pcluster/aws/ec2.py
  cli/src/pcluster/config/cluster_config.py
  cli/tests/pcluster/aws/test_ec2.py
Labels: skip-changelog-update, 3.x

#4550 Add lambda vpc testing in private and no internet access integration tests
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_no_internet_subnet/pcluster.config.yaml
  tests/integration-tests/tests/networking/test_cluster_networking/test_cluster_in_private_subnet/pcluster.config.yaml
Labels: skip-changelog-update

#4544 EFA MultiAZ Validator (3.x)
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#4553 [3.x] Integ-tests: create mount targets when creating EFS
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_efs.py
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#4556 Suppress suggestions to use EFA when MultiAZ is enabled.
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/src/pcluster/validators/instances_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster/validators/test_instances_validators.py
Labels: skip-changelog-update, 3.x

#4558 [develop][integ-tests] Allow fetching of deprecated Centos 7 images
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#4557 Update Efs Validator Error Message
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/efs_validators.py
  cli/tests/pcluster/validators/test_efs_validators.py
Labels: skip-changelog-update

#4555 Add MultiAzPlacementGroupValidator that fails if both MultiAZ and PlacementGroup are enabled
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/networking_validators.py
  cli/tests/pcluster/validators/test_networking_validators.py
Labels: skip-changelog-update, 3.x

#4541 [Multi-AZ] Modify networking validators impacted by Multi-AZ
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/networking_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_networking_validators.py
Labels: skip-changelog-update, 3.x

#4551 [MultiAZ] Validate compatibility of a Capacity Reservation Resource Group with multiple instance types and subnets
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
  cli/tests/pcluster/validators/utils.py
Labels: skip-changelog-update, 3.x

#4531 [MultiAZ] Clarify which InstanceType parameter is referenced for the CapacityReservationValidator messaging
  cli/src/pcluster/validators/ec2_validators.py
Labels: skip-changelog-update, 3.x

#4493 Change Node version validator to use 'nvm current'
  cli/src/pcluster/api/util.py
  cli/tests/pcluster/api/test_util.py
Labels: skip-changelog-update, 3.x

#4564 Revert "Add support for ComputeConsoleLogging parameters in cluster configuration
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/monitoring_validators.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/schemas/test_schema_validators.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full.all_resources.yaml
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_monitoring_validators.py
Labels: skip-changelog-update, 3.x

#4565 Remove constraint of 1 subnet ID for Slurm and Scheduler Plugin queues
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/schemas/test_schema_validators.py
Labels: skip-changelog-update, 3.x

#4559 [surface head node bootstrap errors] rename error message file for both head node and compute node
  cli/src/pcluster/resources/head_node/user_data.sh
Labels: skip-changelog-update, 3.x

#4574 [release-3.3]Allow fetching of deprecated Centos 7 images
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#4572 [integ-tests] Make assertions on DeleteStackFunction after it has been created
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update, 3.x

#4580 Add logs:TagLogGroup and logs:UntagLogGroup actions to Parallelcluster Policy
  api/infrastructure/parallelcluster-api.yaml
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update

#4581 [3.x] Make an assertion in test_unsupported_content_type more stable
  cli/tests/pcluster/api/test_flask_app.py
Labels: skip-changelog-update

#4566 [surface head node bootstrap errors] trim error message before passing to cfn-signal
  cli/src/pcluster/resources/head_node/user_data.sh
Labels: skip-changelog-update, 3.x

#4587 Add simple api tests config
  tests/integration-tests/configs/simple-api.yaml
Labels: skip-changelog-update

#4576 [MultiAZ] Validate usage of EFS OneZone when using multiple availability zones
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#4590 Add warm-up for Lambda API
  tests/integration-tests/tests/pcluster_api/test_api.py
Labels: skip-changelog-update

#4593 [3.x] Change validation failure level from WARNING to ERROR if EBS is not available
  cli/src/pcluster/validators/ebs_validators.py
Labels: skip-changelog-update

#4595 Rename validator checking single InstanceType with MultiAZ
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/networking_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_networking_validators.py
Labels: skip-changelog-update

#4602 [develop] Fix flake8 config
  awsbatch-cli/.flake8
  cli/.flake8
Labels: skip-changelog-update

#4603 [release-3.3] Fix flake8 config
  awsbatch-cli/.flake8
  cli/.flake8
Labels: skip-changelog-update

#4598 [3.x] Rebelance integration tests
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4601 [3.x] Move the postupdate logic inside the chef update to easily handle signal, this is temporary
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#4592 2.x: Block cluster update when using a managed FSx and vpc_security_group_id is modified
  CHANGELOG.md
  cli/src/pcluster/config/mappings.py
  cli/src/pcluster/config/update_policy.py
  cli/tests/pcluster/config/test_config_patch.py
  cli/tests/pcluster/config/test_config_patch/test_single_param_change/pcluster.config.ini
  cli/tests/pcluster/config/test_config_patch/test_vpc_security_id_changes/pcluster.config.ini
Labels: 2.x

#4573 Add Unmanaged FSx multiple AZ validator.
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#4604 [MultiAZ] Validate PlacementGroup compatibility with Capacity Reservation only for Single Subnet Queues
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update, 3.x

#4608 2.x: Print changes in the vpc_security_group_id when the update is allowed
  cli/src/pcluster/config/update_policy.py
  cli/tests/pcluster/config/test_config_patch.py
Labels: skip-changelog-update, 2.x

#4609 [Develop][SubnetUpdate] Block subnet updates when using a managed Fsx for Lustre FileSystem
  CHANGELOG.md
  cli/src/pcluster/config/update_policy.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/config/test_config_patch.py
  cli/tests/pcluster/config/test_update_policy.py
Labels: 3.x

#4611 Move test_efa with c6gn.16xlarge from IAD to DUB to mitigate ICE
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4614 Move test_efa with c6gn.16xlarge from IAD to DUB to mitigate ICE
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4619 2.11.8 Merge fixes for integration tests from release-2.11 into integ-tests-2.11.8
  .github/workflows/ci.yml
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 2.x

#4620 [integ-tests] Rebelance integration tests
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4618 [develop] Allow update on subnet addition
  cli/src/pcluster/config/update_policy.py
  cli/tests/pcluster/config/test_update_policy.py
Labels: skip-changelog-update

#4621 [3.x] Fix test_on_demand_capacity_reservation
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/networking/test_on_demand_capacity_reservation/test_on_demand_capacity_reservation/pcluster.config.yaml
Labels: skip-changelog-update

#4625 Add DescribeStacks permission to Slurm HeadNode instance profile
  tests/iam_policies/cluster-roles.cfn.yaml
Labels: skip-changelog-update, 3.x

#4628 Update changelog for 3.3.1
  CHANGELOG.md
Labels: 3.x

#4627 [MultiAZ] Validate Capacity Reservation Instance Type compatibility per Availability Zone
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update, 3.x

#4626 [integ-tests] Check that update is rolled back if post update script fails
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_update_slurm/failed_postupdate.sh
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
Labels: skip-changelog-update, 3.x

#4606 3.x: Use the original official AMI when updating the cluster
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/models/cluster_resources.py
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#4632 Adds MultiAzRootNodeValidator and aggregates multiple notifications for MultiAzEbsVolumeValidator
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ebs_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#4634 [Integ-tests] Fix test_on_demand_capacity_reservation
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/networking/test_on_demand_capacity_reservation/test_on_demand_capacity_reservation/pcluster.config.yaml
Labels: skip-changelog-update

#4631 [develop][MultiAZ] Improve MultiAZ validation messaging
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/src/pcluster/validators/ebs_validators.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/src/pcluster/validators/networking_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
  cli/tests/pcluster/validators/test_networking_validators.py
Labels: skip-changelog-update, 3.x

#4637 Move efa benchmark test to eu-west-1 for capacity
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x
