Repository aws/aws-parallelcluster, pull requests merged in 2023-03, with the labels that each got.

#4983 Fix integration test: add alarm actions to permission boundary of the iam integration test
  tests/integration-tests/tests/iam/test_iam.py
Labels: skip-changelog-update, 3.x

#4980 Disable checks that we need to skip on RHEL8
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#4982 `[cloudformation]` Add ability to create VPC in networking CFN stacks.
  cloudformation/networking/public-private.cfn.json
  cloudformation/networking/public.cfn.json
  cloudformation/tests/conftest.py
  cloudformation/tests/test_networking.py
  cloudformation/tests/test_policies.py
Labels: skip-changelog-update

#4986 [3.x] Specify ImageBuilderSubnetId should be public
  api/infrastructure/parallelcluster-api.yaml
Labels: skip-changelog-update

#4990 [develop] Change fixture scope in test_ad_integration
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update, 3.x

#4991 Add rhel8 tests to redhat8.yaml config file
  tests/integration-tests/configs/redhat8.yaml
Labels: skip-changelog-update

#4985 [Multi User] Add support for AD password as SSM Parameter.
  cli/src/pcluster/aws/aws_api.py
  cli/src/pcluster/aws/ssm.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/validators/directory_service_validators.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/aws/test_aws_api.py
  cli/tests/pcluster/aws/test_ssm.py
  cli/tests/pcluster/templates/test_directory_service.py
  cli/tests/pcluster/templates/test_directory_service/test_head_node_permissions/config-ssm.yaml
  cli/tests/pcluster/validators/test_directory_service_validators.py
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x

#4992 [Isolated Regions] Move logic to configure an instance for US isolated regions from CloudInit x-shellscript phase to CloudInit cloud-boothook phase.
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
Labels: skip-changelog-update, 3.x

#4993 [Isolated Regions] Set the default root volume size to the default EBS volume size (35Gb) in US isolated regions.
  cli/src/pcluster/config/cluster_config.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#4440 [3.x] Improve error message when build_status tag does not exist on AMI
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update

#4981 [CDK] Move compute node IAM resources into the Compute Fleet Construct
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/slurm_builder.py
Labels: skip-changelog-update, 3.x

#4997 [Isolated Regions] Fix resolution of CloudFormation endpoint, that is injected into the head node user data.
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update, 3.x

#4998 [Isolated Regions] [IntegTest] Add more tests cases to the test config for US Isolated regions.
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#4996 [Integ-tests] Improve test_slurm_update to be compatible with isolated regions
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.yaml
Labels: skip-changelog-update

#4999 [Isolated Regions] [Test] Make EBS settings in cluster configurations compatible with US isolated regions.
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_x86_64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_x86_64.yaml
  tests/integration-tests/tests/storage/test_ebs/test_ebs_multiple/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_drain.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_rollback.yaml
Labels: skip-changelog-update, 3.x

#5000 [Test] Fix IAM policy ParallelClusterClusterPolicy used by integration tests.
  tests/iam_policies/user-role.cfn.yaml
Labels: bug, skip-changelog-update, 3.x

#5001 [Test] Fix invalid Jinja statements in cluster config files.
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_x86_64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_x86_64.yaml
  tests/integration-tests/tests/storage/test_ebs/test_ebs_multiple/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_drain.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_rollback.yaml
Labels: bug, skip-changelog-update, 3.x

#5004 [Integ-tests] Improve test_slurm_update to be compatible with isolated regions
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.yaml
Labels: skip-changelog-update

#5005 [Isolated Regions] Set Slurm Database as unsupported in US isolated regions.
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_feature_validators.py
Labels: skip-changelog-update, 3.x

#5006 [Isolated Regions] Add region-based validation for PasswordSecretArn.
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/directory_service_validators.py
  cli/tests/pcluster/validators/test_directory_service_validators.py
Labels: skip-changelog-update, 3.x

#5009 [develop] Fix cli dimensions filtering in TestRunner
  tests/integration-tests/conftest_tests_config.py
Labels: skip-changelog-update, 3.x

#5010 [develop] Create a NAT Gateway per AZ
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update

#5003 [3.x] Add OS support files
  pc_support/merge_version_files.py
  pc_support/os_3.0.0.json
  pc_support/os_3.0.0b1.json
  pc_support/os_3.0.1.json
  pc_support/os_3.0.2.json
  pc_support/os_3.0.3.json
  pc_support/os_3.1.0b1.json
  pc_support/os_3.1.1.json
  pc_support/os_3.1.2.json
  pc_support/os_3.1.3.json
  pc_support/os_3.1.4.json
  pc_support/os_3.1.5.json
  pc_support/os_3.2.0.json
  pc_support/os_3.2.0b1.json
  pc_support/os_3.2.0b2.json
  pc_support/os_3.2.1.json
  pc_support/os_3.3.0.json
  pc_support/os_3.3.0b1.json
  pc_support/os_3.3.1.json
  pc_support/os_3.4.0.json
  pc_support/os_3.4.0b1.json
  pc_support/os_3.4.1.json
  pc_support/os_3.5.0.json
  pc_support/os_3.6.0.json
  pc_support/test_json_files/non_regex_matching.json
  pc_support/test_merge_version_files.py
  util/bump-version.sh
Labels: skip-changelog-update

#5011 [Isolated Regions] [Test] Adapt integration test 'test_iam_policies' so that it can be executed also in US isolated regions.
  tests/integration-tests/tests/iam/test_iam.py
Labels: skip-changelog-update, 3.x

#5013 [Isolated Regions] [Test] Make STS endpoint retrieval compatible with US isolated regions.
  tests/integration-tests/tests/common/utils.py
Labels: bug, skip-changelog-update, 3.x

#5014 [Isolated Regions] [Test] Fix cluster configuration used by test_ebs_multiple in US Isolated regions.
  tests/integration-tests/tests/storage/test_ebs/test_ebs_multiple/pcluster.config.yaml
Labels: bug, skip-changelog-update, 3.x

#5016 [Test] Move utility functions from 'performance_tests/common' to 'common/utils'
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/efa/test_fabric.py
Labels: skip-changelog-update, 3.x

#5017 [Isolated Regions] [Test] Add more integration tests to the test config dedicated to US isolated regions.
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5019 [Isolated Regions] [Test] Fix cluster configuration used in 'test_scheduler_plugin_integration'
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues.before_update_x86_64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_arm64.yaml
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin/test_scheduler_plugin_integration/scheduler_queues_x86_64.yaml
Labels: bug, skip-changelog-update, 3.x

#5021 Fix liter error R1710
  cli/src/pcluster/cli/commands/dcv_connect.py
Labels: skip-changelog-update

#4994 Add rhel8 tests to daily integration tests
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#5023 Permit to run system-analyzer.sh on RHEL
  tests/integration-tests/tests/common/data/system-analyzer.sh
Labels: skip-changelog-update

#5030 Move some tests from eu-west-2 to ca-central-1 and us-east-2
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#5033 [Isolated Regions] [Test] Update test config for US isolated regions
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5034 [Integ-tests] Fix isolated_regions.yaml to include expected benchmark specifications
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update

#5036 [Isolated Regions] [Test] Update test config for US isolated regions
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5043 Fix transient log rotation integtation test
  tests/integration-tests/tests/log_rotation/test_log_rotation.py
Labels: skip-changelog-update, 3.x

#5042 Fix root volume id retrieval in integration tests
  tests/integration-tests/constants.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#5046 Permit tags prefix validators to work if a tag is defined as a boolean
  cli/src/pcluster/schemas/common_schema.py
  cli/tests/pcluster/schemas/test_common_schema.py
Labels: skip-changelog-update

#5049 Disable failing RHEL8 tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#5051 [Isolated Regions] pcluster configure: fix the filter used to get qualifying subnets when not running in US isolated regions.
  cli/src/pcluster/cli/commands/configure/easyconfig.py
Labels: bug, skip-changelog-update, 3.x

#5057 Improve redhat8 integration tests list
  tests/integration-tests/configs/redhat8.yaml
Labels: skip-changelog-update

#5053 [Isolated Regions] Remove us-iso-west-1 from supported regions.
  cli/src/pcluster/constants.py
Labels: skip-changelog-update, 3.x

#5052 [Isolated Regions] [Test] Excluding the test 'test_iam_image.py::test_iam_roles' from test config for US isolated regions
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5050 [Versioning] Update CHANGELOG for release 3.5.1.
  CHANGELOG.md
Labels: 3.x

#5055 [Isolated Regions] [Test] Allow private ParallelCluster AMIs in isolated regions to facilitate testing for test case test_queue_parameters_update
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#5060 Add RedHat 8.7 to the remarkable AMI list
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#5063 [Isolated Regions] [Test] Fix test configuration for 'test_iam.py::test_iam_roles'.
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5064 [Isolated Regions] [Test] Enforce multi-AZ checks on us-isob-east-1.
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update, 3.x

#5059 [IntegTests] Fix Multi-AZ create/update integration test failures
  tests/integration-tests/conftest.py
Labels: skip-changelog-update, 3.x

#5066 Removing alinux2 from `test_on_demand_capacity_reservation`
  tests/integration-tests/configs/redhat8.yaml
Labels: skip-changelog-update, 3.x

#5067 Upgrade CodeQL GitHub Action to v2
  .github/workflows/codeql-analysis.yml
Labels: skip-changelog-update

#5069 Accept 9.7 and 9.8 for ebs volume size.
  tests/integration-tests/tests/storage/test_ebs.py
Labels: skip-changelog-update, 3.x

#5070 Enable test_ebs_existing on rhel8
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#5071 Disable nccl_benchmarks for rhel8
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update, 3.x

#5072 [Versioning] Update changelog for 3.5.1 adding bug fixes.
  CHANGELOG.md
Labels: 3.x

#5073 Ignore personal integration test scripts and configs
  tests/integration-tests/.gitignore
  tests/integration-tests/configs/.gitignore
Labels: skip-changelog-update, 3.x

#5074 [Test] Add permission dynamodb:BatchGetItem to cluster-roles.cfn.yaml
  tests/iam_policies/cluster-roles.cfn.yaml
Labels: skip-changelog-update, 3.x

#5075 [Test] Add permission ec2:GetConsoleOutput to cluster-roles.cfn.yaml
  tests/iam_policies/cluster-roles.cfn.yaml
Labels: skip-changelog-update, 3.x

#5078 Remove redhat8 from ARM PL test
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#5035 [NestedStack] Create compute fleet resources in a nested stack
  cli/src/pcluster/aws/cfn.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/models/s3_bucket.py
  cli/src/pcluster/templates/cdk_artifacts_manager.py
  cli/src/pcluster/templates/cdk_builder.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/conftest.py
  cli/tests/pcluster/cli/test_commands.py
  cli/tests/pcluster/models/dummy_s3_bucket.py
  cli/tests/pcluster/models/test_cluster.py
  cli/tests/pcluster/templates/test_additional_packages.py
  cli/tests/pcluster/templates/test_capacity_reservation.py
  cli/tests/pcluster/templates/test_cdk_artifacts_manager.py
  cli/tests/pcluster/templates/test_cdk_builder_utils.py
  cli/tests/pcluster/templates/test_cdk_manifest_reader/manifest.json
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_dev_settings.py
  cli/tests/pcluster/templates/test_directory_service.py
  cli/tests/pcluster/templates/test_iam.py
  cli/tests/pcluster/templates/test_scheduling.py
  cli/tests/pcluster/templates/test_shared_storage.py
  cli/tests/pcluster/utils.py
Labels: skip-changelog-update, 3.x

#5081 Create a RootVolumeEncryptionConsistencyValidator
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#5045 Fix bug in ImageBuilder resources tagging
  CHANGELOG.md
  cli/src/pcluster/templates/imagebuilder_stack.py
  cli/tests/pcluster/templates/test_imagebuilder_stack.py
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/createami/test_createami.py
Labels: 3.x

#5088 [Isolated Regions] [Test] Remove test case 'test_cluster_in_private_subnet' from isolated regions config
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5084 Add MultiNetworkInterfacesInstancesValidator
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#5090 Fix MultiNetworkInterfacesInstancesValidator failure messages
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#5092 Add json event logs to log rotation integration test
  tests/integration-tests/tests/log_rotation/test_log_rotation.py
Labels: skip-changelog-update

#5099 Increase limit on number of queues per cluster
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/src/pcluster/models/s3_bucket.py
  cli/src/pcluster/templates/cdk_artifacts_manager.py
  cli/src/pcluster/templates/cdk_builder.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/compute_fleet_stack.py
  cli/src/pcluster/templates/queue_group_stack.py
  cli/src/pcluster/utils.py
  cli/tests/pcluster/templates/test_cdk_artifacts_manager.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_all_validators.py
Labels: 3.x

#5102 Fix integration test of cw logging by write dummy message to empty log
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging.py
Labels: skip-changelog-update

#5098 remove custom actions from dna.json
  .pre-commit-config.yaml
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/queue_group_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_head_node_dna_json/head_node_default.dna.json
Labels: component:cli, skip-changelog-update, 3.x

#5097 Fix API client patch file
  api/client/patch-client.sh
  api/client/resources/api_client.py.patch
Labels: skip-changelog-update

#5108 [3.5] Add installer integration test config
  .github/workflows/ci.yml
  api/spec/build-model.sh
  tests/integration-tests/configs/installer.yaml
Labels: skip-changelog-update

#5109 [3.x] Add installer integration test config
  tests/integration-tests/configs/installer.yaml
Labels: skip-changelog-update

#5107 Remove metric filter for AmiLargerThanRootVolume
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
Labels: skip-changelog-update

#5111 Delete test_all_validators for SchedulerPlugin
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_all_validators_are_called/scheduler_plugin_1.yaml
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_all_validators_are_called/scheduler_plugin_2.yaml
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_validators_are_called_with_correct_argument/scheduler_plugin.yaml
Labels: skip-changelog-update, 3.x

#5104 multiple custom actions support in yaml schema
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/config/dummy_cluster_config.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/schemas/test_cluster_schema/test_scheduler_constraints_for_custom_actions/awsbatch.on_node_configured.yaml
  cli/tests/pcluster/schemas/test_cluster_schema/test_scheduler_constraints_for_custom_actions/slurm.on_node_start.yaml
Labels: 3.x

#5119 [develop] Adds Schedulers dedicated test config
  tests/integration-tests/configs/schedulers.yaml
Labels: skip-changelog-update, 3.x

#5117 [IntegTest] Retrieve resources from nested stacks
  tests/integration-tests/tests/networking/test_placement_group.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#5120 Enable Active Directory end to end tests for rhel8 on redhat8 test config
  tests/integration-tests/configs/redhat8.yaml
Labels: skip-changelog-update

#5122 Revert "`[integ-tests/custom_resource]` Move testing to framework"
  cloudformation/custom_resource/cluster-1-click.yaml
  cloudformation/tests/test_cluster.yaml
  cloudformation/tests/test_cluster_custom_resource.py
  tests/integration-tests/README.md
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/configs/custom_resource.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_resource_bucket.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/custom_resource/__init__.py
  tests/integration-tests/tests/custom_resource/conftest.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#5123 Add integration test for OnNodeStartExecutionError
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#5124 Fix OnNodeStartExecutionErrors in integration test
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#5130 3.x Fix expected to match custom action changes
  tests/integration-tests/tests/create/test_create.py
Labels: skip-changelog-update, 3.x

#5113 3.x Add test for custom action failure events
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/dashboard_and_alarms/structured_log_event_utils.py
  tests/integration-tests/tests/dashboard_and_alarms/test_structured_log_events.py
  tests/integration-tests/tests/dashboard_and_alarms/test_structured_log_events/test_custom_compute_action_failure/on_compute_configured_error.sh
  tests/integration-tests/tests/dashboard_and_alarms/test_structured_log_events/test_custom_compute_action_failure/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#5131 Revert "Revert "`[integ-tests/custom_resource]` Move testing to frame…
  cloudformation/custom_resource/cluster-1-click.yaml
  cloudformation/tests/test_cluster_custom_resource.py
  tests/integration-tests/README.md
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/configs/custom_resource.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_resource_bucket.py
  tests/integration-tests/resources/cluster_custom_resource.yaml
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/custom_resource/__init__.py
  tests/integration-tests/tests/custom_resource/conftest.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#5121 [3.x] Let the credential be refreshed automatically
  tests/integration-tests/framework/credential_providers.py
Labels: skip-changelog-update

#5138 Substitute override with dimension property in custom metric filter
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
Labels: skip-changelog-update, 3.x
