Repository aws/aws-parallelcluster, pull requests merged in 2023-07, with the labels that each got.

#5445 Add ELBv2 boto3 client and some methods
  cli/src/pcluster/aws/elb.py
  cli/tests/pcluster/aws/test_elb.py
Labels: skip-changelog-update, 3.x

#5447 [Integ-tests] Extend timeout to wait for node state update
  tests/integration-tests/tests/common/schedulers_common.py
Labels: skip-changelog-update

#5417 Adding Integration test to automate performance testing using starCCM
  tests/integration-tests/configs/starccm.yaml
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_starccm.py
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/starccm.install.sh
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/starccm.results.sh
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/starccm.slurm.sh
Labels: skip-changelog-update

#5451 Remove dryrun argument from validate_create_request
  cli/src/pcluster/api/controllers/cluster_operations_controller.py
Labels: skip-changelog-update

#5452 [release-3.6] Comment AWS Batch tests
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#5459 Force the remote command executor to use only the key provided and add ubuntu2204 to integ test utils
  tests/integration-tests/remote_command_executor.py
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#5461 Add ubuntu2204 to the OSS_ lists
  tests/integration-tests/configs/common.jinja2
Labels: skip-changelog-update

#5462 [Integ-test] Add test_slurm_custom_partitions to common.yaml
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#5463 Add ubuntu 2204 to integration test configs develop and common
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#5440 Add a LifeCycle hook to the login nodes AutoScaling Group
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_traffic_management_resources_values_properties/test-login-nodes-stack.yaml
Labels: skip-changelog-update, 3.x

#5466 Remove Ubuntu 22 from the remarkable AMI list until Deep Engine provides an AMI
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#5467 Ubuntu 22 remarkable AMIs are not available, so use default in test_build_image as well
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#5469 update rsa keys in test_ad_integration to ed25519 keys to match the cookbook
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update

#5470 Update instance type to one that exists in ap-east-1 for test_slurm_fast_capacity_failover
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
Labels: skip-changelog-update

#5457 Lambda function process job data, push instance-to-node mapping to Op…
  cli/src/pcluster/resources/custom_resources/OpenSearch_lambda/Lambda_pushing_events_to_OpenSearch.py
Labels: skip-changelog-update

#5471 Trainium with neuron is not yet supported for Ubuntu 22. Fix test_create expected message
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/create/test_create.py
Labels: skip-changelog-update

#5455 [Test]Changing s3 URI for performance testing using starCCM+.
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/starccm.install.sh
Labels: skip-changelog-update

#5474 Avoid to call describe login nodes if they are not in the cluster config
  cli/src/pcluster/models/cluster.py
  cli/tests/pcluster/api/controllers/test_cluster_operations_controller.py
  cli/tests/pcluster/models/test_cluster.py
Labels: skip-changelog-update, 3.x

#5473 Remove `h1.2xlarge` instance type from the test_ephemeral tests
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#5465 [3.x]Change default of ImdsSupport from V1.0 to V2.0
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/config/common.py
  cli/src/pcluster/config/imagebuilder_config.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/templates/test_imagebuilder_stack.py
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/create/test_create.py
  tests/integration-tests/tests/create/test_create/test_create_imds_secured/pcluster.config.yaml
  tests/integration-tests/tests/createami/test_createami.py
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
  tests/integration-tests/tests/createami/test_createami/test_kernel4_build_image_run_cluster/image.config.yaml
Labels: 3.x

#5476 [integ-tests-3.6] Remove `h1.2xlarge` instance type from the test_ephemeral integration…
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#5481 [develop] Remove custom AMI from fast_failover test
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5480 [develop] Add DirectoryService config in login nodes dna.json
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/login_nodes_stack.py
Labels: skip-changelog-update, 3.x

#5483 Skip Login Nodes check for awsbatch scheduler
  cli/src/pcluster/models/cluster.py
  cli/tests/pcluster/models/test_cluster.py
Labels: skip-changelog-update, 3.x

#5450 Add validators for LoginNodes
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/schemas/test_schema_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
Labels: skip-changelog-update, 3.x

#5478 Lambda function process job data, retrieve instance-to-node mapping from OpenSearch, push job data to OpenSearch
  cli/src/pcluster/resources/custom_resources/OpenSearch_lambda/Lambda_pushing_events_to_OpenSearch.py
Labels: skip-changelog-update

#5485 Update the AD integration test to use the new ED25519 keys that are generated in the cookbook
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update

#5487 [Performance Tests] Fix StarCCM package URI.
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/starccm.install.sh
Labels: skip-changelog-update, 3.x

#5486 Use the pinned Ubuntu 22.04 image for build tests for compatibility with gdrcopy and lustre client
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#5484 Give LoginNodes' ssh keyname a default value as HeadNode's keyname
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack-without-ssh.yaml
Labels: skip-changelog-update, 3.x

#5491 [Login Nodes] Add 'dns_domain' and 'hosted_zone' to dna.json in login nodes
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/login_nodes_stack.py
Labels: skip-changelog-update, 3.x, Environment

#5490 Ignore describe-cluster exceptions when getting information about login nodes
  cli/src/pcluster/api/controllers/cluster_operations_controller.py
Labels: skip-changelog-update

#5492 Align vCPUs for fast_capacity_failover test config
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
Labels: skip-changelog-update

#5493 [Integ-tests] Remove unused fixture usage
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update

#5495 Use ED25519 keys for cluster_user.py in integ tests
  tests/integration-tests/tests/ad_integration/cluster_user.py
Labels: skip-changelog-update

#5497 ap-east-1 has limited instance type availability - use M5 instead of M4
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
Labels: skip-changelog-update

#5498 Restrict permissions associated to the LoginNodes
  cloudformation/policies/parallelcluster-policies.yaml
Labels: skip-changelog-update, 3.x

#5499 Retrieve Login Nodes pool based on its name in the describe cluster
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/models/login_nodes_status.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/models/test_login_nodes_status.py
Labels: skip-changelog-update, 3.x

#5489 Allow configuration of Cloudwatch log collection on login nodes
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/login_nodes_stack.py
Labels: skip-changelog-update, 3.x

#5494 [Refactor only] Remove class CommonSchedulerClusterConfig
  cli/src/pcluster/config/cluster_config.py
Labels: skip-changelog-update

#5503 Pin PyYAML to version 5.3.1
  cli/requirements.txt
  cli/setup.py
  cloudformation/tests/requirements.txt
Labels: skip-changelog-update, 3.x

#5506 Fix CloudWatch logging test
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging.py
Labels: skip-changelog-update, 3.x

#5502 [integ-tests] Fix failures of test_ad_integration
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update

#5475 [Test]Adding Integration test to automate performance testing using O…
  tests/integration-tests/configs/openfoam.yaml
  tests/integration-tests/tests/performance_tests/test_openfoam.py
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/openfoam.install.sh
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/openfoam.results.sh
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/openfoam.slurm.sh
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5508 [Login Nodes] Extend update policy for DirectoryService and SharedStorage
  cli/src/pcluster/config/update_policy.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/config/test_update_policy.py
Labels: skip-changelog-update, 3.x, Environment

#5516 [Integ-test]Change Ubuntu2004 Deep Learning AMI to use newer CUDA version
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#5518 [Directory Service] Remove redundant tests, keeping only SimpleAD with LDAP and MicrosoftAD with LDAPS.
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update, 3.x

#5519 Add read_only user in LoginNode dna.json
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/login_nodes_stack.py
Labels: skip-changelog-update, 3.x

#5520 [Login Nodes] Add lifecycle hook for node launch in login nodes ASG
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#5521 [Login Nodes] Fix logic that checks number of healthy/unhealthy login nodes
  cli/src/pcluster/models/cluster.py
Labels: bug, skip-changelog-update, 3.x

#5522 Add switch for ARM PL on Ubuntu 22
  tests/integration-tests/tests/arm_pl/test_arm_pl.py
Labels: skip-changelog-update

#5529 [release-3.7] Add scaffolding to test login nodes dna_json
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_login_node_dna_json/login-basic-config.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_node_dna_json/login-with-directory-service.yaml
  cli/tests/pcluster/utils.py
Labels: skip-changelog-update, 3.x

#5530 [release-3.7] Add DescribeTags to LoginNode policy for user_role
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x

#5531 Removing Instances from config file and replacing it with InstanceTypes when using --force-run-instances option
  tests/integration-tests/conftest.py
Labels: skip-changelog-update, 3.x

#5533 Use the base dir based on os for armpl tests
  tests/integration-tests/tests/arm_pl/test_arm_pl.py
Labels: skip-changelog-update

#5534 Extend fast ICE failover to include nodes that are launched using job-level scaling
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5532 Use the base dir based on os for armpl tests
  tests/integration-tests/tests/arm_pl/test_arm_pl.py
Labels: skip-changelog-update

#5525 Add Integration test for cluster Updates (add, remove LN pools)
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_login_nodes_count_update/pcluster_create_without_login_nodes.config.yaml
  tests/integration-tests/tests/update/test_update/test_login_nodes_count_update/pcluster_update_login_nodes_count_to_0.config.yaml
  tests/integration-tests/tests/update/test_update/test_login_nodes_count_update/pcluster_update_login_nodes_count_to_3.config.yaml
Labels: skip-changelog-update, 3.x

#5537 Add Integration test of testing add/remove LoginNode Pools
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_login_nodes_count_update/pcluster_create_without_login_nodes.config.yaml
  tests/integration-tests/tests/update/test_update/test_login_nodes_count_update/pcluster_update_login_nodes_count_to_0.config.yaml
  tests/integration-tests/tests/update/test_update/test_login_nodes_count_update/pcluster_update_login_nodes_count_to_3.config.yaml
Labels: skip-changelog-update, 3.x
