Repository aws/aws-parallelcluster, pull requests merged in 2023-09, with the labels that each got.

#5683 Pass value of AssignPublicIp config param to LT associate_public_ip_address property
  cli/src/pcluster/templates/queues_stack.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update

#5685 Remove tox dependency on `pytest-travis-fold`
  awsbatch-cli/tox.ini
  cli/tox.ini
Labels: skip-changelog-update, 3.x

#5672 Attach a managed SSM Instance policy to the instance used when running the EBS snapshot factory
  tests/integration-tests/tests/storage/snapshots_factory.py
Labels: skip-changelog-update, 3.x

#5689 Inject SSMManagedInstanceCore policy as an additional IAM policy
  tests/integration-tests/conftest.py
  tests/integration-tests/constants.py
Labels: skip-changelog-update, 3.x

#5698 Fix CodeQL findings
  cli/src/pcluster/api/awslambda/serverless_wsgi.py
  cli/tests/pcluster/models/test_cluster.py
  cli/tests/pcluster/models/test_imagebuilder.py
  cli/tests/pcluster/templates/test_imagebuilder_stack.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster3_config_converter/test_pcluster3_config_converter.py
  tests/integration-tests/tests/schedulers/test_awsbatch.py
  util/generate-ami-list.py
  util/upload-cfn-templates.py
  util/upload-script.py
Labels: skip-changelog-update

#5699 [release-3.7][integ-tests] Improve _get_resources_with_image_resource
  tests/integration-tests/tests/iam/test_iam_image.py
Labels: skip-changelog-update

#5700 [develop][integ-tests] Improve _get_resources_with_image_resource
  tests/integration-tests/tests/iam/test_iam_image.py
Labels: skip-changelog-update

#5703 Remove api/client folder from codeQL scanning and resolve other codeQL findings
  .github/workflows/codeql-analysis.yml
  awsbatch-cli/src/awsbatch/awsbhosts.py
  awsbatch-cli/src/awsbatch/awsbqueues.py
  cli/src/pcluster/cli/commands/configure/utils.py
  cli/src/pcluster/cli/commands/ssh.py
  cli/src/pcluster3_config_converter/pcluster3_config_converter.py
  cli/tests/pcluster/models/test_cluster.py
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/conftest_resource_bucket.py
  tests/integration-tests/s3_common_utils.py
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/storage/test_ebs.py
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/utils.py
  util/generate-ami-list.py
  util/s3_factory.py
Labels: skip-changelog-update

#5708 Remove api/client from directories to scan
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: skip-changelog-update

#5712 [Test] Generate HTML report as a self-contained HTML.
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update, 3.x

#5711 Clean up imports and close file
  awsbatch-cli/src/awsbatch/awsbstat.py
  cli/src/pcluster/api/awslambda/entrypoint.py
  cli/src/pcluster/cli/commands/cluster_logs.py
  cli/src/pcluster/cli/commands/common.py
  cli/src/pcluster/cli/commands/configure/command.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  tests/integration-tests/tests/networking/test_cluster_networking.py
  util/sync_buckets.py
  util/upload-cfn-templates.py
Labels: skip-changelog-update, skip-security-exclusions-check

#5719 Remove PyYAML pin
  cli/requirements.txt
  cli/setup.py
  cloudformation/tests/requirements.txt
Labels: skip-changelog-update

#5720 [develop] Change flask version constrain format
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update

#5718 Add support for Database/DatabaseName in CLI
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
Labels: 3.x

#5726 Use DatabaseName in Slurm Accounting integ test
  tests/integration-tests/tests/schedulers/test_slurm_accounting.py
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.update.yaml
Labels: skip-changelog-update, 3.x

#5727 [Tests] Save managed storage ids and mark them for deletion right after they are created
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update
