Repository aws/aws-parallelcluster, pull requests merged in 2023-10, with the labels that each got.

#5722 Add integration test for scaling to 1000+ static nodes from an ODCR
  tests/integration-tests/configs/weekly.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/common/scaling_common.py
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/scaling/test_scaling.py
  tests/integration-tests/tests/scaling/test_scaling/test_scaling_special_cases/include_custom_partition_large.sh.jinja
  tests/integration-tests/tests/scaling/test_scaling/test_scaling_special_cases/pcluster-downscale.config.yaml
  tests/integration-tests/tests/scaling/test_scaling/test_scaling_special_cases/pcluster-upscale.config.yaml
  tests/integration-tests/tests/scaling/test_scaling/test_scaling_special_cases/pcluster.config.yaml
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#5681 [develop] Setup custom munge key
  cli/src/pcluster/aws/secretsmanager.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/validators/common.py
  cli/src/pcluster/validators/directory_service_validators.py
  cli/src/pcluster/validators/secret_validators.py
  cli/tests/pcluster/templates/test_dev_settings.py
  cli/tests/pcluster/templates/test_dev_settings/test_custom_munge_key_iam_policy/config.yaml
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_secret_validators.py
Labels: skip-changelog-update, 3.x

#5702 [develop] Add scaling_strategy optional parameter
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full.all_resources.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
Labels: skip-changelog-update, 3.x

#5728 [Rocky8] Add rocky8 in Daily Integration tests
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/common/not_released_osses.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#5735 Remove fixes in codecov.yml that were adding an extra dir layer and b…
  codecov.yml
Labels: skip-changelog-update

#5738 Modify message to check in Cinc log at the end of the update
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#5734 [Head Node Reporting] Add parameter 'Monitoring/Alarms/Enabled' to toggle cluster alarms.
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/example_configs/awsbatch.full.yaml
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full.all_resources.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  tests/integration-tests/tests/monitoring/test_monitoring.py
  tests/integration-tests/tests/monitoring/test_monitoring/test_monitoring/pcluster.config.yaml
Labels: 3.x

#5739 [Head Node Reporting] Change cluster alarms naming convention to '[cluster-name]-[component-name]-[metric]'.
  CHANGELOG.md
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  tests/integration-tests/tests/monitoring/test_monitoring.py
Labels: 3.x

#5741 [Head Node Reporting] Add head node alarms to cluster dashboard.
  CHANGELOG.md
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
Labels: 3.x

#5737 [develop] Move MungeKeySecretArn to Scheduling SlurmSettings
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/templates/test_dev_settings/test_custom_munge_key_iam_policy/config.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
Labels: skip-changelog-update, 3.x

#5743 [develop] Give public visibility to greedy-all-or-nothing scaling strategy
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update, 3.x

#5744 Disable test_intel_hpc on CentOS 7
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#5695 [develop] upgrade slurm
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5747 [Head Node Reporting] Fix regression in test_monitoring causing cluster creation failure.
  tests/integration-tests/tests/monitoring/test_monitoring.py
Labels: skip-changelog-update, 3.x

#5725 [develop] Add IAM policies for checking LoginNodes stopped script inside HeadNode
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_custom_munge_key_iam_policy/config.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_custom_munge_key_iam_policy/config_with_login_nodes.yaml
  cli/tests/pcluster/templates/test_dev_settings.py
Labels: skip-changelog-update, 3.x

#5748 [Rocky8] Removing Rocky8 from test_create_wrong_pcluster_version
  awsbatch-cli/.flake8
  cli/.flake8
  tests/integration-tests/configs/common/not_released_osses.yaml
Labels: skip-changelog-update, 3.x

#5752 Run `update` before attempting `apt-get install`
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#5750 Disable deprecated flake8-mypy Python tox check
  .github/.pre-commit-config.yaml
  .pre-commit-config.yaml
  awsbatch-cli/tox.ini
  cli/tox.ini
Labels: skip-changelog-update, 3.x

#5749 [Rocky8] Add Validator to check CustomAMI is provided when Private OSSes are used
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/common/osu_common.py
Labels: skip-changelog-update, 3.x

#5754 Upgrade Slurm to version 23.02.6
  CHANGELOG.md
Labels: 3.x

#5755 [release-3.7] Remove unnecessary version test for Slurm and PMIx
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5757 [Integ Tests]Change the assertion for AD Integ Tests for checking the content of command
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update, 3.x

#5758 Upgrade Slurm to version 23.02.6
  CHANGELOG.md
Labels: 3.x

#5759 [Integ] Adding default value for architecture param used in `inject_additional_config_settings`
  tests/integration-tests/conftest.py
Labels: skip-changelog-update, 3.x

#5761 [Integ]Adding instance fixture so that it can be used by architecture fixture when creating the cluster config file
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#5763 [Integ]Handling failures caused by fixture `instance` not found
  tests/integration-tests/configs/common/not_released_osses.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#5764 [Test] Add cloudwatch:PutCompositeAlarm to permissions boundary policy.
  tests/iam_policies/user-role.cfn.yaml
Labels: bug, skip-changelog-update, 3.x

#5762 [develop] While testing LoginNodes in private subnet accept Ssh connections from anywhere
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_from_login_nodes_in_private_network/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_from_login_nodes_in_private_network/pcluster.update.config.yaml
Labels: skip-changelog-update, 3.x

#5767 Bump version of awsbatch-cli to 1.2.0
  CHANGELOG.md
  awsbatch-cli/setup.py
Labels: skip-changelog-update, 3.x

#5768 Bump version of awsbatch-cli to 1.2.0
  CHANGELOG.md
  awsbatch-cli/setup.py
Labels: skip-changelog-update, 3.x

#5765 [develop] Increase trigger_slurm_reconfigure_race_condition of 1 minute
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#5766 [release-3.8] Increase trigger_slurm_reconfigure_race_condition of 1 minute
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#5771 Bump version to 3.8.0b1
  api/client/src/.openapi-generator/FILES
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
  cloudformation/custom_resource/cluster-1-click.yaml
  cloudformation/custom_resource/cluster.yaml
  pc_support/os_3.8.0b1.json
Labels: skip-changelog-update, 3.x

#5773 Fix test_intel_hpc integration test by disable checking expired gpg
  tests/integration-tests/tests/intel_hpc/test_intel_hpc/test_intel_hpc/install_clck.sh
Labels: skip-changelog-update

#5774 [Test] Add cloudwatch:PutCompositeAlarm to permissions boundary policy created at runtime.
  tests/integration-tests/tests/iam/test_iam.py
Labels: bug, skip-changelog-update

#5775 [Test] Add cloudwatch:PutCompositeAlarm to permissions boundary polic…
  tests/integration-tests/tests/iam/test_iam.py
Labels: bug, skip-changelog-update, 3.x

#5779 [Develop] Add internal shared directories to the list of reserved dir…
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update

#5778 [Release 3.8] Add internal shared directories to the list of reserved dir…
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update

#5780 [develop] Remove mpi job termination check from test in private network
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5781 [release-3.8] Remove mpi job termination check from test in private network
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5782 Fix test_intel_hpc integration test by disable checking expired gpg k…
  tests/integration-tests/tests/intel_hpc/test_intel_hpc/test_intel_hpc/install_clck.sh
Labels: skip-changelog-update

#5784 Rebuild attribution document
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update, 3.x, skip-security-exclusions-check

#5785 Rebuild attribution document
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update, 3.x, skip-security-exclusions-check

#5783 [Release 3.8] Add internal use EFS tests to common and develop
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_internal_efs.py
  tests/integration-tests/tests/storage/test_internal_efs/test_internal_efs/pcluster.config.yaml
Labels: skip-changelog-update

#5786 [Develop] Add internal use EFS tests to common and develop
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_internal_efs.py
  tests/integration-tests/tests/storage/test_internal_efs/test_internal_efs/pcluster.config.yaml
Labels: skip-changelog-update

#5788 [Release 3.8] Add integ test for shared /home
  tests/integration-tests/tests/storage/test_shared_home.py
  tests/integration-tests/tests/storage/test_shared_home/test_shared_home/pcluster.config.yaml
Labels: skip-changelog-update

#5770 [develop] Add custom munge key integration tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/remote_command_executor.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/schedulers/test_custom_munge_key.py
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/fail-on-node-updated.sh
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/pcluster.remove_custom_munge_key.config.yaml
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/pcluster.roll_back.config.yaml
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/pcluster.stop_login.config.yaml
Labels: skip-changelog-update, 3.x

#5791 [Integ] Reverting the change made to make AD Integ test Pass due to failure in Spack file Permission
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update, 3.x

#5796 Improve Marshmallow validation message for DatabaseName
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update, 3.x

#5795 Improve Marshmallow validation message for DatabaseName
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update, 3.x

#5794 [release-3.8] Add custom munge key integration tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/remote_command_executor.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/schedulers/test_custom_munge_key.py
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/fail-on-node-updated.sh
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/pcluster.remove_custom_munge_key.config.yaml
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/pcluster.roll_back.config.yaml
  tests/integration-tests/tests/schedulers/test_custom_munge_key/test_custom_munge_key/pcluster.stop_login.config.yaml
Labels: skip-changelog-update, 3.x

#5798 [release-3.8]Removing rocky8 from Testing for ARM instances
  tests/integration-tests/configs/common/not_released_osses.yaml
Labels: skip-changelog-update, 3.x

#5799 Removing rocky8 from Testing for ARM instances
  tests/integration-tests/configs/common/not_released_osses.yaml
Labels: skip-changelog-update, 3.x

#5802 Remove inclusion of not_released_oss.yaml from develop.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x, skip-security-exclusions-check

#5801 Remove inclusion of not_released_oss.yaml from develop.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x, skip-security-exclusions-check

#5800 Change performance test STAR-CCM version from 16 to 18
  tests/integration-tests/tests/performance_tests/test_starccm.py
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/starccm.install.sh
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/starccm.slurm.sh
Labels: skip-changelog-update

#5803 [Release 3.8] Use elastic throughput for internal shared EFS when used
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#5804 [Develop] Use elastic throughput for internal shared EFS when used
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#5807 [Develop] Add shared home integ tests to common.yaml
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#5805 [Release 3.8] Add shared home integ tests to common.yaml
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update
