Repository aws/aws-parallelcluster, pull requests merged in 2023-11, with the labels that each got.

#5811 Remove print of func names and param from pcluster CLI log
  cli/src/pcluster/cli/entrypoint.py
  cli/tests/pcluster/cli/test_entrypoint.py
Labels: skip-changelog-update

#5813 [develop] Add wait to give nodes the time to mount NFS share
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/test_mpi_job.sh
Labels: skip-changelog-update

#5814 [release-3.8] Add wait to give nodes the time to mount NFS share
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/test_mpi_job.sh
Labels: skip-changelog-update

#5815 Add more semgrep rulesets
  awsbatch-cli/tox.ini
  cli/src/pcluster/cli/model.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/common.py
  cli/tox.ini
Labels: skip-changelog-update

#5806 [develop] Rename LoginNodes Stack Target Group resource to specific schema
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#5816 [release-3.8] Rename LoginNodes Stack Target Group resource to specific schema
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#5819 [Rocky8]Update CHANGELOG.md for adding support of Rocky8
  CHANGELOG.md
Labels: 3.x

#5820 [release-3.8][Rocky8]Update CHANGELOG.md for adding support of Rocky8
  CHANGELOG.md
Labels: 3.x

#5823 [Storage] Use gp3 as default EBS volume type in ADC regions.
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/tests/pcluster/config/test_cluster_config.py
  tests/integration-tests/tests/storage/test_ebs/test_ebs_multiple/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_drain.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_rollback.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.yaml
Labels: 3.x, Environment

#5810 [release-3.8]Adding Rocky8 in common.yaml
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/common/not_released_osses.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#5809 [Integ]Adding Rocky8 in common.yaml
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/common/not_released_osses.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#5827 [develop] Increase wait to give nodes the time to mount NFS share
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/test_mpi_job.sh
Labels: skip-changelog-update

#5828 [release-3.8] Increase wait to give nodes the time to mount NFS share
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/test_mpi_job.sh
Labels: skip-changelog-update

#5824 [develop] Fix LoginNodes pool name update fail
  cli/src/pcluster/config/update_policy.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/config/test_update_policy.py
Labels: skip-changelog-update, 3.x

#5825 [Release 3.8] Add integ tests for a shared /home via FSx Lustre, FSx …
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_shared_home.py
  tests/integration-tests/tests/storage/test_shared_home/test_shared_home/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_shared_home/test_shared_home/s3_test_file
Labels: skip-changelog-update

#5826 [Develop] Add integ tests for a shared /home via FSx Lustre, FSx Onta…
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_shared_home.py
  tests/integration-tests/tests/storage/test_shared_home/test_shared_home/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_shared_home/test_shared_home/s3_test_file
Labels: skip-changelog-update

#5830 [Integ]Adding Rocky8 to test with hpc instance type
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x

#5831 [release-3.8]mAdding Rocky8 to test with hpc instance type
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x

#5833 [develop] Extend CapacityTypeValidator to ensure there is CapacityReservationId when using Capacity Blocks
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update

#5832 Test protection mode and fast capacity failover with the various scaling strategies
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.broken.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.recover.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5836 [release-3.8] Test protection mode and fast capacity failover with the various scaling strategies
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.broken.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.recover.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.yaml
Labels: skip-changelog-update

#5837 [develop][integ-test] Add GetInstanceProfile permission for integration test permission boundary
  tests/integration-tests/tests/iam/test_iam.py
Labels: skip-changelog-update

#5843 [release-3.8][integ-test] Add GetInstanceProfile permission for integration test permission boundary
  tests/integration-tests/tests/iam/test_iam.py
Labels: skip-changelog-update

#5844 [integ-test] Add GetInstanceProfile permission for integration test permission boundary
  tests/integration-tests/tests/iam/test_iam.py
Labels: skip-changelog-update

#5846 [Develop] Fix create_file_cache import after removal due to linter
  tests/integration-tests/tests/storage/test_shared_home.py
Labels: skip-changelog-update

#5840 [develop] Test scaling behaviour of job-level scaling strategies based on available capacity
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/scaling/test_scaling.py
  tests/integration-tests/tests/scaling/test_scaling/test_job_level_scaling/pcluster.config.yaml
Labels: skip-changelog-update

#5839 [release-3.8] Test scaling behaviour of job-level scaling strategies based on available capacity
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/scaling/test_scaling.py
  tests/integration-tests/tests/scaling/test_scaling/test_job_level_scaling/pcluster.config.yaml
Labels: skip-changelog-update

#5850 [Develop] Update shared home test to include mounting to multiple clu…
  tests/integration-tests/tests/storage/test_shared_home.py
Labels: skip-changelog-update

#5849 [Release 3.8] Update shared home test to include mounting to multiple…
  tests/integration-tests/tests/storage/test_shared_home.py
Labels: skip-changelog-update

#5847 [develop] Create integration tests for Capacity Blocks
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/capacity_reservations/__init__.py
  tests/integration-tests/tests/capacity_reservations/test_capacity_blocks.py
  tests/integration-tests/tests/capacity_reservations/test_capacity_blocks/test_capacity_blocks/override_capacity_blocks.sh
  tests/integration-tests/tests/capacity_reservations/test_capacity_blocks/test_capacity_blocks/pcluster.config.yaml
Labels: skip-changelog-update

#5848 [Bug Fix][develop] Fix Login Nodes Feature does not set Tags bugs
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack-with-custom-tags.yaml
Labels: skip-changelog-update, 3.x

#5854 [Bug Fix][release3.8] Fix Login Nodes Feature does not set Tags bugs
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack-with-custom-tags.yaml
Labels: skip-changelog-update, 3.x

#5855 [develop] Move job level scaling from common to develop yaml
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#5856 [release-3.8] Move job level scaling from common to develop yaml
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#5857 [develop] [integ-tests] Move ODCR e2e tests from networking to capacity_reservations folder
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/configs/new_os.yaml
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/tests/capacity_reservations/test_on_demand_capacity_reservation.py
  tests/integration-tests/tests/capacity_reservations/test_on_demand_capacity_reservation/pcluster.config.yaml
Labels: skip-changelog-update

#5862 [develop] Distinguish standard and flexible compute resource when validating ODCRs
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_slurm_validators_are_called_with_correct_argument/slurm.yaml
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update

#5864 [develop] Increase wait to give nodes the time to mount NFS share
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/test_mpi_job.sh
Labels: skip-changelog-update

#5865 [release-3.8] Increase wait to give nodes the time to mount NFS share
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/test_mpi_job.sh
Labels: skip-changelog-update

#5869 [Develop] Fix miss on renaming for PCAPIUserRole in the infrastructure
  api/infrastructure/parallelcluster-api.yaml
  tests/integration-tests/tests/pcluster_api/test_api_infrastructure.py
Labels: skip-changelog-update

#5870 [Release 3.8] Fix miss on renaming for PCAPIUserRole in the infrastru…
  api/infrastructure/parallelcluster-api.yaml
  tests/integration-tests/tests/pcluster_api/test_api_infrastructure.py
Labels: skip-changelog-update

#5859 [release-3.8][Isolated Regions]Adding Job Level Scaling and Custom Munge Key Feature Tests in isolated_regions.yaml
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_feature_validators.py
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/tests/storage/test_shared_home.py
Labels: skip-changelog-update, 3.x

#5860 [Isolated Regions] Adding Job Level Scaling and Custom Munge Key Feature Tests in isolated_regions.yaml
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_feature_validators.py
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/tests/storage/test_shared_home.py
Labels: skip-changelog-update, 3.x

#5871 [release-3.8][Isolated Region]Resolving Region as None when using FeatureRegionValidator for CBR
  cli/src/pcluster/config/cluster_config.py
Labels: skip-changelog-update, 3.x

#5872 [Isolated Region]Resolving Region as None when using FeatureRegionValidator for CBR
  cli/src/pcluster/config/cluster_config.py
Labels: skip-changelog-update, 3.x

#5873 Bump version to 3.8.0
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
  cloudformation/custom_resource/cluster-1-click.yaml
  cloudformation/custom_resource/cluster.yaml
Labels: skip-changelog-update, 3.x

#5883 [Test] Remove Ubuntu 22.04 from OpenFOAM performance tests
  tests/integration-tests/configs/openfoam.yaml
Labels: skip-changelog-update, 3.x

#5882 [Test] Remove Ubuntu 22.04 from OpenFOAM performance tests
  tests/integration-tests/configs/openfoam.yaml
Labels: skip-changelog-update, 3.x

#5887 [Isolated Region]Updating the Customer Facing Feature Name for FeatureRegionValidator
  cli/src/pcluster/constants.py
  cli/tests/pcluster/validators/test_feature_validators.py
Labels: skip-changelog-update, 3.x

#5886 [release-3.8][Isolated Regon]Updating the Customer Facing Feature Name for FeatureRegionValidator
  cli/src/pcluster/constants.py
  cli/tests/pcluster/validators/test_feature_validators.py
Labels: skip-changelog-update, 3.x

#5891 Use Rocky 8.8 AMI for test_build_image
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#5892 Use Rocky 8.8 AMI for test_build_image
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#5893 Use RHEL 8.8 AMI for test_build_image
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#5894 Use RHEL 8.8 AMI for test_build_image
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#5897 [release-3.8] Increase wait to give nodes the time to mount NFS share
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/test_mpi_job.sh
Labels: skip-changelog-update

#5898 [develop] Increase wait to give nodes the time to mount NFS share
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/test_mpi_job.sh
Labels: skip-changelog-update

#5901 [release-3.8] Use older RHEL 8.8 AMI for test_build_image
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#5903 [feature] Fix bugs in External Slurmdbd stack
  cloudformation/external-slurmdbd/external_slurmdbd/external_slurmdbd_stack.py
  cloudformation/external-slurmdbd/resources/user_data.sh
Labels: skip-changelog-update, 3.x
