Repository aws/aws-parallelcluster, pull requests merged in 2023-12, with the labels that each got.

#5906 [Performance Tests] Add coverage for all OSes supported by StarCCM+ and OpenFOAM with respective baselines.
  tests/integration-tests/configs/openfoam.yaml
  tests/integration-tests/configs/starccm.yaml
  tests/integration-tests/tests/performance_tests/test_openfoam.py
  tests/integration-tests/tests/performance_tests/test_starccm.py
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/dependencies.install.sh
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5907 [Performance Tests] Add coverage for all OSes supported by StarCCM+ and OpenFOAM with respective baselines.
  tests/integration-tests/configs/openfoam.yaml
  tests/integration-tests/configs/starccm.yaml
  tests/integration-tests/tests/performance_tests/test_openfoam.py
  tests/integration-tests/tests/performance_tests/test_starccm.py
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/dependencies.install.sh
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5905 [Release 3.8] Prevent updates to clusters that include changes to /home
  cli/src/pcluster/config/update_policy.py
  cli/tests/pcluster/config/test_update_policy.py
Labels: skip-changelog-update

#5909 Fix slurm integration tests after updating to 23.11
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5910 [release-3.8][Isolated Region] Updating the assertion of AZ returned for us-isob-east-1
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update, 3.x

#5911 [Isolated Region] Updating the assertion of AZ returned for us-isob-east-1
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update, 3.x

#5917 Add support for static private IP addressing and DNS resolution for external slurmdbd instance
  cloudformation/external-slurmdbd/external_slurmdbd/external_slurmdbd_stack.py
  cloudformation/external-slurmdbd/resources/user_data.sh
Labels: skip-changelog-update, 3.x

#5920 Fix others slurm integration tests after updating to 23.11
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5925 [release-3.8] Fix LoginNodes pool name update fail
  cli/src/pcluster/config/update_policy.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/config/test_update_policy.py
Labels: skip-changelog-update

#5918 Add performance test for startup time of compute nodes
  cli/src/pcluster/resources/compute_node/user_data.sh
  tests/integration-tests/configs/startup_time_performance.yaml
  tests/integration-tests/tests/performance_tests/test_startup_time.py
  tests/integration-tests/tests/performance_tests/test_startup_time/test_startup_time/pcluster.config.yaml
Labels: skip-changelog-update

#5930 [Performance Test] StarCCM installation: remove creation of wrong folder
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/starccm.install.sh
Labels: skip-changelog-update, 3.x

#5932 Add all OSs to the config file for startup performance test
  tests/integration-tests/configs/startup_time_performance.yaml
  tests/integration-tests/tests/performance_tests/test_startup_time.py
Labels: skip-changelog-update

#5931 Fix others slurm integration tests after updating to 23.11
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5936 [develop] Install kernel-devel for Rocky Linux from vault
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#5935 [develop] Install kernel-devel for Rocky Linux from vault
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#5934 Remove `CommunicationParameters` from the Slurm Settings deny list
  CHANGELOG.md
  cli/src/pcluster/validators/slurm_settings_validator.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: 3.x

#5939 [develop] Add support for passing Slurm patches from S3
  cli/src/pcluster/config/imagebuilder_config.py
  cli/tests/pcluster/models/test_imagebuilder.py
Labels: skip-changelog-update, 3.x

#5938 [Isolated Regions] Remove integration tests covering custom resource from isolated regions test config.
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5927 [release-3.8] Add support for passing Slurm patches from S3
  cli/src/pcluster/config/imagebuilder_config.py
  cli/tests/pcluster/models/test_imagebuilder.py
Labels: skip-changelog-update, 3.x

#5940 [Test] Capture logs in the HTML test report generated by pytest.
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update, 3.x

#5941 [Test] Capture logs in the HTML test report generated by pytest.
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update, 3.x

#5943 Update to add changelog of slurm 23.02.7
  CHANGELOG.md
Labels: 3.x

#5947 Add il-central-1 to supported regions
  cli/src/pcluster/constants.py
Labels: skip-changelog-update

#5944 [release-3.8][Isolated Region] c5a instance Family is not available in Isolated regions
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.mem-based-scheduling.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.update-schedulable-memory.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5945 [Isolated Region] c5a instance Family is not available in Isolated regions
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.mem-based-scheduling.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.update-schedulable-memory.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5949 [Test] Inject partition into policy ARNs for ad, accounting and performance tests.
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration_on_login_nodes/ad_stack.yaml
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_simple/test_simple/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.update.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting_disabled_to_enabled_update/pcluster.config.update.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting_disabled_to_enabled_update/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5953 [Test] Inject partition into policy ARNs for ad, accounting and performance tests.
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration_on_login_nodes/ad_stack.yaml
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_simple/test_simple/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.update.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting_disabled_to_enabled_update/pcluster.config.update.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting_disabled_to_enabled_update/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5960 Add il-central-1 to supported regions
  cli/src/pcluster/constants.py
Labels: skip-changelog-update

#5961 [develop][integ-tests] Avoid assuming IAM role itself.
  tests/integration-tests/framework/credential_providers.py
Labels: skip-changelog-update

#5962 [develop] Execute latest version of NCCL tests
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/init_nccl_benchmarks.sh
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update

#5959 [release-3.8] Execute latest version of NCCL tests
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/init_nccl_benchmarks.sh
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update

#5971 [release-3.8][Isolated Regions][Integ Tests] Removing one of the unsupported AZ's
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update, 3.x

#5970 [Isolated Regions][Integ Tests] Removing one of the unsupported AZ's
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update, 3.x

#5972 [release-3.8][Isolated Regions][Integ Tests] Removing one of the unsupported AZ's
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update, 3.x

#5974 [develop] Add SSM VPC Endpoints
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update

#5976 [Integ-tests-3.8.0] Add SSM VPC Endpoints
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update

#5977 [integ-tests-3.8.0] Add "Insufficient capacity" as pattern to exclude from error check
  tests/integration-tests/tests/common/assertions.py
Labels: skip-changelog-update

#5978 [3.8][Integ-tests] Add il-central-1 to daily test run
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#5979 [develop][Integ-tests] Add il-central-1 to daily test run
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#5982 Add 0 as an option for RetentionInDays cluster config param to not update CW log retention
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/tests/pcluster/schemas/test_schema_validators.py
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging.py
Labels: skip-changelog-update
