Repository aws/aws-parallelcluster, pull requests merged in 2023-01, with the labels that each got.

#4777 [3.x] Allow to skip image import when deploying an API
  api/infrastructure/deploy-api.sh
Labels: skip-changelog-update

#4754 [Test] Include testing for detached retained managed storage to the integration tests covering the dynamic file system mounting.
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/common/networking/security_groups.py
  tests/integration-tests/tests/common/storage/assertions.py
  tests/integration-tests/tests/common/storage/constants.py
  tests/integration-tests/tests/common/storage/ebs_utils.py
  tests/integration-tests/tests/common/storage/efs_utils.py
  tests/integration-tests/tests/common/storage/fsx_utils.py
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_drain.yaml
Labels: skip-changelog-update, 3.x

#4778 [3.x] Pre-import cdk libraries at the beginning of cluster create and update
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/templates/import_cdk.py
Labels: skip-changelog-update

#4773 Validate cluster name length with Slurm accounting
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: 3.x

#4780 [3.x] Test concurrent cdk import
  cli/tests/pcluster/templates/test_concurrent_cdk_import.py
Labels: skip-changelog-update

#4783 [3.x] Remove obsolete pcluster3.yaml file
  tests/integration-tests/configs/pcluster3.yaml
Labels: skip-changelog-update

#4552 3.x Add IAM Policy to allow head node to retrieve compute node console output.
  CHANGELOG.md
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/slurm_builder.py
Labels: 3.x

#4782 [3.x]Create Runtime CFN template for Custom CLI Credentials with troposphere
  tests/iam_policies/user-role.cfn.yaml
  tests/integration-tests/tests/iam/test_iam.py
  tests/integration-tests/tests/iam/test_iam/test_iam_resource_prefix/user-role-iam-resource-prefix.cfn.yaml
Labels: skip-changelog-update, 3.x

#4786 Add integration test for scontrol update nodelist sorting bug
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_scontrol_update_nodelist_sorting/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4789 Fix non existing region in integration tests config
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#4790 Fix non existing region in integration tests config
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#4794 Add launch template to disable imdsv1 in AD CloudFormation templates
  cloudformation/ad/ad-integration.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#4779 Fix bandit and semgrep findings
  awsbatch-cli/src/awsbatch/awsbhosts.py
  awsbatch-cli/src/awsbatch/awsbstat.py
  cli/src/pcluster/api/controllers/cluster_compute_fleet_controller.py
  cli/src/pcluster/api/util.py
  cli/src/pcluster/cli/commands/dcv_connect.py
  cli/src/pcluster/cli/commands/ssh.py
  cli/src/pcluster/models/cluster.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/crhelper/resource_helper.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/crhelper/utils.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/send_build_notification.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/utils.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/src/pcluster/validators/s3_validators.py
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/files/default/head_node_slurm/slurm/pcluster_slurm_config_generator.py
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/recipes/install_slurm.rb
  util/sync_buckets.py
  util/update_pcluster_configs.py
  util/upload-cookbook.py
Labels: skip-changelog-update, skip-security-exclusions-check

#4795 Include deprecated AMIs when retrieve pcluster AMI in integration test
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#4796 Move integration test test_update_slurm to ap-northeast-2
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#4787 3.x Add failure reasons on stack creation failure
  tests/integration-tests/cfn_stacks_factory.py
Labels: skip-changelog-update, 3.x

#4798 Disable B028 flake8-bugbear lint check
  awsbatch-cli/.flake8
  cli/.flake8
Labels: skip-changelog-update, 3.x

#4806 [integ-3.4] Add launch template to disable imdsv1 in AD CloudFormation templates
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/ad_stack.yaml
Labels: skip-changelog-update

#4804 [3.x] Add IMDSv2 enforcement in some utilities
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/storage/snapshots_factory.py
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#4808 [integ-tests-3.4.1] Check read-after-write consistency
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#4809 [develop] Check read-after-write consistency
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#4801 [surface headnode bootstrap error] update the general cfn-init error message
  cli/src/pcluster/resources/head_node/user_data.sh
Labels: skip-changelog-update, 3.x

#4813 [3.x] Fix IMDSv2 enforcement in launch templates
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#4814 [3.4] Fix IMDSv2 enforcement in launch templates
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#4784 3.x Integration tests for compute console output logging
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/cloudwatch_logging/test_compute_console_output_logging.py
  tests/integration-tests/tests/cloudwatch_logging/test_compute_console_output_logging/test_compute_console_logging/pcluster.config.yaml
  tests/integration-tests/tests/cloudwatch_logging/test_compute_console_output_logging/test_console_output_with_monitoring_disabled/pcluster.config.yaml
  tests/integration-tests/tests/cloudwatch_logging/test_compute_console_output_logging/test_custom_action_error/on_node_start.sh
  tests/integration-tests/tests/cloudwatch_logging/test_compute_console_output_logging/test_custom_action_error/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4567 [3.x] fix easyconfig when the AWS Account contains ipv6-only subnets
  cli/src/pcluster/cli/commands/configure/easyconfig.py
Labels: skip-changelog-update

#4820 Pass IMDS support info to validator
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update, 3.x

#4821 [Cherry-pick] Include deprecated AMIs when retrieve pcluster AMI in integration test
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#4823 Change get of node attributes to use /etc/chef/node_attributes.json
  cli/src/pcluster/resources/imagebuilder/parallelcluster_tag.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update

#4825 Use more readily available instance types for the compute ami update test
  tests/integration-tests/tests/update/test_update/test_update_compute_ami/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_compute_ami/pcluster.config.yaml
Labels: skip-changelog-update

#4826 Use more readily available instance types for the compute ami update test
  tests/integration-tests/tests/update/test_update/test_update_compute_ami/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_compute_ami/pcluster.config.yaml
Labels: skip-changelog-update

#4827 Use more readily available instance types for the compute ami update test
  tests/integration-tests/tests/update/test_update/test_update_compute_ami/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_compute_ami/pcluster.config.yaml
Labels: skip-changelog-update

#4830 Add integration test for surface headnode bootstrap failure
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/create/test_create.py
  tests/integration-tests/tests/create/test_create/test_cluster_creation_timeout/pcluster.config.yaml
  tests/integration-tests/tests/create/test_create/test_cluster_creation_with_invalid_ebs/pcluster.config.yaml
  tests/integration-tests/tests/create/test_create/test_cluster_creation_with_problematic_preinstall_script/pcluster.config.yaml
  tests/integration-tests/tests/create/test_create/test_cluster_creation_with_problematic_preinstall_script/pre_install.sh
Labels: skip-changelog-update

#4834 integ-tests-3.4.1: Use custom cookbook to solve the Ubuntu20 build failure due to MySQL installation
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: skip-changelog-update

#4837 integ-tests-3.4.1: Use https url for custom chef cookbook
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: skip-changelog-update

#4824 [3.x] Make DFSM integ tests more efficient
  tests/integration-tests/README.md
  tests/integration-tests/conftest.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/storage-stack.yaml
Labels: skip-changelog-update

#4822 [3.x]Update THIRD-PARTY-LICENSES.txt
  THIRD-PARTY-LICENSES.txt
  util/create-attribution-doc.sh
Labels: skip-changelog-update, 3.x

#4841 Upgrade Slurm to version 22.05.8
  CHANGELOG.md
  scheduler_plugins/slurm/artifacts/slurm_plugin_cookbook/attributes/default.rb
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: 3.x
