Repository aws/aws-parallelcluster, pull requests merged in 2023-05, with the labels that each got.

#5247 [release-3.6] Redirect console output from third-party imports in the CLI entrypoint to the logfile
  cli/src/pcluster/cli/entrypoint.py
Labels: skip-changelog-update, 3.x

#5245 GPU Health Check End-to-End tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/health_checks/test_gpu_health_checks.py
  tests/integration-tests/tests/health_checks/test_gpu_health_checks/test_cluster_with_gpu_health_checks/mock_failing_gpu_health_check.sh
  tests/integration-tests/tests/health_checks/test_gpu_health_checks/test_cluster_with_gpu_health_checks/mock_successful_gpu_health_check.sh
  tests/integration-tests/tests/health_checks/test_gpu_health_checks/test_cluster_with_gpu_health_checks/pcluster.config.yaml
  tests/integration-tests/tests/health_checks/test_gpu_health_checks/test_cluster_with_gpu_health_checks/restore_gpu_health_check.sh
Labels: skip-changelog-update, 3.x

#5250 Use https Url for PoliciesTemplateUri in API Stack - release 3.6
  api/infrastructure/parallelcluster-api.yaml
Labels: skip-changelog-update, 3.x

#5249 Use https Url for PoliciesTemplateUri in API Stack - develop
  api/infrastructure/parallelcluster-api.yaml
Labels: skip-changelog-update, 3.x

#5252 Add metric for GPU health check failure
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.slurm.conditional_vol.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/centos7.slurm.full.yaml
Labels: skip-changelog-update, 3.x

#5258 Replace aws-parallelcluster::validations with InSpec controls
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#5265 Revert "Export SLURM_TASKS_PER_NODE on NCCL test to avoid Slurm 23.02 bug"
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update

#5266 [3.6.0] Fix parallelcluster_validate.yaml after cuda variables name change
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update

#5273 Add InSpec tests for recipes and platform to AMI validation
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#5276 Run InSpec controls from AMI build Test phase
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update, 3.x

#5278 Add InSpec tests for aws-parallelcluster-environment cookbook
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#5281 Increase the versions requirements for aws-cdk to ~= 1.164
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update

#5285 [release-3.6]Move CDK imports under the redirect_stdouterr_to_logger contextmanager
  cli/src/pcluster/templates/cdk_builder.py
  cli/src/pcluster/validators/directory_service_validators.py
Labels: skip-changelog-update

#5284 Suppress JSII warnings for Node version
  cli/src/pcluster/cli/entrypoint.py
Labels: skip-changelog-update, 3.x

#5279 Add a timeout of 4 hours to release shared fixture lock
  tests/integration-tests/framework/fixture_utils.py
Labels: skip-changelog-update

#5298 [3.x] Remove the need of cdk arn class in PasswordSecretArnValidator
  cli/src/pcluster/validators/directory_service_validators.py
Labels: skip-changelog-update

#5292 Add a timeout of 4 hours to release shared fixture lock
  tests/integration-tests/framework/fixture_utils.py
Labels: skip-changelog-update

#5299 Don't suppress JSII Node EOL warning with `JSII_SILENCE_WARNING_END_OF_LIFE_NODE_VERSION`
  cli/src/pcluster/cli/entrypoint.py
Labels: skip-changelog-update, 3.x

#5297 Describe compute fleet resources in a single nested stack.
  CHANGELOG.md
  cli/src/pcluster/cli/commands/configure/easyconfig.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/templates/compute_fleet_stack.py
  cli/src/pcluster/templates/queues_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/validators/test_all_validators.py
  tests/integration-tests/tests/scaling/test_scaling.py
Labels: 3.x

#5301 [release-3.6] Describe compute fleet resources in a single nested stack.
  CHANGELOG.md
  cli/src/pcluster/cli/commands/configure/easyconfig.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/templates/compute_fleet_stack.py
  cli/src/pcluster/templates/queues_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/validators/test_all_validators.py
  tests/integration-tests/tests/scaling/test_scaling.py
Labels: 3.x

#5300 Fix link to CDK in README.md
  README.md
Labels: skip-changelog-update

#5302 Add Changelog entry for NVIDIA GPU scontrol reboot bug
  CHANGELOG.md
Labels: 3.x

#5303 Add Changelog entry for NVIDIA GPU scontrol reboot bug
  CHANGELOG.md
Labels: 3.x

#5305 Move pyenv checks to InSpec controls
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#5306 `[custom_resource]` Propagate tags from stack.
  cloudformation/custom_resource/cluster.yaml
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/tests/custom_resource/conftest.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update

#5309 3.x Remove cluster health metrics from ADC regions
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
Labels: skip-changelog-update, 3.x, Observability

#5310 3.6 Remove cluster health metrics from ADC regions
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
Labels: skip-changelog-update, 3.x, Observability

#5311 `[custom_resource]` Propagate tags from stack.
  cloudformation/custom_resource/cluster.yaml
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/tests/custom_resource/conftest.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update, 3.x

#5312 `[custom_resource]` Tag cluster created with custom resource.
  cli/src/pcluster/schemas/common_schema.py
  cli/tests/pcluster/schemas/test_schema_validators.py
  cloudformation/custom_resource/cluster.yaml
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update

#5313 `[custom_resource]` Tag cluster created with custom resource.
  cli/src/pcluster/schemas/common_schema.py
  cli/tests/pcluster/schemas/test_schema_validators.py
  cloudformation/custom_resource/cluster.yaml
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update

#5316 Use the compute node's IP Address instead of nodename to reduce SSH timeout errors.
  tests/integration-tests/tests/health_checks/test_gpu_health_checks.py
Labels: skip-changelog-update, 3.x

#5319 [3.x] Add an assertion to verify config tags have precedence over stack ones
  tests/integration-tests/resources/cluster_custom_resource.yaml
  tests/integration-tests/tests/custom_resource/conftest.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update

#5320 Remove tests on awscli from Test phase
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update, 3.x

#5321 [Test] Add us-iso-east-1 to isolated regions in integ test config.
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5271 [3.x][FileCache] Add Fsx FileCache in DFSM and its own Integration Tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/resources/file-cache-storage-cfn.yaml
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/storage/test_fsx_lustre.py
  tests/integration-tests/tests/storage/test_fsx_lustre/test_fsx_file_cache/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_fsx_file_cache/s3_test_file
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_drain.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/storage-stack.yaml
Labels: skip-changelog-update, 3.x

#5325 [release-3.6] Permit tags prefix validators to work if a tag is defined as a boolean
  CHANGELOG.md
  cli/src/pcluster/schemas/common_schema.py
  cli/tests/pcluster/schemas/test_common_schema.py
Labels: skip-changelog-update

#5323 [3.x FileCache]Adding unmanaged Fsx Storage(OnTap,OpenZfs,FileCache) in CW Dashboard Test
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.batch.head_node_log.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.batch.no_head_node_log.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.slurm.conditional_vol.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/centos7.slurm.full.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/rhel8.slurm.full.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/ubuntu18.slurm.no_dashboard.yaml
Labels: skip-changelog-update, 3.x

#5327 [3.6] Add an assertion to verify config tags have precedence over stack ones
  tests/integration-tests/resources/cluster_custom_resource.yaml
  tests/integration-tests/tests/custom_resource/conftest.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update

#5314 Introduce Slurm compute node priority customization
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/slurm_settings_validator.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: 3.x

#5334 Removes Weight parameter from CustomSlurmSettings integ-test
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_custom_config_parameters/pcluster.config.update.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_custom_config_parameters/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5342 Explicitly specify `region` key when formatting string
  tests/integration-tests/conftest_resource_bucket.py
Labels: skip-changelog-update, 3.x

#5343 Explicitly specify `region` key when formatting string
  tests/integration-tests/conftest_resource_bucket.py
Labels: skip-changelog-update

#5340 [develop] Avoid to run CentOS7 ARM tests in common.yaml
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#5338 Add ubuntu 22 to image builder resources
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_tag.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#5346 [Integ-tests] Simplify the initial command of RemoteCommandExecutor with a bastion
  tests/integration-tests/remote_command_executor.py
Labels: skip-changelog-update

#5344 Allow Memory Based Scheduling and FIT
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/instances_validators.py
  cli/tests/pcluster/validators/test_instances_validators.py
Labels: 3.x

#5348 [Isolated Regions][Test] Make 'test_iam_roles' executable in whatever partition.
  tests/iam_policies/cluster-roles.cfn.yaml
Labels: skip-changelog-update, 3.x, Environment

#5317 [Multi User] Enable support for Active Directory password in Secrets Manager for region us-isob-east-1.
  cli/src/pcluster/validators/directory_service_validators.py
  cli/tests/pcluster/validators/test_directory_service_validators.py
Labels: skip-changelog-update, 3.x, Environment

#5352 Create a bucket in the policies_uri_fixture when testing the API
  tests/integration-tests/tests/pcluster_api/test_api.py
Labels: skip-changelog-update, 3.x

#5353 Create a bucket in the policies_uri_fixture when testing the API
  tests/integration-tests/tests/pcluster_api/test_api.py
Labels: skip-changelog-update, 3.x

#5335 Add Changelog entry for Slurm node prioritization bug fix
  CHANGELOG.md
Labels: 3.x

#5360 [Isolated Regions][Test] Fix test config for isolated regions
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x, Environment

#5362 [Isolated Regions] Mark Slurm Accounting feature as supported in US ISO regions.
  cli/src/pcluster/constants.py
  cli/tests/pcluster/test_utils.py
Labels: skip-changelog-update, 3.x, Environment

#5363 Temporarily remove test_awsbatch during investigation
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x
