Repository aws/aws-parallelcluster, pull requests merged in 2023-04, with the labels that each got.

#5144 Add SuspendExcNodes to SLURM_SETTINGS_DENY_LIST
  cli/src/pcluster/validators/slurm_settings_validator.py
Labels: skip-changelog-update, 3.x

#5149 Rename error metric OnNodeStart/ConfiguredExecutionErrors to OnNodeStart/ConfiguredRunErrors
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  tests/integration-tests/tests/dashboard_and_alarms/test_structured_log_events.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5147 [CFNLimits] Detect new configuration sections/parameters for the CFN limit test
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full.all_resources.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
Labels: skip-changelog-update, 3.x

#5150 [Test] Fix dynamic file system mounting test by making the external storage stack retrieve the VPC stack output properly.
  tests/integration-tests/tests/update/test_update.py
Labels: bug, skip-changelog-update, 3.x

#5148 3.x Add metric for idle compute nodes
  CHANGELOG.md
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  tests/integration-tests/tests/dashboard_and_alarms/test_structured_log_events.py
  tests/integration-tests/tests/dashboard_and_alarms/test_structured_log_events/test_custom_compute_action_failure/pcluster.config.yaml
Labels: 3.x

#5154 Test AD for all oses in redhat8 pipeline
  tests/integration-tests/configs/redhat8.yaml
Labels: skip-changelog-update

#5152 [develop] Add Slurm prolog and epilog settings to deny list
  cli/src/pcluster/validators/slurm_settings_validator.py
Labels: skip-changelog-update

#5156 Remove CustomSlurmSettingsWarning
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/slurm_settings_validator.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#5132 3.x Add cluster_name to compute fleet dna.json
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/templates/queue_group_stack.py
Labels: skip-changelog-update, 3.x

#5155 [3.x] Add the output of the spawn process to stdout to ease the investigaton in case of problems
  tests/integration-tests/tests/configure/test_pcluster_configure.py
Labels: skip-changelog-update

#5161 [3.x] Add an higher timeout to the configure spawned process
  tests/integration-tests/tests/configure/test_pcluster_configure.py
Labels: skip-changelog-update

#5162 [3.x] Revert "Pass to CDK v2"
  CHANGELOG.md
  cli/requirements.txt
  cli/setup.py
  cli/src/pcluster/api/util.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/templates/awsbatch_builder.py
  cli/src/pcluster/templates/cdk_artifacts_manager.py
  cli/src/pcluster/templates/cdk_builder.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/compute_fleet_stack.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/src/pcluster/templates/imagebuilder_stack.py
  cli/src/pcluster/templates/import_cdk.py
  cli/src/pcluster/templates/queue_group_stack.py
  cli/src/pcluster/templates/slurm_builder.py
  cli/src/pcluster/validators/directory_service_validators.py
  cli/tests/conftest.py
  cli/tests/pcluster/api/test_util.py
  cli/tests/pcluster/templates/test_cdk_builder_utils.py
  cli/tests/pcluster/templates/test_imagebuilder_stack.py
Labels: skip-changelog-update

#5160 [3.x] Enforcing Serial execution for Multi-nics tests and add them in release config
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/multiple_nics/test_multiple_nics.py
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5164 [3.x] Enforcing Serial execution for Multi-nics tests and add them in release config
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/multiple_nics/test_multiple_nics.py
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5118 [3.6] Add support for the HealthChecks sections in the cluster configuration
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
Labels: 3.x

#5166 [3.x] Changing the AZ to Region for Mult-nic test
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update, 3.x

#4845 `[API]` Update to use hosted policies, lambda layer, new integ-tests
  api/README.md
  api/docker/awslambda/sam/template.yaml
  api/docker/awslambda/test-events/event.json
  api/infrastructure/deploy-api.sh
  api/infrastructure/parallelcluster-api.yaml
  cloudformation/tests/test_policies.py
  tests/integration-tests/README.md
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_resource_bucket.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
  tests/integration-tests/tests/pcluster_api/test_api_infrastructure.py
  util/bump-version.sh
Labels: skip-changelog-update

#5165 [3.x] update test_iam_image.py to poll for the image resource to exist
  tests/integration-tests/tests/iam/test_iam_image.py
Labels: skip-changelog-update, 3.x

#5167 [3.x] update test_iam_image.py to poll for the image resource to exist
  tests/integration-tests/tests/iam/test_iam_image.py
Labels: skip-changelog-update, 3.x

#5168 [3.x] update test_iam_image.py to poll for the image resource to exist
  tests/integration-tests/tests/iam/test_iam_image.py
Labels: skip-changelog-update, 3.x

#5170 Add warning about VPC usage charges in automation
  cli/src/pcluster/cli/commands/configure/easyconfig.py
Labels: skip-changelog-update

#5174 `[integ-tests/lambda-layer]` Parameterize lambda layer to copy.
  tests/integration-tests/README.md
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_resource_bucket.py
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update

#5159 `[integ-tests/custom_resource]` Exercise custom role additional policies
  tests/integration-tests/configs/custom_resource.yaml
  tests/integration-tests/resources/cluster_custom_resource.yaml
  tests/integration-tests/tests/custom_resource/conftest.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update

#5178 Update warning about VPC usage charges in automation to focus on subnet creation with pub/priv
  cli/src/pcluster/cli/commands/configure/easyconfig.py
Labels: skip-changelog-update

#5179 Remove JobCompPass from SLURM_SETTINGS_DENY_LIST
  cli/src/pcluster/validators/slurm_settings_validator.py
Labels: skip-changelog-update, 3.x

#5180 `[custom_resource]` Limit response size.
  cloudformation/custom_resource/cluster.yaml
Labels: skip-changelog-update

#5183 Add redhat8 to test_cloudwatch_logging integ-test
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging.py
Labels: skip-changelog-update

#5182 Upgrade Slurm to version 23.02.1 and munge to version 0.5.15
  CHANGELOG.md
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: 3.x

#5181 Add redhat8 update cluster integration tests in develop
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#5169 Increase limit on number of compute resources per queue
  CHANGELOG.md
  cli/src/pcluster/cli/commands/configure/easyconfig.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/templates/compute_fleet_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_resource_distribution_in_stacks/variable_queue_compute_resources.yaml
  cli/tests/pcluster/validators/test_all_validators.py
Labels: 3.x

#5186 Add Validator for total amount of tags on compute resources
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/tags_validators.py
  cli/tests/pcluster/validators/test_tags_validators.py
Labels: skip-changelog-update

#5187 `[custom_resource]` Sort configuration errors.
  cloudformation/custom_resource/cluster.yaml
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update

#5190 `[integration-tests/resource-bucket]` Fix defect in fixture for resource-bucket
  tests/integration-tests/README.md
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_resource_bucket.py
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update

#5192 `[custom_resource/networking-locatin]` Update the 1-click cluster to …
  cloudformation/custom_resource/cluster-1-click.yaml
Labels: skip-changelog-update

#5193 Add redhat8 to integration test
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#5194 `[integ-tests/custom_resource_bucket]` Update where we store the netw…
  tests/integration-tests/conftest_resource_bucket.py
Labels: skip-changelog-update

#5176 [Templates] Scope down CloudFormation permissions in 'parallelcluster-policies.yaml' template.
  cloudformation/policies/parallelcluster-policies.yaml
Labels: skip-changelog-update, 3.x

#5134 multiple custom actions validators
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/config/common.py
  cli/src/pcluster/utils.py
  cli/src/pcluster/validators/common.py
  cli/src/pcluster/validators/s3_validators.py
  cli/tests/pcluster/config/test_common.py
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_s3_validators.py
  tests/integration-tests/tests/pcluster_api/test_api.py
  tests/integration-tests/tests/pcluster_api/test_api/test_cluster_awsbatch/custom_action.sh
  tests/integration-tests/tests/pcluster_api/test_api/test_cluster_awsbatch/pcluster.config.update.yaml
  tests/integration-tests/tests/pcluster_api/test_api/test_cluster_awsbatch/pcluster.config.yaml
  tests/integration-tests/tests/pcluster_api/test_api/test_cluster_slurm/custom_action.sh
  tests/integration-tests/tests/pcluster_api/test_api/test_cluster_slurm/pcluster.config.update.yaml
  tests/integration-tests/tests/pcluster_api/test_api/test_cluster_slurm/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5196 Add CHANGELOG entry for fixing Slurm accounting password bug
  CHANGELOG.md
  tests/integration-tests/clusters_factory.py
Labels: 3.x

#5197 Modify test_slurm_accounting test to account for issue #5151
  tests/integration-tests/tests/schedulers/test_slurm_accounting.py
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.update.yaml
Labels: skip-changelog-update, 3.x

#5195 [3.x] Remove NewLine characters in THIRD-PARTY-LICENSES.txt created through create-attribution-doc.sh
  util/create-attribution-doc.sh
Labels: skip-changelog-update, 3.x

#5202 Add Changelog entry about building Slurm with support for LUA
  CHANGELOG.md
Labels: 3.x

#5200 Fix logging order of CDK template generation
  cli/src/pcluster/templates/cdk_builder.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#5204 Revert removal of wait variable in clusters_factory.py
  tests/integration-tests/clusters_factory.py
Labels: skip-changelog-update, 3.x

#5206 [Permissions] Add action 'cloudformation:ListStacks' to ParallelClusterClusterPolicy in parallelcluster-policies.yaml.
  cloudformation/policies/parallelcluster-policies.yaml
Labels: bug, skip-changelog-update, 3.x

#5208 Fix code coverage upload to Codecov
  .github/workflows/ci.yml
  awsbatch-cli/tox.ini
  cli/tox.ini
Labels: skip-changelog-update, 3.x

#5209 [3.x] Remove NewLine characters in THIRD-PARTY-LICENSES.txt created through create-attribution-doc.sh
  util/create-attribution-doc.sh
Labels: skip-changelog-update, 3.x

#5211 Add rhel8 to supported OSs for ARM (it was already in supported OSs for x86_64)
  cli/src/pcluster/cli/commands/dcv_util.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#5048 [Integ-tests] Fix _delete_volumes to use the right boto3 call
  tests/integration-tests/clusters_factory.py
Labels: skip-changelog-update

#5213 cover async validators nested execution and fix suppressor support
  cli/src/pcluster/config/common.py
  cli/tests/pcluster/config/test_common.py
Labels: skip-changelog-update, 3.x

#5215 `[cloudformation/policies]` Remove redundant condition.
  cloudformation/policies/parallelcluster-policies.yaml
Labels: skip-changelog-update

#5221 Bump version to 3.6.0b1
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
  cloudformation/custom_resource/cluster-1-click.yaml
  cloudformation/custom_resource/cluster.yaml
  pc_support/os_3.6.0b1.json
Labels: skip-changelog-update

#5220 Skip package-cleanup for redhat8 and manually clean the kernel packages
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#5222 Run schedulers workstream integ tests only on alinux2
  tests/integration-tests/configs/schedulers.yaml
Labels: skip-changelog-update, 3.x

#5224 [3.x] Update attribution doc
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update

#5223 [3.6] Update attribution doc
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update

#5229 Export SLURM_TASKS_PER_NODE on NCCL test to avoid Slurm 23.02 bug
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update

#5218 Reenable validations for functionalities previously not supported in rhel8
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#5216 3.x Add metric for GPU health check failure
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.slurm.conditional_vol.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/centos7.slurm.full.yaml
Labels: skip-changelog-update, 3.x

#5233 `[requirements/flask]` Pin flask at 2.2.x
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update

#5235 Fix parallelcluster_validate.yaml after cuda variables name change
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update

#5236 Optionally format region for resource bucket passed in config
  tests/integration-tests/conftest_resource_bucket.py
Labels: skip-changelog-update, 3.x

#5237 Document the usage of region placeholder in --resource-bucket integ test parameter
  tests/integration-tests/README.md
Labels: skip-changelog-update

#5239 Make test_slurm_memory_based_scheduling more robust
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.update-schedulable-memory.yaml
Labels: skip-changelog-update, 3.x

#5241 `[requirements/flask]` Pin flask at 2.2.x (#5233)
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update

#5242 Replace bash script with InSpec execution for ArmPL validation during AMI build
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#5212 [FSxFileCache][3.x]Adding FsxFileCacheSettings/FileCacheId Config Option under SharedStorage
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/aws/fsx.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/validators/awsbatch_validators.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/aws/test_fsx.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/templates/test_shared_storage.py
  cli/tests/pcluster/templates/test_shared_storage/test_non_happy_storage/config.yaml
  cli/tests/pcluster/templates/test_shared_storage/test_non_happy_storage/file_cache_config.yaml
  cli/tests/pcluster/templates/test_shared_storage/test_unmanaged_shared_storage_fsx/unmanaged_config.yaml
  cli/tests/pcluster/validators/test_awsbatch_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster/validators/test_feature_validators.py
Labels: skip-changelog-update, 3.x
