Repository aws/aws-parallelcluster, pull requests merged in 2023-02, with the labels that each got.

#4838 Add integration test for interaction of scontrol reboot with EC2 status checks
  CHANGELOG.md
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_scontrol_reboot_ec2_health_checks/add_sleep_to_slurmd_service_compute.sh
  tests/integration-tests/tests/schedulers/test_slurm/test_scontrol_reboot_ec2_health_checks/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_scontrol_reboot_ec2_health_checks/reset_sleep_slurmd_service_compute.sh
Labels: 3.x

#4839 3.x Add integration test for create cluster failure on PROTECTED mode
  cli/src/pcluster/resources/compute_node/user_data.sh
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode_on_cluster_create/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode_on_cluster_create/preinstall.sh
Labels: skip-changelog-update, 3.x

#4847 `[policies]` Return the Arn of ParallelClusterLambdaRole in output of policies substack
  cloudformation/policies/parallelcluster-policies.yaml
  cloudformation/tests/test_policies.py
Labels: skip-changelog-update

#4852 New entry in CHANGELOG for increased verbosity in Slurm logs
  CHANGELOG.md
Labels: 3.x

#4854 Create new integ test file to validate cookbook refactoring
  tests/integration-tests/configs/redhat8.yaml
Labels: skip-changelog-update

#4855 Add benchmarks fixture to tests requiring it
  tests/integration-tests/configs/redhat8.yaml
Labels: skip-changelog-update

#4844 [develop] Create integ tests VPC stack at regional level
  tests/integration-tests/README.md
  tests/integration-tests/conftest.py
  tests/integration-tests/network_template_builder.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/configure/test_pcluster_configure.py
  tests/integration-tests/tests/networking/test_cluster_networking.py
  tests/integration-tests/tests/scheduler_plugin/test_scheduler_plugin.py
  tests/integration-tests/tests/schedulers/conftest.py
  tests/integration-tests/tests/storage/test_ebs.py
Labels: skip-changelog-update

#4856 [integ-tests] Highlight usage of Capacity Reservations for EFA tests
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#4859 [develop] Fix name of vpc stack outputs
  tests/integration-tests/tests/schedulers/test_slurm_accounting.py
Labels: skip-changelog-update

#4761 [AWSBatch-CLI] Add Python 3.10 support
  awsbatch-cli/CHANGELOG.md
  awsbatch-cli/setup.py
Labels: skip-changelog-update

#4800 [Isolated Regions] Add support for isolated regions: us-iso-* and us-isob-*
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/src/pcluster/models/s3_bucket.py
  cli/src/pcluster/resources/batch/docker/alinux2/Dockerfile
  cli/src/pcluster/resources/batch/docker/scripts/modify_yum_vars.sh
  cli/src/pcluster/resources/batch/docker/scripts/mount_efs.sh
  cli/src/pcluster/resources/batch/docker/upload-docker-images.sh
  cli/src/pcluster/utils.py
  cli/src/pcluster3_config_converter/pcluster3_config_converter.py
  cli/tests/pcluster/models/test_s3_bucket.py
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_ebs_validators.py
  cli/tests/pcluster3_config_converter/test_data.py
  cli/tests/pcluster3_config_converter/test_pcluster3_config_converter.py
  tests/integration-tests/tests/storage/test_fsx_lustre.py
  tests/integration-tests/utils.py
Labels: 3.x

#4812 [Isolated Regions] Add validators to check features support by region
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/awsbatch_validators.py
  cli/src/pcluster/validators/feature_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_all_validators_are_called/scheduler_plugin_1.yaml
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_validators_are_called_with_correct_argument/scheduler_plugin.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_awsbatch_validators.py
  cli/tests/pcluster/validators/test_feature_validators.py
Labels: skip-changelog-update, 3.x

#4860 `[lib]` Move library functionality to module level
  cli/src/pcluster/lib/__init__.py
  cli/src/pcluster/lib/lib.py
  cli/tests/pcluster/lib/test_lib.py
Labels: skip-changelog-update

#4818 [Isolated Regions] Add controllers assertion to check operations support by region
  cli/src/pcluster/api/controllers/common.py
  cli/src/pcluster/api/controllers/image_logs_controller.py
  cli/src/pcluster/api/controllers/image_operations_controller.py
  cli/src/pcluster/cli/commands/image_logs.py
  cli/src/pcluster/cli/entrypoint.py
  cli/src/pcluster/constants.py
  cli/tests/pcluster/api/controllers/test_common.py
  cli/tests/pcluster/api/controllers/test_image_logs_controller.py
  cli/tests/pcluster/api/controllers/test_image_operations_controller.py
  cli/tests/pcluster/api/controllers/utils.py
  cli/tests/pcluster/cli/test_export_image_logs.py
Labels: skip-changelog-update, 3.x

#4864 Use ARNs of capacity reservations from boto3 instead of formatting from capacity reservation id
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/tests/pcluster/templates/test_capacity_reservation.py
Labels: 3.x

#4866 Fix flake8 repo in pre-commit config
  .pre-commit-config.yaml
Labels: skip-changelog-update, 3.x

#4871 [develp] Fix Slurm accounting update test
  tests/integration-tests/tests/schedulers/test_slurm_accounting.py
Labels: skip-changelog-update

#4867 3.5.0 `[lib]` Move library functionality to module level
  cli/src/pcluster/lib/__init__.py
  cli/src/pcluster/lib/lib.py
  cli/tests/pcluster/lib/test_lib.py
Labels: skip-changelog-update, 3.x

#4872 Remove tests in china and govcloud from redhat8 integ tests list
  tests/integration-tests/configs/redhat8.yaml
Labels: skip-changelog-update

#4873 [develop] Move networking conf into a dedicated pytest plugin
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_networking.py
  tests/integration-tests/tests/schedulers/conftest.py
Labels: skip-changelog-update

#4884 Improve visibility on test_efs_correctly_mounted
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#4886 Improve visibility on test_efs_correctly_mounted
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#4885 Improve visibility on test_efs_correctly_mounted
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#4888 [develop] Fix vpc stack for database subnet creation
  tests/integration-tests/conftest_networking.py
  tests/integration-tests/tests/schedulers/conftest.py
Labels: skip-changelog-update

#4890 [develop] Remove caching of AZ map
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update

#4892 [develop] Get subnets using VPC stack methods
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#4893 [develop] Fix configure test in bad subnet
  tests/integration-tests/tests/configure/test_pcluster_configure.py
Labels: skip-changelog-update

#4889 [integ-test] Prepare for testing with ParallelCluster Executable
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#4870 3.x Provide better diagnostics on test setup failure
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/conftest.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#4898 [develop] Fix AZ logic for ODCR test
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#4899 [develop] Fix AZ logic for storage test
  tests/integration-tests/tests/storage/test_efs/test_multiple_efs/pcluster.config.yaml
Labels: skip-changelog-update

#4896 Add skip_ice flag to ignore InsufficientInstanceCapacity errors
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/common/mpi_common.py
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#4901 [integ-3.4.1] Add skip_ice flag to ignore InsufficientInstanceCapacity errors
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/common/mpi_common.py
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#4900 [3.5] Add skip_ice flag to ignore InsufficientInstanceCapacity errors
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/common/mpi_common.py
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#4904 [release-3.5] Revert no-delete flag for ODCR stack
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#4908 [integ-test] Change test_on_demand_capacity_reservation ODCR instance type
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/networking/test_on_demand_capacity_reservation/test_on_demand_capacity_reservation/pcluster.config.yaml
Labels: skip-changelog-update

#4910 [integ-test] Change ODCR instance type
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/networking/test_on_demand_capacity_reservation/test_on_demand_capacity_reservation/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4912 [develop] Shuffle public and private tests subnets in unison
  tests/integration-tests/README.md
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/storage/test_efs/test_efs_compute_az/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_efs/test_multiple_efs/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_multi_az_fsx/pcluster-managed-fsx.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_multi_az_fsx/pcluster-unmanaged-fsx.config.yaml
  tests/integration-tests/tests/update/test_update/test_multi_az_create_and_update/pcluster_create.config.yaml
  tests/integration-tests/tests/update/test_update/test_multi_az_create_and_update/pcluster_update_1.config.yaml
  tests/integration-tests/tests/update/test_update/test_multi_az_create_and_update/pcluster_update_2.config.yaml
Labels: skip-changelog-update

#4913 Add RHEL8 to image builder components
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_tag.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#4909 Improve wrong version error message in userdata
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
Labels: skip-changelog-update

#4914 Fix variable expansions in the RHEL8 case
  cli/src/pcluster/resources/imagebuilder/parallelcluster_tag.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update

#4911 3.x Add details to integration test setup failures
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/clusters_factory.py
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/cloudwatch_logging/test_compute_console_output_logging.py
  tests/integration-tests/tests/networking/test_networking.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#4920 [develop] Fix VPC stack method name
  tests/integration-tests/tests/storage/test_efs.py
Labels: skip-changelog-update

#4921 [3.x] Add basic cli changes for RH8 for create_cluster/configure/ssh
  cli/src/pcluster/constants.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_disabled_efa_no_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_efa_not_supported/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_default_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_existing_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_non_existent_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_filtered_subnets_by_az/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_no_automation_no_awsbatch_no_errors/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_no_input_no_automation_no_errors/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_subnet_automation_no_awsbatch_no_errors/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_subnet_automation_no_awsbatch_no_errors_empty_vpc/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_vpc_automation_no_awsbatch_no_errors/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_vpc_automation_no_vpc_in_region/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_vpc_automation_no_vpc_in_region_public/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_with_region_arg/output.txt
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/rhel8.slurm.full.yaml
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update

#4922 [integ-tests-3.5.0][Fix] use PrivateSubnetId and PrivateAz2SubnetId for external-shared-storage-stack
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#4918 [release-3.5][Fix] use PrivateSubnetId and PrivateAz2SubnetId for external-shared-storage-stack
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#4928 3.x Add retry to Spot static node assertion
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#4929 3.x Add retry to Spot static node assertion
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#4930 3.x Add retry to Spot static node assertion
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#4923 [develop] Fix wrong version error message
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
Labels: skip-changelog-update

#4931 integ tests: set in the environment AWS_CREDENTIAL_EXPIRATION
  tests/integration-tests/framework/credential_providers.py
Labels: skip-changelog-update

#4932 3.x Change failing test OS to ubuntu2004 on Arm from Centos7
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#4933 3.x Change failing test OS to ubuntu2004 on Arm from Centos7
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#4934 Change failing test OS to ubuntu2004 on Arm from Centos7
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#4938 Remove obfuscation of Expiration field in the print of credentials
  tests/integration-tests/framework/credential_providers.py
Labels: skip-changelog-update

#4939 Save AWS_CREDENTIAL_EXPIRATION environment variable in ISO format
  tests/integration-tests/framework/credential_providers.py
Labels: skip-changelog-update

#4945 [Integ-test]Fix test_dynamic_file_systems_update sporadic failures
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/storage-stack.yaml
Labels: skip-changelog-update

#4944 [Isolated Regions] Add support for US isolated regions: us-iso-* and us-isob-*.
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/src/pcluster/models/s3_bucket.py
  cli/src/pcluster/resources/batch/docker/alinux2/Dockerfile
  cli/src/pcluster/resources/batch/docker/scripts/modify_yum_vars.sh
  cli/src/pcluster/resources/batch/docker/scripts/mount_efs.sh
  cli/src/pcluster/resources/batch/docker/upload-docker-images.sh
  cli/src/pcluster/utils.py
  cli/src/pcluster3_config_converter/pcluster3_config_converter.py
  cli/tests/pcluster/models/test_s3_bucket.py
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_ebs_validators.py
  cli/tests/pcluster3_config_converter/test_data.py
  cli/tests/pcluster3_config_converter/test_pcluster3_config_converter.py
  tests/integration-tests/tests/storage/test_fsx_lustre.py
  tests/integration-tests/utils.py
Labels: 3.x

#4946 3.x Disable placement group in EFA c6gn.16xlarge tests
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4947 3.x Disable placement group in EFA c6gn.16xlarge tests
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4948 3.x Disable placement group in EFA c6gn.16xlarge tests
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#4950 [Isolated Regions] Add validator FeatureRegionValidator to fail fast when a requested feature is not supported in the given region.
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/awsbatch_validators.py
  cli/src/pcluster/validators/feature_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_all_validators_are_called/scheduler_plugin_1.yaml
  cli/tests/pcluster/validators/test_all_validators/test_scheduler_plugin_validators_are_called_with_correct_argument/scheduler_plugin.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_awsbatch_validators.py
  cli/tests/pcluster/validators/test_feature_validators.py
Labels: skip-changelog-update, 3.x

#4951 [Isolated Regions] Add assertion on operations controllers to fail fast with a BadRequest when the requested operation is not supported in the given region.
  cli/src/pcluster/api/controllers/common.py
  cli/src/pcluster/api/controllers/image_logs_controller.py
  cli/src/pcluster/api/controllers/image_operations_controller.py
  cli/src/pcluster/cli/commands/image_logs.py
  cli/src/pcluster/cli/entrypoint.py
  cli/src/pcluster/constants.py
  cli/tests/pcluster/api/controllers/test_common.py
  cli/tests/pcluster/api/controllers/test_image_logs_controller.py
  cli/tests/pcluster/api/controllers/test_image_operations_controller.py
  cli/tests/pcluster/api/controllers/utils.py
  cli/tests/pcluster/cli/test_export_image_logs.py
Labels: skip-changelog-update, 3.x

#4954 [integ-test] Prepare for testing with ParallelCluster executable
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#4927 Add integration test for log rotation
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/log_rotation/test_log_rotation.py
  tests/integration-tests/tests/log_rotation/test_log_rotation/test_log_rotation/pcluster.config.yaml
Labels: skip-changelog-update

#4960 [develop] Fix typo: call unmarshal_params only once
  tests/integration-tests/conftest_tests_config.py
Labels: skip-changelog-update, 3.x

#4963 Revert "[develop] Fix typo: call unmarshal_params only once"
  tests/integration-tests/conftest_tests_config.py
Labels: skip-changelog-update

#4962 Revert "[develop] Move AZ pin for tests"
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/p4d-efa.yaml
  tests/integration-tests/configs/p4d-multinics.yaml
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update

#4953 [Isolated Regions] Fix support for US isolated regions.
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/utils.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/templates/test_cdk_builder_utils.py
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#4959 3.x Increase timeout on scontrol reboot test
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4957 3.x Increase timeout on scontrol reboot test
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4958 3.x Increase timeout on scontrol reboot test
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#4965 Fix integration test config of log rotation
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#4969 [integ-tests-3.5.0] Add flexible instance types to avoid ICE
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.yaml
Labels: skip-changelog-update

#4970 [release-3.5] Add flexible instance types to avoid ICE
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.yaml
Labels: skip-changelog-update

#4971 [develop] Add flexible instance types to avoid ICE
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.yaml
Labels: skip-changelog-update

#4974 [develop] Remove constraint on instance type for test_update_slurm
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#4935 [3.x] Add Python version parameter in create-attribution-doc.sh
  THIRD-PARTY-LICENSES.txt
  util/create-attribution-doc.sh
Labels: skip-changelog-update, 3.x

#4976 Resolve conflicts for create-attribution-doc.sh (#4935)
  THIRD-PARTY-LICENSES.txt
  util/create-attribution-doc.sh
Labels: skip-changelog-update, 3.x
