Repository aws/aws-parallelcluster, pull requests merged in 2023-08, with the labels that each got.

#5540 Add the SSM Managed Instance Policy to the networking bastion instance used in tests
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/network_template_builder.py
Labels: skip-changelog-update, 3.x

#5544 Add reset_connection method to RemoteCommandExecutor
  tests/integration-tests/remote_command_executor.py
Labels: skip-changelog-update, 3.x

#5545 [release-3.7] Add reset_connection method to RemoteCommandExecutor
  tests/integration-tests/remote_command_executor.py
Labels: skip-changelog-update, 3.x

#5546 Reset ssh connection before checking remote files
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update, 3.x

#5547 Reset ssh connection before checking remote files
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update, 3.x

#5548 [develop] Fix code-quality issue in RemoteCommandExecutor
  tests/integration-tests/remote_command_executor.py
Labels: skip-changelog-update, 3.x

#5549 [release-3.7] Fix code-quality issue in RemoteCommandExecutor
  tests/integration-tests/remote_command_executor.py
Labels: skip-changelog-update, 3.x

#5550 [develop] Reset cached values when cluster is stopped
  tests/integration-tests/clusters_factory.py
Labels: skip-changelog-update, 3.x

#5551 Reset cached values when cluster is stopped
  tests/integration-tests/clusters_factory.py
Labels: skip-changelog-update, 3.x

#5555 Pin jsii due to update issue breaking Tox
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update

#5558 [Integ-tests] Change c5n.18xlarge capacity reservation to eu-west-1 with a Placement Group
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/openfoam.yaml
  tests/integration-tests/configs/starccm.yaml
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
Labels: skip-changelog-update

#5559 [Integ-tests] Change c5n.18xlarge capacity reservation to eu-west-1 with a Placement Group
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/openfoam.yaml
  tests/integration-tests/configs/starccm.yaml
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
Labels: skip-changelog-update

#5562 [develop] Add DeleteLifecycleHook to test UserRole
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x

#5563 [Release3.7] Add DeleteLifecycleHook to test UserRole
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x

#5565 [develop] Remove caching of values from Cluster object
  tests/integration-tests/clusters_factory.py
Labels: skip-changelog-update, 3.x

#5566 [release-3.7] Remove caching of values from Cluster object
  tests/integration-tests/clusters_factory.py
Labels: skip-changelog-update, 3.x

#5567 [Integ-tests] Upload OSU benchmark results to CloudWatch metric
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#5560 [Integ-tests] Upload OSU benchmark results to CloudWatch metric
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#5554 [Performance Test] Add scaling test to validate scale out to 1000 nodes.
  tests/integration-tests/configs/scaling.yaml
  tests/integration-tests/tests/performance_tests/test_scaling.py
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5571 [Integ-tests] Relax intel MPI Allgather base number
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allgather
Labels: skip-changelog-update

#5572 [Integ-tests] Relax intel MPI Allgather base number
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/c5n.18xlarge/intelmpi/osu_allgather
Labels: skip-changelog-update

#5570 Increase gracetime period min limit from 1 to 3
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/schemas/test_schema_validators.py
Labels: skip-changelog-update, 3.x

#5543 Test node scaling for exclusive jobs with near all-or-nothing launch
  tests/integration-tests/tests/common/scaling/overrides.sh
  tests/integration-tests/tests/common/scaling_common.py
  tests/integration-tests/tests/scaling/test_scaling.py
  tests/integration-tests/tests/scaling/test_scaling/test_job_level_scaling/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5579 Upgrade slurm to version 23.02.4
  CHANGELOG.md
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: 3.x

#5582 [Release 3.7] Increase volume size default to address free space issu…
  cli/src/pcluster/constants.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update

#5581 Increase volume size default to address free space issues in Centos 7
  cli/src/pcluster/constants.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update

#5584 Correct wrong error message.
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/schemas/test_schema_validators.py
Labels: skip-changelog-update, 3.x

#5587 [develop] Remove pin of pytest library
  tests/integration-tests/requirements.txt
  tests/integration-tests/tox.ini
Labels: skip-changelog-update

#5588 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog-update

#5585 [Test] Scaling test: check that clustermgtd logs does not contain boo…
  tests/integration-tests/tests/performance_tests/test_scaling.py
Labels: skip-changelog-update, 3.x

#5593 Update additional integ tests that hardcode references to default vol…
  tests/integration-tests/tests/storage/test_ebs.py
  tests/integration-tests/tests/storage/test_raid.py
Labels: skip-changelog-update

#5594 [Release 3.7] Update additional integ tests that hardcode references …
  tests/integration-tests/tests/storage/test_ebs.py
  tests/integration-tests/tests/storage/test_raid.py
Labels: skip-changelog-update

#5578 [integ-test-3.7] Test node scaling for exclusive jobs with near all-or-nothing launch
  tests/integration-tests/tests/common/scaling/overrides.sh
  tests/integration-tests/tests/common/scaling_common.py
  tests/integration-tests/tests/scaling/test_scaling.py
  tests/integration-tests/tests/scaling/test_scaling/test_job_level_scaling/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5597 Add dns tests to schedulers.yaml integration test configuration
  tests/integration-tests/configs/schedulers.yaml
Labels: skip-changelog-update, 3.x

#5600 [develop][Performance Test] Add scaling test to validate scale out to 1000 nodes.
  tests/integration-tests/configs/scaling.yaml
  tests/integration-tests/tests/performance_tests/test_scaling.py
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling/pcluster.config.yaml
Labels: skip-changelog-update

#5603 Update SSH keypair vaildator to include a check for ed25519 keys on Ubuntu 22.04
  cli/src/pcluster/aws/aws_api.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update

#5604 [Release 3.7] Update SSH keypair vaildator to include a check for ed2…
  cli/src/pcluster/aws/aws_api.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update

#5564 Test protected mode in partitions using job-level scaling
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.broken.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.recover.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5601 Restrict access to /tmp/wait_condition_handle.txt
  CHANGELOG.md
  cli/src/pcluster/templates/cluster_stack.py
Labels: 3.x, Environment

#5613 Restrict access to /tmp/wait_condition_handle.txt
  CHANGELOG.md
  cli/src/pcluster/templates/cluster_stack.py
Labels: 3.x

#5616 [release-3.7][Integ-tests] Fix tests in isolated regions
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/tests/create/test_create.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.mem-based-scheduling.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.update-schedulable-memory.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_memory_based_scheduling/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/storage-stack.yaml
Labels: skip-changelog-update

#5599 [develop] Add and test encryption of the LoginNodes root volume
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#5586 [release-3.7] Add and test encryption of the LoginNodes root volume
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#5621 [develop] Add possibility to pass a custom cinc URL during AMI build
  cli/src/pcluster/config/imagebuilder_config.py
  cli/src/pcluster/schemas/imagebuilder_schema.py
  cli/src/pcluster/templates/imagebuilder_stack.py
Labels: skip-changelog-update

#5618 Use wget for failure cases in test_dcv to avoid the change in behavio…
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/dcv/test_dcv.py
Labels: skip-changelog-update

#5617 [Release 3.7] Use wget for failure cases in test_dcv to avoid the cha…
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/dcv/test_dcv.py
Labels: skip-changelog-update

#5626 [OpenFOAM]Add more descriptive log to show performance test results.
  tests/integration-tests/tests/performance_tests/test_openfoam.py
Labels: skip-changelog-update, 3.x

#5625 [develop]Create lifecycle hook the same time as ASG and correct wrong instance IAM policy resource of autoscaling:CompleteLifecycleAction
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#5623 [StarCCM+]Add more descriptive log to show performance test results.
  tests/integration-tests/tests/performance_tests/test_starccm.py
Labels: skip-changelog-update, 3.x

#5612 [release-3.7] Test protected mode in partitions using job-level scaling
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.broken.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.recover.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_protected_mode/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5624 [release-3.7] Define the launch lifecycle hook as an ASG property and fix IAM policy resource for autoscaling:CompleteLifecycleAction
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#5619 [develop] Add AD test for LoginNodes
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration_on_login_nodes/NLB_SimpleAD.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration_on_login_nodes/ad_stack.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration_on_login_nodes/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5630 [File Cache] Rename 'FSx File Cache' to 'File Cache'.
  cli/src/pcluster/aws/fsx.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.batch.head_node_log.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.batch.no_head_node_log.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.slurm.conditional_vol.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/centos7.slurm.full.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/rhel8.slurm.full.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/ubuntu20.slurm.no_dashboard.yaml
  cli/tests/pcluster/templates/test_shared_storage.py
  cli/tests/pcluster/templates/test_shared_storage/test_non_happy_storage/file_cache_config.yaml
  cli/tests/pcluster/templates/test_shared_storage/test_unmanaged_shared_storage_fsx/unmanaged_config.yaml
  cli/tests/pcluster/validators/test_cluster_validators.py
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/resources/file-cache-storage-cfn.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre.py
  tests/integration-tests/tests/storage/test_fsx_lustre/test_fsx_file_cache/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_drain.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/storage-stack.yaml
Labels: skip-changelog-update, 3.x

#5632 [Release 3.7] Revert back to curl for test dcv, add a check for an ex…
  tests/integration-tests/tests/dcv/test_dcv.py
Labels: skip-changelog-update

#5633 Revert back to curl for test dcv, add a check for an exception that g…
  tests/integration-tests/tests/dcv/test_dcv.py
Labels: skip-changelog-update

#5628 [StarCCM+]Corrected the condition for the outcome.
  tests/integration-tests/tests/performance_tests/test_starccm.py
Labels: skip-changelog-update

#5634 Bump version to 3.7.0
  api/infrastructure/parallelcluster-api.yaml
  cli/setup.py
  cli/src/pcluster/constants.py
  cloudformation/custom_resource/cluster-1-click.yaml
  cloudformation/custom_resource/cluster.yaml
Labels: skip-changelog-update

#5637 [performance-test] Make OpenFoam and StarCCM able to use open PG-ODCR
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/pcluster.config.yaml
Labels: skip-changelog-update

#5636 Renaming the test_fsx_file_cache folder which contains the test files
  tests/integration-tests/tests/storage/test_fsx_lustre/test_file_cache/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_file_cache/s3_test_file
Labels: skip-changelog-update, 3.x

#5641 [release-3.7] Add AD test for LoginNodes
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration_on_login_nodes/NLB_SimpleAD.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration_on_login_nodes/ad_stack.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration_on_login_nodes/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5627 [OpenFOAM]Corrected the condition for the outcome.
  tests/integration-tests/tests/performance_tests/test_openfoam.py
Labels: skip-changelog-update

#5638 [Integ-test] Avoid setting up integration tests networking in local zone
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update

#5639 [develop]Test connectivity and basic Slurm interactions with a LN Pool in a public subnet
  tests/iam_policies/user-role.cfn.yaml
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/pcluster.update.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_pmix/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5646 [release-3.7]Test connectivity and basic Slurm interactions with a LN Pool in a public subnet
  tests/iam_policies/user-role.cfn.yaml
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/pcluster.update.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_pmix/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5644 [develop] Handle login nodes bootstrap failures
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/utils.py
Labels: skip-changelog-update, 3.x

#5649 [release-3.7] Revert "Handle login nodes bootstrap failures (#5647)"
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/utils.py
Labels: skip-changelog-update, 3.x

#5650 [develop] Revert "Handle login nodes bootstrap failures (#5644)"
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/utils.py
Labels: skip-changelog-update, 3.x

#5652 [develop] Add change log entry for login nodes.
  CHANGELOG.md
Labels: 3.x

#5654 [release-3.7] Reduce wait-time while checking mpi jobs
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5655 [develop] Reduce wait-time while checking mpi jobs
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5656 [release-3.7] Reduce Login nodes gracetime period in test_ebs_existing
  tests/integration-tests/tests/storage/test_ebs.py
  tests/integration-tests/tests/storage/test_ebs/test_ebs_existing/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5657 [develop] Reduce Login nodes gracetime period in test_ebs_existing
  tests/integration-tests/tests/storage/test_ebs.py
  tests/integration-tests/tests/storage/test_ebs/test_ebs_existing/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5658 [performance-test] Make OpenFoam and StarCCM able to use open PG-ODCR
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/pcluster.config.yaml
Labels: skip-changelog-update

#5660 [Integ-test] Avoid setting up integration tests networking in local zone
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update

#5663 [release-3.7] Disables test of slurm from login nodes in private network
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#5665 [release-3.7] [integ-tests] Use a fixed time MPI job to test job cancellation of MPI processes
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/mpi_job.sh
Labels: skip-changelog-update, 3.x

#5671 [develop] [integ-tests] Use a fixed time MPI job to test job cancellation of MPI processes
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/mpi_job.sh
Labels: skip-changelog-update, 3.x

#5668 [File Cache] Rename 'FSx File Cache' to 'File Cache'.
  CHANGELOG.md
  cli/src/pcluster/aws/fsx.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.batch.head_node_log.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.batch.no_head_node_log.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/alinux2.slurm.conditional_vol.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/centos7.slurm.full.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/rhel8.slurm.full.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/ubuntu20.slurm.no_dashboard.yaml
  cli/tests/pcluster/templates/test_shared_storage.py
  cli/tests/pcluster/templates/test_shared_storage/test_non_happy_storage/file_cache_config.yaml
  cli/tests/pcluster/templates/test_shared_storage/test_unmanaged_shared_storage_fsx/unmanaged_config.yaml
  cli/tests/pcluster/validators/test_cluster_validators.py
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/resources/file-cache-storage-cfn.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre.py
  tests/integration-tests/tests/storage/test_fsx_lustre/test_file_cache/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_drain.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/storage-stack.yaml
Labels: skip-changelog-update, 3.x

#5677 [Test] Add --force-elastic-ip Integ Tests option for multi-nic instances
  tests/integration-tests/configs/gpu.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/intelmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/intelmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/intelmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/intelmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/intelmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/intelmpi/osu_latency
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/openmpi/osu_allgather
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/openmpi/osu_allreduce
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/openmpi/osu_alltoall
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/openmpi/osu_bcast
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/openmpi/osu_bibw
  tests/integration-tests/tests/efa/test_efa/test_efa/osu_benchmarks/results/p5.48xlarge/openmpi/osu_latency
  tests/integration-tests/tests/efa/test_fabric/test_fabric/run-fabtests.sh
Labels: skip-changelog-update, 3.x
