Repository aws/aws-parallelcluster, pull requests merged in 2023-06, with the labels that each got.

#5370 [Isolated Regions] Make test_log_rotation executable in isolated regions
  tests/integration-tests/tests/log_rotation/test_log_rotation.py
  tests/integration-tests/tests/log_rotation/test_log_rotation/test_log_rotation/pcluster.config.yaml
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x, Environment

#5371 [integ-tests] Fix test_build_image intermittent failures
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#5364 [3.x] Adding default mount options and name for fsx
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update, 3.x

#5373 Move test_dynamic_file_systems_update to ap-southeast-2
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update, 3.x

#5374 [Isolated Regions] Make 1-click template defining the SLURM Database infrastructure deployable to US isolated regions.
  cloudformation/database/serverless-database.yaml
Labels: skip-changelog-update, 3.x, Environment

#5377 [integ-tests] Fix test_build_image intermittent failures
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#5376 [integ-tests] Fix test_build_image intermittent failures
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#5368 add a cluster bootstrap failure and a test case
  cli/src/pcluster/models/cluster_resources.py
  cli/tests/pcluster/api/controllers/test_cluster_operations_controller.py
Labels: skip-changelog-update, 3.x

#5385 Do not check RAID File System at boot
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#5389 Fix validation of custom nodes, nodesets and partitions in CustomSlurmSettings
  cli/src/pcluster/validators/slurm_settings_validator.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#5393 Fix validation of custom nodes, nodesets and partitions in CustomSlurmSettings
  cli/src/pcluster/validators/slurm_settings_validator.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update, 3.x

#5396 [Isolated Regions][Test] Add to test config for isolated regions: test_slurm_custom_config_parameters
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x, Environment

#5391 Fix cluster creation failure when using Custom Resource
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/validators/networking_validators.py
  cli/tests/pcluster/validators/test_networking_validators.py
Labels: 3.x

#5400 [Isolated Regions][Test] Add integ test covering custom resource to the tests executed in US iso regions.
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x, Environment

#5403 Remove recipes tests
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update

#5405 Call entrypoints recipes from aws-parallelcluster-entrypoints cookbook
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update

#5412 [develop] Always call parameters by name while submitting a job for testing
  tests/integration-tests/tests/common/schedulers_common.py
Labels: skip-changelog-update, 3.x

#5413 [Documentation] Fix CHANGELOG for version 3.6.1.
  CHANGELOG.md
Labels: 3.x

#5355 Add startup time metrics for compute node
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/queues_stack.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
Labels: skip-changelog-update, 3.x

#5421 [Isolated Regions] [Policies] Omit AWSXRayDaemonWriteAccess policy of ParallelClusterLambdaRole in US isolated regions as the policy is not supported in these regions.
  cloudformation/policies/parallelcluster-policies.yaml
Labels: skip-changelog-update, 3.x, Environment

#5395 Add queue-level JobExclusiveAllocation cluster configuration parameter
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/slurm_settings_validator.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
Labels: skip-changelog-update, 3.x

#5401 Add a metric and an alarm for the cluster in protected mode error
  cli/src/pcluster/constants.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
Labels: skip-changelog-update, 3.x

#5425 Pin pytest version to 7.3
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update

#5426 [Test] Pin pytest version to 7.3
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update, 3.x

#5384 Setup AWS Infrastructure for login nodes using CDK
  cli/src/pcluster/aws/ec2.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/aws/test_ec2.py
  cli/tests/pcluster/config/dummy_cluster_config.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/schemas/test_schema_validators.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full.all_resources.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_traffic_management_resources_values_properties/test-login-nodes-stack.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_2.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_validators_are_called_with_correct_argument/slurm.yaml
Labels: skip-changelog-update, 3.x

#5428 [integ-tests-3.6.0] Pin pytest version to 7.3
  tests/integration-tests/requirements.txt
Labels: skip-changelog-update

#5432 [develop] Add proxy attribute to LoginNodes Networking Schema
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full.all_resources.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
Labels: skip-changelog-update, 3.x

#5433 [Test] Replace t2.large with m5.large in 'test_fast_capacity_failover'
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5427 Add integ-testing option to force usage of run-instance API over Create-fleet api
  tests/integration-tests/configs/new_instance_types.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/framework/tests_configuration/config_renderer.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/networking/test_multi_cidr/test_multi_cidr/pcluster.config.yaml
Labels: skip-changelog-update

#5430 Revisit list of tests required to validate a new OS
  tests/integration-tests/configs/new_os.yaml
Labels: skip-changelog-update

#5438 Remove unwanted byos (Bring your own scheduler) yaml
  tests/integration-tests/configs/byos.yaml
Labels: skip-changelog-update

#5439 Add ubuntu2204 to the AMI owner dict and deep learning AMI dict
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#5441 [Test] Remove hard wired custom AMI from 'test_fast_capacity_failover'.
  tests/integration-tests/tests/schedulers/test_slurm/test_fast_capacity_failover/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#5422 [Integ-test] Add `instances` dimension to custom_resource tests in isolated_regions.yaml
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update
