Repository aws/aws-parallelcluster, pull requests merged in 2024-08, with the labels that each got.

#6374 Fix Cfn-lint W1028
  cloudformation/networking/public-private.cfn.json
  cloudformation/networking/public.cfn.json
Labels: skip-changelog-update

#6375 Fix Cfn-lint W1028
  cloudformation/networking/public-private.cfn.json
  cloudformation/networking/public.cfn.json
Labels: skip-changelog-update

#6379 [Release-3.10] Fix retrieve_supported_regions to get the correct S3 Url
  cli/src/pcluster/utils.py
Labels: skip-changelog-update, 3.x

#6380 [Develop] Fix retrieve_supported_regions to get the correct S3 Url
  CHANGELOG.md
  cli/src/pcluster/utils.py
Labels: 3.x

#6383 Add dummy config for pipeline testing
  tests/integration-tests/configs/dummy.yaml
Labels: skip-changelog-update

#6373 [Develop] Fix cluster deletion failure when placement groups are enabled
  CHANGELOG.md
  cli/src/pcluster/resources/custom_resources/custom_resources_code/cleanup_resources.py
Labels: 3.x

#6385 Add the cluster stack name and cw log group name to the metadata table for quick identification
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_utils.py
  tests/integration-tests/framework/metadata_table_manager.py
  tests/integration-tests/requirements.txt
  tests/integration-tests/tests/dummy/test_dummy.py
  tests/integration-tests/tests/dummy/test_dummy/test_dummy_cluster/pcluster.config.yaml
Labels: skip-changelog-update

#6387 Add CreateServiceLinkedRole action to LoginNode policy
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update

#6392 [ADC] Add rhel8 owner account ids for ADC
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#6395 [LoginNodes] Update API to support multiple login node pools
  api/client/src/docs/ClusterInstance.md
  api/client/src/docs/DescribeClusterResponseContent.md
  api/client/src/docs/LoginNodesPool.md
  api/client/src/pcluster_client/model/cluster_instance.py
  api/client/src/pcluster_client/model/describe_cluster_response_content.py
  api/client/src/pcluster_client/model/login_nodes_pool.py
  api/spec/openapi/ParallelCluster.openapi.yaml
  api/spec/smithy/model/operations/DescribeCluster.smithy
  api/spec/smithy/model/operations/DescribeClusterInstances.smithy
  api/spec/smithy/model/types/LoginNodesPool.smithy
  cli/src/pcluster/api/controllers/cluster_instances_controller.py
  cli/src/pcluster/api/controllers/cluster_operations_controller.py
  cli/src/pcluster/api/models/cluster_instance.py
  cli/src/pcluster/api/models/describe_cluster_response_content.py
  cli/src/pcluster/api/models/login_nodes_pool.py
  cli/src/pcluster/api/openapi/openapi.yaml
  cli/src/pcluster/aws/aws_resources.py
  cli/tests/pcluster/api/controllers/test_cluster_operations_controller.py
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
  tests/integration-tests/tests/cli_commands/test_cli_commands/test_slurm_cli_commands/pcluster.config.with.warnings.yaml
  tests/integration-tests/tests/cli_commands/test_cli_commands/test_slurm_cli_commands/pcluster.config.yaml
Labels: skip-changelog-update

#6400 [integ-test] Fix build_image_custom_resource fixture
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#6399 [integ-test] Fix build_image_custom_resource fixture
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#6404 Update integration test utils for login nodes
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#6406 Increase default PCLUSTER_RESERVED_VOLUME_SIZE to 32
  cli/src/pcluster/imagebuilder_utils.py
  cli/tests/pcluster/templates/test_imagebuilder_stack.py
Labels: skip-changelog-update

#6409 Change login node OnNodeUpdated update policy to supported
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update

#6410 [integ-tests] Remove Rocky from daily integration tests
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update

#6413 [integ-tests] Fix test_build_image_custom_components failure
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#6411 Use right permission to operate on log files
  tests/integration-tests/tests/basic/log_rotation_utils.py
Labels: skip-changelog-update

#6414 Pinning to Minitar 0.9 as its available in S3
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
Labels: skip-changelog-update, 3.x

#6418 [Develop] Introduce pagnator in describe_images boto3 calls
  CHANGELOG.md
  cli/src/pcluster/aws/ec2.py
Labels: 3.x

#6419 Update retiring instances in integ tests
  tests/integration-tests/configs/.gitignore
  tests/integration-tests/configs/new_os.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_from_login_nodes_in_private_network/pcluster.config.yaml
Labels: skip-changelog-update
