Repository aws/aws-parallelcluster, pull requests merged in 2024-12, with the labels that each got.

#6502 ec2 image builder updateos document insufficient arguments to yum
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#6584 [integ-tests] Fix test_essential_features test
  tests/integration-tests/tests/basic/log_rotation_utils.py
  tests/integration-tests/tests/basic/test_essential_features.py
Labels: skip-changelog-update

#6586 [Test] Removing color from output of ip command
  tests/integration-tests/tests/multiple_nics/test_multiple_nics.py
Labels: skip-changelog-update, 3.x

#6588 [Test] Fix test 'test_update_instance_list' by making use of the expected instance types.
  tests/integration-tests/tests/update/test_update/test_update_instance_list/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_instance_list/pcluster.config.yaml
Labels: skip-changelog-update, 3.x, Test

#6589 [Test] Fix test 'test_update_instance_list' by making use of the expected instance types.
  tests/integration-tests/tests/update/test_update/test_update_instance_list/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_instance_list/pcluster.config.yaml
Labels: skip-changelog-update, 3.x, Test

#6593 [Test] Add another instance type for handling ICE
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6595 Add logging for test_image_tag_and_volume
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#6596 [Test]Using Rocky8 AMI for testing 3.11.1
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update, 3.x

#6597 [Test] Update AZ in which c6in is available
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6598 Only have EFS shared storage type if the scheduler is slurm
  tests/integration-tests/tests/storage/test_efs/test_multiple_efs/pcluster.config.yaml
Labels: skip-changelog-update

#6599 [Test] Create Directory /etc/enroot for pyxis test
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/compute_node_start.sh
Labels: skip-changelog-update, 3.x

#6602 [changelog] Move the export logs changelog line to ENHANCEMENTS
  CHANGELOG.md
Labels: 3.x

#6603 [changelog] Move the export logs changelog line to ENHANCEMENTS
  CHANGELOG.md
Labels: 3.x

#6601 [Test] Create Directory /etc/enroot for pyxis test
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/compute_node_start.sh
Labels: skip-changelog-update, 3.x

#6592 [Test] Fix test 'test_update_slurm' adapting the constraint in the sbatch command to the flexible instance types used in the config
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x, Test

#6610 [Test] Fix test 'test_update_slurm' adapting the constraint in the sbatch command to the flexible instance types used in the config
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x, Test

#6613 Update Attribution doc for 3.12.0
  THIRD-PARTY-LICENSES.txt
  util/create-attribution-doc.sh
Labels: skip-changelog-update, 3.x

#6611 [Test] Skip Nvidia driver installation if Deep Learning AMI is used
  tests/integration-tests/tests/createami/test_createami.py
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: skip-changelog-update

#6612 Wait for update to complete in test_api
  tests/integration-tests/tests/pcluster_api/test_api.py
Labels: skip-changelog-update

#6618 Wait for update to complete in test_api
  tests/integration-tests/tests/pcluster_api/test_api.py
Labels: skip-changelog-update

#6614 Update Attribution doc for 3.12.0
  THIRD-PARTY-LICENSES.txt
  util/create-attribution-doc.sh
Labels: skip-changelog-update, 3.x

#6626 [unit-tests] Fix unit tests on Python 3.12
  cli/tests/pcluster/cli/test_describe_cluster_instances.py
  cli/tests/pcluster/cli/test_list_images.py
Labels: skip-changelog-update

#6628 Lock kernel minor version during image build
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update
