Repository aws/aws-parallelcluster, pull requests merged in 2024-06, with the labels that each got.

#6270 Add git commit refs to test metadata table
  tests/integration-tests/conftest_utils.py
Labels: skip-changelog-update

#6267 Add the global_build_number parameter to the test runs
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_runtest_hooks.py
  tests/integration-tests/conftest_utils.py
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update

#6271 Decouple region support from CLI release
  cli/src/pcluster/api/controllers/common.py
  cli/src/pcluster/cli/commands/configure/utils.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/supported-regions
  cli/src/pcluster/utils.py
  cli/src/pcluster/validators/cluster_validators.py
Labels: skip-changelog-update, skip-security-exclusions-check

#6276 Use a single extend to add the global build number, extend expects a …
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update

#6253 Adding Support to Suppress Validators in Custom Resources
  CHANGELOG.md
  cli/src/pcluster/lib/lib.py
  tests/integration-tests/tests/custom_resource/conftest.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource/test_cluster_create/pcluster.config.yaml
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource/test_cluster_update_invalid/pcluster.config.invalidprofile.yaml
Labels: skip-changelog-update, 3.x

#6266 Removing usage of `/etc/profile.d/pcluster.sh`
  CHANGELOG.md
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/src/pcluster/templates/queues_stack.py
  cloudformation/external-slurmdbd/external-slurmdbd.json
  cloudformation/external-slurmdbd/resources/user_data.sh
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#6283 [Docs] Add changelog entry for version 3.9.3.
  CHANGELOG.md
Labels: docs, 3.x

#6285 Set default to None for metadata table params that don't have values
  tests/integration-tests/framework/metadata_table_manager.py
Labels: skip-changelog-update

#6286 [Docs] Add changelog entry for 3.9.3: cloud_dns.
  CHANGELOG.md
Labels: docs, 3.x

#6288 [integ-tests] fix test_overwrite_sg
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.update.yaml
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.yaml
Labels: skip-changelog-update

#6291 [integ-test] Fix test_dynamic_file_systems_update_data_loss
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x, Test

#6292 Adding OSU Benchmarks for AL2023
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/intelmpi/osu_allgather
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/intelmpi/osu_allreduce
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/intelmpi/osu_alltoall
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/intelmpi/osu_bcast
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/intelmpi/osu_bibw
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/intelmpi/osu_latency
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/openmpi/osu_allgather
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/openmpi/osu_allreduce
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/openmpi/osu_alltoall
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/openmpi/osu_bcast
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/openmpi/osu_bibw
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/osu_benchmarks/results/alinux2023/c5n.18xlarge/openmpi/osu_latency
Labels: skip-changelog-update, 3.x

#6295 [AL2023] Adding Al2023 for daily and released Integration tests
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update, 3.x

#6299 [Slurmdbd] Make template compatible with Ubuntu
  cloudformation/external-slurmdbd/external-slurmdbd.json
  cloudformation/external-slurmdbd/resources/user_data.sh
Labels: skip-changelog-update

#6301 Install packages as the user instead of in system locations
  tests/integration-tests/tests/efa/test_efa/test_efa/install-fabtests.sh
Labels: skip-changelog-update

#6303 Use string defaults even for numbers in the metadata_table_manager
  tests/integration-tests/framework/metadata_table_manager.py
Labels: skip-changelog-update

#6300 [Test] Fix test_starccm so that it can be executed on AL2023.
  tests/integration-tests/configs/starccm.yaml
  tests/integration-tests/tests/performance_tests/test_starccm.py
Labels: skip-changelog-update, 3.x, Test

#6306 [Develop] Fix test_proxy integ test
  tests/integration-tests/tests/proxy/test_proxy.py
  tests/integration-tests/tests/proxy/test_proxy/test_proxy/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6312 [Linters] Pin setuptools to <70.0.0 as in cli/setup.py to prevent false positive violations on packaging module.
  awsbatch-cli/tox.ini
  cli/tox.ini
Labels: skip-changelog-update, 3.x, Code Style

#6311 [Validators] Add validator to prevent the use of Placement Groups with Capacity Blocks.
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: enhancement, 3.x

#6310 [PCAPI] Add missing CFN states to PCAPI
  CHANGELOG.md
  api/client/src/docs/CloudFormationStackStatus.md
  api/client/src/pcluster_client/model/cloud_formation_stack_status.py
  api/spec/openapi/ParallelCluster.openapi.yaml
  api/spec/smithy/model/types/Common.smithy
  cli/src/pcluster/api/openapi/openapi.yaml
Labels: bug, 3.x

#6314 Bump awsbatch-cli version to 1.4.0
  awsbatch-cli/CHANGELOG.md
  awsbatch-cli/setup.py
Labels: skip-changelog-update
