Repository aws/aws-parallelcluster, pull requests merged in 2024-01, with the labels that each got.

#5713 [Disable Sudo] Add Config Option to disable Sudo access for default users in supported OSSes
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/src/pcluster/templates/queues_stack.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_compute_launch_template_properties/cluster-using-flexible-instance-types.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_compute_launch_template_properties/cluster-using-single-instance-type.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack-with-custom-tags.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack-without-ssh.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack.yaml
  cli/tests/pcluster/validators/test_cluster_validators.py
  tests/integration-tests/configs/common/common.yaml
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/create/test_create.py
  tests/integration-tests/tests/create/test_create/test_create_disable_sudo_access_for_default_user/pcluster.config.yaml
Labels: 3.x

#5989 [Test][Isolated Regions] Make test_efa use c5n.9xl rather than c5n.18xl in isolated regions
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5988 [Test][Isolated Regions] Make test_efa use c5n.9xl rather than c5n.18xl in isolated regions
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5987 [Test][Isolated Regions] Make test_efa use c5n.9xl rather than c5n.18xl in isolated regions.
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#5990 Add option to use simpleAD in the ad-integration template
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update

#5993 [integ-tests-3.8.0] Increase job duration in memory-based-scheduling test
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5992 [release-3.8] Increase job duration in memory-based-scheduling test
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5991 [develop] Increase job duration in memory-based-scheduling test
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#5994 Add support for multiple users in ad template
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update

#5997 [Disable Sudo]Register Validator only if the DisableSudoAccessForDefaultUser config option is used
  cli/src/pcluster/config/cluster_config.py
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_2.yaml
Labels: skip-changelog-update, 3.x

#5996 Change shellcheck severity level to warning
  .github/workflows/ci.yml
  api/gradlew
  api/infrastructure/deploy-api.sh
  api/spec/spec_overrides.sh
  cli/src/pcluster/resources/batch/docker/build-docker-images.sh
  cli/src/pcluster/resources/batch/docker/scripts/entrypoint.sh
  cli/src/pcluster/resources/batch/docker/upload-docker-images.sh
  util/bump-version.sh
  util/create-attribution-doc.sh
  util/upload-cli.sh
Labels: skip-changelog-update

#6000 Disable test_custom_image to stop reoccuring integ test failure
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#5926 Add support for ExternalSlurmdbd in SlurmSettings
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/validators/slurm_settings_validator.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/validators/test_cluster_validators.py
  cloudformation/external-slurmdbd/external_slurmdbd/external_slurmdbd_stack.py
Labels: skip-changelog-update, 3.x

#6008 [develop][Integ-tests] Fix CloudWatch integration tests
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging/test_cloudwatch_logging/cw_agent_debug.sh
Labels: skip-changelog-update

#6004 [Disable Sudo] Supporting DisableSudoAccessForDefaultUser config Option using Cookbook
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/src/pcluster/templates/queues_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_compute_launch_template_properties/cluster-using-flexible-instance-types.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_compute_launch_template_properties/cluster-using-single-instance-type.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_head_node_dna_json/head_node_default.dna.json
  cli/tests/pcluster/templates/test_cluster_stack/test_head_node_dna_json/slurm-imds-secured-true.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_node_dna_json/login-basic-config.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack-with-custom-tags.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack-without-ssh.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_login_nodes_launch_template_properties/test-login-nodes-stack.yaml
  tests/integration-tests/tests/create/test_create/test_create_disable_sudo_access_for_default_user/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6010 [external_slurmdbd] Allow traffic from external slurmdbd to slurmctld's
  cloudformation/external-slurmdbd/external_slurmdbd/external_slurmdbd_stack.py
Labels: skip-changelog-update, 3.x

#6011 Remove rocky8 OS from released integ tests
  tests/integration-tests/configs/common/common.yaml
Labels: skip-changelog-update

#6006 Add validator to fail when a user is not using a custom ami and is using an instance_type that is not supported by openRM
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/models/test_imagebuilder.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: 3.x

#6016 [Disable Sudo] Support Update of DisableSudoAccessForDefaultUser Config Option
  cli/src/pcluster/schemas/cluster_schema.py
  tests/integration-tests/tests/create/test_create.py
  tests/integration-tests/tests/create/test_create/test_create_disable_sudo_access_for_default_user/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6017 [Disable Sudo] Update the Policy for DisableSudoAccessForDefaultUser
  cli/src/pcluster/schemas/cluster_schema.py
Labels: skip-changelog-update, 3.x

#6019 [develop] Fix assertion on update resize for TERMINATE case
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#6023 [DFSM] Load pcluster envars in compute node user data to resolve cfn …
  cli/src/pcluster/resources/compute_node/user_data.sh
Labels: bug, skip-changelog-update, 3.x

#6024 [DFSM][Test] Add check in integ 'test_update_slurm' to verify that compute nodes save the expected cluster config version on DynamoDB.
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#6025 [develop] Fix InstanceTypeBaseAMICompatibleValidator to properly handle custom AMIs without description
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update

#6009 Add resource leak integration test
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/performance_tests/test_starccm.py
Labels: skip-changelog-update

#6034 Change test_slurm gpu instance type to g4dn.2xlarge
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#6032 Use ad_integration.yaml template in ad_integration test
  cloudformation/ad/ad-integration.yaml
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update2.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
Labels: skip-changelog-update

#6039 [develop] Upgrade to Slurm 23.11.3
  CHANGELOG.md
Labels: 3.x

#6035 Unset proxies in test_runner
  cli/tests/pcluster/models/test_cluster_resources.py
  cli/tests/pcluster/models/test_common.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/performance_tests/plotting/performance_tests_plots.py
  tests/integration-tests/tests/storage/snapshots_factory.py
Labels: skip-changelog-update

#6036 Unset proxies in test runner
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update

#6037 chore: a more polite closed issue message
  .github/workflows/closed-issue-message.yml
Labels: skip-changelog-update

#6046 Fix ad integ test failure
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update

#6045 [Integ Tests] Merge cfn-init tests and rename to test-essential-features
  tests/integration-tests/README.md
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/configs/new_os.yaml
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/tests/basic/__init__.py
  tests/integration-tests/tests/basic/test_essential_features.py
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/failing_post_install.sh
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/pcluster.config.yaml
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/post_install.sh
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/pre_install.sh
  tests/integration-tests/tests/cfn-init/test_cfn_init/test_replace_compute_on_failure/pcluster.config.yaml
  tests/integration-tests/tests/common/assertions.py
Labels: skip-changelog-update

#6052 [Tests] Add new configuration file to be used during release process
  tests/integration-tests/configs/release-process.yaml
Labels: skip-changelog-update

#6054 [Test] Add permission logs:ListTagsForResource to the role assumed by…
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x

#6057 Add outputs to ExternalSlurmDbd Stack
  cloudformation/external-slurmdbd/external_slurmdbd/external_slurmdbd_stack.py
Labels: skip-changelog-update, 3.x

#6056 [DFSM][Test] In test_update_slurm, add retry on the assertion to verify cluster config version in DDB during rollback.
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#6051 [integ-tests-3.8.0] [Tests] Remove rocky8 tests from released tests
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update

#6059 [DFSM] Remove redundant __init__ file from custom_resources folder.
  cli/src/pcluster/resources/custom_resources/__init__.py
Labels: skip-changelog-update, 3.x

#6066 [develop] Fix DeviceIndex value to 1 on secondary interfaces for compute nodes
  cli/src/pcluster/templates/queues_stack.py
Labels: skip-changelog-update
