Repository aws/aws-parallelcluster, pull requests merged in 2024-10, with the labels that each got.

#6457 [Github workflow] Fix Slurmdbd tempate Github check by pinning typeguard version
  .github/workflows/ci.yml
Labels: skip-changelog-update

#6458 [Github workflow] Fix Slurmdbd tempate Github check by pinning typeguard version
  .github/workflows/ci.yml
Labels: skip-changelog-update

#6460 Reapply "Pin jsonschema for Lambda Layer to version 4.17.3"
  tests/integration-tests/conftest_resource_bucket.py
Labels: skip-changelog-update

#6456 Revert "Pin setuptools version to be less than 70.0.0"
  awsbatch-cli/setup.py
  cli/setup.py
  cloudformation/external-slurmdbd/requirements.txt
Labels: skip-changelog-update

#6463 [Documentation] Add changelog entry for version 3.11.1.
  CHANGELOG.md
Labels: docs, 3.x

#6464 [Documentation] Add changelog entry for version 3.11.1.
  CHANGELOG.md
Labels: docs, 3.x

#6466 [Documentation] Fix changelog entries for version 3.11.1.
  CHANGELOG.md
Labels: docs, 3.x

#6468 [Documentation] Fix changelog entries for version 3.11.1.
  CHANGELOG.md
Labels: docs, 3.x

#6467 [Documentation] Fix changelog entries for version 3.11.1.
  CHANGELOG.md
Labels: docs, 3.x

#6469 Revert "Fix code linter error" causing job submission failure on AWS Batch
  cli/src/pcluster/resources/batch/docker/alinux2/Dockerfile
  cli/src/pcluster/resources/batch/docker/alinux2023/Dockerfile
Labels: bug, skip-changelog-update, 3.x

#6472 [Docs] Add changelog entry for 3.11.1 about libjwt.
  CHANGELOG.md
Labels: docs, 3.x

#6471 [Docs] Add changelog entry for 3.11.1 about libjwt.
  CHANGELOG.md
Labels: docs, 3.x

#6475 [Release-3.11] Add pyxis integration test
  tests/integration-tests/README.md
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/pyxis/test_pyxis.py
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/compute_node_start.sh
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/head_node_configure.sh
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6481 [develop] Fix proxy.yaml cfn-lint check error
  cloudformation/proxy/proxy.yaml
Labels: skip-changelog-update, 3.x

#6476 [develop] Add pyxis integration test
  tests/integration-tests/README.md
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/pyxis/test_pyxis.py
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/compute_node_start.sh
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/head_node_configure.sh
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6480 [integ-test] Remove old generation of instance types
  tests/integration-tests/README.md
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/new_os.yaml
  tests/integration-tests/conftest_networking.py
  tests/integration-tests/tests/schedulers/test_awsbatch/test_awsbatch/pcluster.config.yaml
Labels: skip-changelog-update

#6484 [integ-test] Remove test_create_wrong_pcluster_version from isolated regions
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update

#6486 Move reboot step to be before installing kernel package during OS update
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#6490 [integ-test-framework] Retrieve private Rocky AMIs according to the architecture of instance
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#6491 [integ-test-framework] fix typo in develop.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#6498 [AWSBatch] Remove offending specification of USER in front of ENTRYPOINT + ignore not unseful semgrep rules
  cli/src/pcluster/resources/batch/docker/alinux2/Dockerfile
  cli/src/pcluster/resources/batch/docker/alinux2023/Dockerfile
Labels: skip-changelog-update, 3.x, awsbatch, skip-security-exclusions-check, Security

#6494 [1-click] In the 1-click template `ad_integration.yaml`, add retry for domain join.
  cloudformation/ad/ad-integration.yaml
Labels: enhancement, skip-changelog-update, 3.x

#6495 [1-click] In the 1-click template ad_integration.yaml, add retry for domain join
  cloudformation/ad/ad-integration.yaml
Labels: enhancement, skip-changelog-update, 3.x

#6493 [Test] Fix test_essential_features by using the correct partition in IAM policy ARNs.
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/pcluster.config.yaml
Labels: bug, skip-changelog-update, 3.x, Test

#6492 [Test] Fix test_essential_features by using the correct partition in IAM policy ARNs.
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/pcluster.config.yaml
Labels: bug, skip-changelog-update, 3.x, Test

#6504 [integ-tests] Remove test_create_wrong_pcluster_version
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/tests/create/test_create.py
Labels: skip-changelog-update

#6506 [integ-tests] Remove test_create_wrong_pcluster_version
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/tests/create/test_create.py
Labels: skip-changelog-update

#6508 [integ-test] Add instances to some tests in test definition
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#6509 [integ-tests] Fix sporadic API test failures by adding sleep at the end of the server creation
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#6511 [integ-tests] Fix sporadic API test failures by adding sleep at the end of the server creation
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#6512 [integ-tests] Fix sporadic API test failures by adding sleep at the end of the server creation
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#6514 [Test] In AD 1-click template, add a debug log lines to make it easier to troubleshoot realm joining issues.
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update, 3.x, Test

#6516 [integ-test] Fix build-image test failures
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/createami/test_createami.py
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: skip-changelog-update

#6515 [integ-test] Fix build-image test failures
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/createami/test_createami.py
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: skip-changelog-update

#6517 [integ-test-framework] Ensure xdist fixture cleans up even when test crashes
  tests/integration-tests/framework/fixture_utils.py
Labels: skip-changelog-update

#6519 [Test] In AD 1-click template, add verbosity to the realm command to make it easier to troubleshoot failures
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update, 3.x, Environment

#6521 [Test] Ad integ test, add logs to make it easier to troubleshoot failures
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update, 3.x, Test

#6522 [integ-test] Add instances to performance tests
  tests/integration-tests/configs/startup_time_performance.yaml
Labels: skip-changelog-update, 3.x
