Repository aws/aws-parallelcluster, pull requests merged in 2024-07, with the labels that each got.

#6325 [integ-tests] Change the wrong version of test_build_image_wrong_pcluster_version to 3.9.3
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#6316 [scaling test] Pick availability zone with large capacity
  tests/integration-tests/configs/scaling_stress_test.yaml
Labels: skip-changelog-update

#6330 [BuildImage] Fix AWS URL suffix to retrieve gems.tgz from S3 from ParallelCluster component.
  CHANGELOG.md
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
Labels: bug, 3.x

#6333 [BuildImage] Fix AWS URL suffix to retrieve gems.tgz from S3 from ParallelCluster component.
  CHANGELOG.md
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
Labels: bug, 3.x

#6332 [Test] Execute build-image tests in China.
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update, 3.x, Test

#6335 [Test] Execute build-image tests in China.
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update, 3.x, Test

#6308 [Develop] Run 8 and 16 node performance tests in parallel
  tests/integration-tests/tests/performance_tests/test_openfoam.py
  tests/integration-tests/tests/performance_tests/test_starccm.py
Labels: skip-changelog-update, 3.x

#6336 [Develop] Improve pref tests logging info and group duplicate codes to common.py
  tests/integration-tests/tests/performance_tests/common.py
  tests/integration-tests/tests/performance_tests/test_openfoam.py
  tests/integration-tests/tests/performance_tests/test_starccm.py
Labels: skip-changelog-update, 3.x

#6324 [Validators] Make EfaPlacementGroupValidator not suggest to set a Placement Group when Capacity Blocks are used.
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: enhancement, 3.x

#6343 Fix code linter for AWSBatch CLI code
  awsbatch-cli/src/awsbatch/awsbhosts.py
  awsbatch-cli/src/awsbatch/awsbqueues.py
Labels: skip-changelog-update

#6340 Adding Describe ELB and AutoScaling Group policies
  cloudformation/policies/parallelcluster-policies.yaml
Labels: skip-changelog-update, 3.x

#6344 [integ-tests] Fix test_create_wrong_pcluster_version
  tests/integration-tests/tests/create/test_create.py
Labels: skip-changelog-update

#6346 [integ-tests] Update develop.yaml and isolated_regions.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update

#6347 Move LT bootstrap log under /dev/ttyS0 instead of /dev/console
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/login_node/user_data.sh
Labels: skip-changelog-update

#6349 [integ-tests] Update develop.yaml and isolated_regions.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update

#6351 Remove ParallelCluster API docker logic
  .github/workflows/ci.yml
  api/docker/awslambda/Dockerfile
  api/docker/awslambda/buildspec.yml
  api/docker/awslambda/docker-build.sh
Labels: skip-changelog-update

#6352 Create a table in each partition's reporting region, instead of just us-east-1
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_utils.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#6354 [integ-test] Skip fabtest in us-iso regions
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update

#6356 [integ-tests] Fix test_create_wrong_pcluster_version
  tests/integration-tests/tests/create/test_create.py
Labels: skip-changelog-update, 3.x, Test

#6365 [Develop] Add support for CGK region
  CHANGELOG.md
  cli/src/pcluster/resources/supported-regions
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/develop.yaml
Labels: 3.x
