Repository aws/aws-parallelcluster, pull requests merged in 2024-04, with the labels that each got.

#6182 Store POSIX timestamps instead of datetime objects to support seriali…
  tests/integration-tests/conftest_utils.py
Labels: skip-changelog-update

#6183 Only use the set of dimensions needed for the generated report
  tests/integration-tests/reports_generator.py
Labels: skip-changelog-update

#6186 Fix bug to allow alarms to be disabled when cw dashboard is enabled
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/centos7.slurm.full.yaml
Labels: skip-changelog-update

#6188 [Test] Reduce test_monitoring to only running one test in develop
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/tests/monitoring/test_monitoring.py
Labels: skip-changelog-update

#6184 Merge test_slurm integ tests
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/configs/new_instance_types.yaml
  tests/integration-tests/configs/new_os.yaml
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/configs/schedulers.yaml
  tests/integration-tests/tests/common/mpi_common.py
  tests/integration-tests/tests/scaling/test_mpi.py
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_pmix/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting.py
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.update.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.update2.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting_disabled_to_enabled_update/pcluster.config.update.yaml
Labels: skip-changelog-update

#6189 [Integ-tests] Use right permission to operate on log files
  tests/integration-tests/tests/common/assertions.py
Labels: skip-changelog-update

#6190 [Integ-tests] Use right permission to operate on log files
  tests/integration-tests/tests/common/assertions.py
Labels: skip-changelog-update

#6191 [Integ-tests] Don't check FSx in dynamic file system update test when not supported
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#6194 [Tests] Merge test_fabric with test_efa
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/gpu.yaml
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/install-fabtests.sh
  tests/integration-tests/tests/efa/test_efa/test_efa/run-fabtests.sh
  tests/integration-tests/tests/efa/test_fabric.py
  tests/integration-tests/tests/efa/test_fabric/test_fabric/pcluster.config.yaml
Labels: skip-changelog-update

#6197 [Versioning] Add CHANGELOG entries for version 3.9.1.
  CHANGELOG.md
Labels: skip-changelog-update, 3.x

#6198 [Versioning] Add CHANGELOG entries for version 3.9.1.
  CHANGELOG.md
Labels: 3.x

#6199 [Integ-tests] Simplify checks in memory based scheduling test
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#6200 Fix bug in log rotation test code
  tests/integration-tests/tests/basic/log_rotation_utils.py
Labels: skip-changelog-update

#6201 [Tests] Move test_mpi to essential features
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/configs/new_instance_types.yaml
  tests/integration-tests/configs/new_os.yaml
  tests/integration-tests/configs/new_region.yaml
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/configs/schedulers.yaml
  tests/integration-tests/tests/basic/test_essential_features.py
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/mpi_ssh.sh
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/pcluster.config.yaml
  tests/integration-tests/tests/common/mpi_common.py
  tests/integration-tests/tests/scaling/test_mpi.py
  tests/integration-tests/tests/scaling/test_mpi/test_mpi/pcluster.config.yaml
  tests/integration-tests/tests/scaling/test_mpi/test_mpi_ssh/pcluster.config.yaml
Labels: skip-changelog-update

#6204 [Test] DFSM: add draining as a valid state for compute nodes marked for draining as part of an update.
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x, Test

#6203 [Test] Add ec2:DeleteTags to the pcluster user role
  cloudformation/policies/parallelcluster-policies.yaml
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x, Test

#6207 [Policies] Add ec2:DeleteTags to the pcluster user role as required by workflows updating the head node instance.
  cloudformation/policies/parallelcluster-policies.yaml
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update, 3.x

#6208 [Test] DFSM: add draining as a valid state for compute nodes marked for draining as part of an update.
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x, Test

#6205 [Tests] Merge test_multiple_jobs_submissions with test_job_level_scaling
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/configs/new_os.yaml
  tests/integration-tests/configs/new_region.yaml
  tests/integration-tests/tests/scaling/test_scaling.py
  tests/integration-tests/tests/scaling/test_scaling/test_job_level_scaling/cluster-check.sh
  tests/integration-tests/tests/scaling/test_scaling/test_job_level_scaling/pcluster.config.yaml
  tests/integration-tests/tests/scaling/test_scaling/test_multiple_jobs_submission/pcluster.config.yaml
Labels: skip-changelog-update

#6213 [Isolated] Using IAM instead of ACM
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update, 3.x

#6215 [integ-tests] Skip custom image test
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update

#6216 [Isolated] Adding DeleteConflictException Exception
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update, 3.x

#6220 Change instance types to support arm architecture
  tests/integration-tests/tests/scaling/test_scaling/test_job_level_scaling/pcluster.config.yaml
Labels: skip-changelog-update

#6221 [CoudFormation] Add 1-click template to deploy a proxy environment for ParallelCluster.
  cloudformation/proxy/proxy.yaml
Labels: skip-changelog-update, 3.x, Environment, Test

#6222 [Integ-tests] Fix CloudWatch test failed because of change for external Slurm dbd
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging.py
Labels: skip-changelog-update

#6225 Create the DDB table and update entries for each test that runs to st…
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_runtest_hooks.py
  tests/integration-tests/conftest_utils.py
  tests/integration-tests/framework/framework_constants.py
  tests/integration-tests/framework/metadata_table_manager.py
  tests/integration-tests/framework/unit_test_metadata_table_publisher.py
Labels: skip-changelog-update

#6226 [slurmdbd] Disable Slurmdbd service by default and add a CFN parameter to enable it and enable CloudWatch logs
  cloudformation/external-slurmdbd/external-slurmdbd.json
  cloudformation/external-slurmdbd/external_slurmdbd/external_slurmdbd_stack.py
  tests/integration-tests/tests/schedulers/conftest.py
Labels: skip-changelog-update
