Repository aws/aws-parallelcluster, pull requests merged in 2024-02, with the labels that each got.

#6047 [Integ] Reducing the number of queues for test_multiple_jobs_submission
  tests/integration-tests/tests/scaling/test_scaling.py
Labels: skip-changelog-update, 3.x

#6061 Add log_group_name to dna.json for ExternalSlurmDbd
  cloudformation/external-slurmdbd/external_slurmdbd/external_slurmdbd_stack.py
Labels: skip-changelog-update, 3.x

#6069 Revert "[DFSM] Add custom resource to check that all compute nodes have the expected cluster config version.
  cli/pytest.ini
  cli/src/pcluster/resources/custom_resources/custom_resources_code/cleanup_resources.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/constants.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/utils/__init__.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/utils/ec2_utils.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/utils/retry_utils.py
  cli/src/pcluster/resources/custom_resources/custom_resources_code/wait_cluster_ready.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/resources/__init__.py
  cli/tests/pcluster/resources/custom_resources/__init__.py
  cli/tests/pcluster/resources/custom_resources/custom_resources_code/__init__.py
  cli/tests/pcluster/resources/custom_resources/custom_resources_code/test_wait_cluster_ready.py
  cli/tests/pcluster/resources/custom_resources/custom_resources_code/utils.py
Labels: skip-changelog-update, 3.x

#6071 Fix S3 bucket name for external slurmdbd stack
  cloudformation/external-slurmdbd/external_slurmdbd/external_slurmdbd_stack.py
Labels: skip-changelog-update, 3.x

#6072 [DFSM] Add permission `dynamodb:BatchGetItem` to the head node policies used by tests.
  tests/iam_policies/user-role.cfn.yaml
  tests/integration-tests/resources/traditional_instance_policy.json
  tests/integration-tests/tests/iam/test_iam.py
Labels: skip-changelog-update, 3.x

#6060 [DFSM] Allow dynamic file system mounting as live update on compute nodes for external EFS/FSx* storage.
  cli/src/pcluster/config/update_policy.py
  cli/src/pcluster/constants.py
  cli/tests/pcluster/config/test_update_policy.py
Labels: skip-changelog-update, 3.x

#6074 [Test] Fix unit test validating template limits and made it more informative.
  cli/tests/pcluster/templates/test_cluster_stack.py
Labels: skip-changelog-update, 3.x

#6075 [CloudFormation] Reduce the size of the compute fleet template
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/templates/queues_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  tests/integration-tests/tests/scaling/test_scaling.py
Labels: skip-changelog-update, 3.x

#6064 Allow AD stacks to be detected and used by another test execution
  cloudformation/ad/ad-integration.yaml
  tests/integration-tests/README.md
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/conftest.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#6077 Update the attribution document for 3.9.0
  THIRD-PARTY-LICENSES.txt
Labels: skip-changelog-update, 3.x

#6078 [Tests] Remove rocky8 from released tests
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update

#6079 [Fix] Introduce hashlib import forgotten in previous PR
  cloudformation/external-slurmdbd/external_slurmdbd/external_slurmdbd_stack.py
Labels: skip-changelog-update, 3.x

#6083 [DFSM] Make compute nodes log on chef-client.log rather than cloud-init.log during creation.
  cli/src/pcluster/resources/compute_node/user_data.sh
Labels: skip-changelog-update, 3.x

#6089 [Develop] Improve DeviceIndex value to 1 on secondary interfaces for compute nodes
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/queues_stack.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/aws/dummy_aws_api.py
  cli/tests/pcluster/config/test_cluster_config.py
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: skip-changelog-update

#6090 [DFSM] Fix error messages returned by the user data for all cluster nodes. In particular, fixed the list of suggested logs.
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/head_node/user_data.sh
  cli/src/pcluster/resources/login_node/user_data.sh
Labels: enhancement, skip-changelog-update, 3.x

#6086 [Disable Sudo]Move DisableSudoAccessForDefaultUser under DeploymentSettings
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/config/common.py
  cli/src/pcluster/config/imagebuilder_config.py
  cli/src/pcluster/schemas/cluster_schema.py
  cli/src/pcluster/schemas/common_schema.py
  cli/src/pcluster/schemas/imagebuilder_schema.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/src/pcluster/templates/queues_stack.py
  cli/tests/pcluster/config/dummy_imagebuilder_config.py
  cli/tests/pcluster/example_configs/slurm.full.yaml
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/schemas/test_imagebuilder_schema.py
  cli/tests/pcluster/schemas/test_imagebuilder_schema/test_imagebuilder_schema/imagebuilder_schema_all.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_head_node_dna_json/slurm-imds-secured-true.yaml
  cli/tests/pcluster/templates/test_login_nodes_stack/test_login_nodes_dna_json/config-1.yaml
  cli/tests/pcluster/templates/test_login_nodes_stack/test_login_nodes_dna_json/dna-1.json
  cli/tests/pcluster/templates/test_queues_stack/test_compute_nodes_dna_json/config-2.yaml
  cli/tests/pcluster/templates/test_queues_stack/test_compute_nodes_dna_json/dna-2.json
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_1.yaml
  cli/tests/pcluster/validators/test_all_validators/test_slurm_all_validators_are_called/slurm_2.yaml
  tests/integration-tests/tests/create/test_create/test_create_disable_sudo_access_for_default_user/pcluster.config.yaml
  tests/integration-tests/tests/create/test_create/test_create_disable_sudo_access_for_default_user/pcluster_update_login_nodes_count_to_0.config.yaml
  tests/integration-tests/tests/create/test_create/test_create_disable_sudo_access_for_default_user/pcluster_update_login_nodes_count_to_1.config.yaml
Labels: skip-changelog-update, 3.x

#6095 [DFSM][Test] Consolidate stack to deploy external storage.
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/storage-stack.yaml
Labels: enhancement, skip-changelog-update, 3.x, Environment

#6093 [Disable Sudo] Changelog Update
  CHANGELOG.md
Labels: skip-changelog-update, 3.x

#6100 [Test] Use argument typing compatible with Python 3.7.
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#6102 Add validator for OS and instance type compatibility
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update

#6101 [Tests] Adding regex pattern to strings
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#6104 Change test_slurm gpu instance type to g4dn.2xlarge
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x, Test

#6103 Support RHEL9 and Rocky9: fix missing changes
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/tests/common/osu_common.py
Labels: skip-changelog-update

#6105 Removing /etc/chef/client.rb from user_data.sh as its set in the AMI's already
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full.all_resources.yaml
  cli/tests/pcluster/templates/test_cluster_stack/test_cluster_config_limits/slurm.full_config.snapshot.yaml
Labels: skip-changelog-update, 3.x

#6106 Add RHEL/Rocky 8.9 to test_build_image
  cli/src/pcluster/models/imagebuilder.py
  tests/integration-tests/README.md
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#6108 [CodeStyle] Remove unsupported option 'no-space-check' for PyLint.
  cli/.pylintrc
Labels: skip-changelog-update, 3.x, Developer Experience

#6107 [DFSM] Remove unnecessary definition of interval from cfn-hup configuration.
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/cluster_stack.py
Labels: skip-changelog-update, 3.x

#6111 Add wait time to allow time for job state to switch to pending
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#6091 Add DO-NOT-DELETE tag to VPC and AD stacks when retain-ad-stack option is selected
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update

#6119 [DFSM] Remove extra period in error message returned by the shared storage update policy.
  cli/src/pcluster/config/update_policy.py
  cli/tests/pcluster/config/test_update_policy.py
Labels: skip-changelog-update, 3.x

#6112 [Limits] Reduce CloudFormation template size by reducing the size of user data.
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/login_node/user_data.sh
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/login_nodes_stack.py
  cli/src/pcluster/templates/queues_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_cluster_stack/test_head_node_dna_json/head_node_default.dna.json
  cli/tests/pcluster/templates/test_login_nodes_stack/test_login_nodes_dna_json/dna-1.json
  cli/tests/pcluster/templates/test_login_nodes_stack/test_login_nodes_dna_json/dna-2.json
  cli/tests/pcluster/templates/test_queues_stack/test_compute_nodes_dna_json/dna-1.json
  cli/tests/pcluster/templates/test_queues_stack/test_compute_nodes_dna_json/dna-2.json
Labels: enhancement, skip-changelog-update, 3.x

#6120 [develop] Change test_build_image test to use Rocky8 instead of Rocky9
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#6124 [Storage][1-click] Use FSxLustre version 2.12 for File Cache in 1-click template for storage
  cloudformation/storage/storage-stack.yaml
Labels: bug, skip-changelog-update, 3.x, Test

#6125 [DFSM][Test] Make 'test_file_systems_update' executable in regions with 2 AZs.
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x, Test

#6116 Fix ParallelClusterClusterPolicy permissions for CloudFormation actions for PCAPI
  cloudformation/policies/parallelcluster-policies.yaml
Labels: skip-changelog-update

#6123 [Custom Resource][Test] Adapt the error messages verified in 'test_cluster_update_invalid' considering that CloudFormation truncates long error messages.
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update, 3.x, Test

#6126 [FileCache] Use FSxLustre version 2.12 for File Cache
  tests/integration-tests/resources/file-cache-storage-cfn.yaml
Labels: skip-changelog-update, 3.x

#6117 [DFSM][Test] Extend integ test 'test_dynamic_file_systems_update' to cover the DFSM as live update.
  tests/integration-tests/tests/common/login_nodes_utils.py
  tests/integration-tests/tests/storage/storage_common.py
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update_rollback.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.yaml
Labels: skip-changelog-update, 3.x, Test

#6133 [release-3.9] Bump aws-batch cli version to 1.3.0
  awsbatch-cli/setup.py
Labels: skip-changelog-update, 3.x
