Repository aws/aws-parallelcluster, pull requests merged in 2024-03, with the labels that each got.

#6136 [DFSM][Docs] Add 3.9.0 changelog item about dynamic file system mounting without fleet replacement.
  CHANGELOG.md
Labels: docs, 3.x

#6137 [DFSM][Docs] Add 3.9.0 changelog item about dynamic file system mounting without fleet replacement.
  CHANGELOG.md
Labels: docs, 3.x

#6138 [release-3.9] Use CloudFormation constant to retrieve Stack ARN for Instance Roles
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_queues_stack.py
Labels: skip-changelog-update

#6140 Shorten the action needed message shown on resizing of the compute fleet
  cli/src/pcluster/config/update_policy.py
  cli/tests/pcluster/config/test_update_policy.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update, 3.x

#6144 [release-3.9]Shorten the action needed message shown on resizing of the compute fleet
  cli/src/pcluster/config/update_policy.py
  cli/tests/pcluster/config/test_update_policy.py
  tests/integration-tests/tests/custom_resource/test_cluster_custom_resource.py
Labels: skip-changelog-update, 3.x

#6145 [develop] Use CloudFormation constant to retrieve Stack ARN for Instance Roles
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_queues_stack.py
Labels: skip-changelog-update

#6146 [develop][Performance tests] Include OS information when uploading to CloudWatch metrics
  tests/integration-tests/tests/performance_tests/test_osu.py
Labels: skip-changelog-update

#6142 Fix assertion when checking node state
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#6147 Fix assertion when checking node state
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x, Test

#6148 Make odcr for MultiAZ integ-tests targeted
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#6149 Make odcr for MultiAZ integ-tests targeted
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#6151 Create a MetricsPublisher class for the integration test framework in anticipation of more Metrics usage throughout
  tests/integration-tests/benchmarks/common/metrics_reporter.py
  tests/integration-tests/framework/metrics_publisher.py
  tests/integration-tests/reports_generator.py
  tests/integration-tests/tests/common/scaling_common.py
  tests/integration-tests/utils.py
Labels: skip-changelog-update

#6153 [Test] Use bigger instance types in test 'test_update_compute_ami'.
  tests/integration-tests/tests/update/test_update/test_update_compute_ami/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_compute_ami/pcluster.config.yaml
Labels: enhancement, skip-changelog-update, 3.x, Test

#6155 Simplify Ubuntu kernel pinning during build image OS update
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update, 3.x

#6160 Update CHANGELOG entries for 3.9.0 release
  CHANGELOG.md
Labels: 3.x

#6163 [release-3.9][integ-tests] Remove tests for Rocky, Remove build-image tests for Ubuntu22
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update

#6165 Add parameters to scaling stress test
  tests/integration-tests/README.md
  tests/integration-tests/conftest.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/performance_tests/test_scaling.py
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling_stress_test/scaling_test_config.yaml
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling_stress_test/scaling_test_config_schema.yaml
Labels: skip-changelog-update

#6164 [Tests] Merge tests for essential features into a single test
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/configs/new_os.yaml
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/tests/basic/disable_hyperthreading_utils.py
  tests/integration-tests/tests/basic/log_rotation_utils.py
  tests/integration-tests/tests/basic/structured_log_event_utils.py
  tests/integration-tests/tests/basic/test_essential_features.py
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/failing_post_install.sh
  tests/integration-tests/tests/basic/test_essential_features/test_essential_features/pcluster.config.yaml
  tests/integration-tests/tests/disable_hyperthreading/__init__.py
  tests/integration-tests/tests/disable_hyperthreading/test_disable_hyperthreading/test_hit_disable_hyperthreading/pcluster.config.yaml
  tests/integration-tests/tests/log_rotation/test_log_rotation/test_log_rotation/pcluster.config.yaml
  tests/integration-tests/tests/monitoring/test_structured_log_events.py
  tests/integration-tests/tests/monitoring/test_structured_log_events/test_custom_compute_action_failure/on_compute_configured_error.sh
  tests/integration-tests/tests/monitoring/test_structured_log_events/test_custom_compute_action_failure/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#6173 [develop] Fix URL encoding for pcluster API client example
  api/client/resources/sigv4_auth.py
  api/client/src/pcluster_client/sigv4_auth.py
Labels: skip-changelog-update

#6172 Add static node stress test
  tests/integration-tests/configs/scaling_stress_test.yaml
  tests/integration-tests/tests/common/scaling/scaling_test_config.yaml
  tests/integration-tests/tests/common/scaling/scaling_test_config_schema.yaml
  tests/integration-tests/tests/common/scaling_common.py
  tests/integration-tests/tests/performance_tests/test_scaling.py
  tests/integration-tests/tests/performance_tests/test_scaling/test_static_scaling_stress_test/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_scaling/test_static_scaling_stress_test/results/baseline.json
Labels: skip-changelog-update

#6174 [Isolated] Reverting changes w.r.t. Ad integration tests
  cloudformation/ad/ad-integration.yaml
  cloudformation/storage/storage-stack.yaml
  tests/integration-tests/README.md
  tests/integration-tests/cfn_stacks_factory.py
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.update2.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration/pcluster.config.yaml
  tests/integration-tests/utils.py
Labels: skip-changelog-update, 3.x

#6176 [Isolated] Adding time of 25 seconds before checking the num of nodes
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#6177 [Isolated] Adding Custom Resource Tests in Isolated regions
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update, 3.x

#6178 Use the MetricsPublisher in the runtest_makereport hook to publish ph…
  tests/integration-tests/conftest.py
  tests/integration-tests/conftest_runtest_hooks.py
  tests/integration-tests/conftest_utils.py
  tests/integration-tests/framework/metrics_publisher.py
  tests/integration-tests/time_utils.py
Labels: skip-changelog-update

#6179 Output bootstrap errors in scaling test
  tests/integration-tests/tests/common/scaling/get_bootstrap_errors.sh
  tests/integration-tests/tests/common/scaling_common.py
  tests/integration-tests/tests/performance_tests/test_scaling.py
Labels: skip-changelog-update
