Repository aws/aws-parallelcluster, pull requests merged in 2024-11, with the labels that each got.

#6524 [integ-test-framework] Release xdist fixture if a process is DEAD
  tests/integration-tests/framework/fixture_utils.py
Labels: skip-changelog-update

#6525 Change test_error_handling region to eu-west-1
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#6527 [integ-tests] Improve build-image integration tests
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#6520 [Docs] Fix changelog entry for version 3.11.1.
  CHANGELOG.md
Labels: docs, 3.x

#6526 Move reboot step to be before installing kernel package during OS update
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#6518 Adding Efs and Ebs for weekly scaling tests
  tests/integration-tests/configs/scaling.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/tests/common/scaling/scaling_test_config.yaml
  tests/integration-tests/tests/common/scaling/scaling_test_config_schema.yaml
  tests/integration-tests/tests/performance_tests/test_scaling.py
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling/pcluster.config.yaml
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/pcluster.config.yaml
  tests/integration-tests/tests/scaling/test_scaling.py
  tests/integration-tests/tests/scaling/test_scaling/test_scaling_special_cases/pcluster-downscale.config.yaml
  tests/integration-tests/tests/scaling/test_scaling/test_scaling_special_cases/pcluster-upscale.config.yaml
  tests/integration-tests/tests/scaling/test_scaling/test_scaling_special_cases/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_efs/test_efs_access_point/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_efs/test_efs_same_az/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_efs/test_multiple_efs/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_fsx_lustre_configuration_options/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6531 [integ-tests] Fix tests in iso regions
  cloudformation/storage/storage-stack.yaml
  tests/integration-tests/network_template_builder.py
  tests/integration-tests/resources/file-cache-storage-cfn.yaml
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update

#6532 [integ-tests] Improve build-image integration tests
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#6533 [Docs] Add breaking change to changelog for version 3.11.0 about loginNodes field returned by DescribeCluster API and describe-cluster CLI command.
  CHANGELOG.md
Labels: docs, 3.x

#6534 Force delete if delete fails during cleanup
  tests/integration-tests/cfn_stacks_factory.py
Labels: skip-changelog-update

#6535 Rename reboot step
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
Labels: skip-changelog-update

#6536 [integ-test] Enhance test_efa by printing slurm.out for debugging
  tests/integration-tests/tests/efa/test_efa.py
Labels: skip-changelog-update, 3.x

#6539 [Integ test] Increase the instance size and overall time we wait for state change
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_scontrol_reboot/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6545 [Integ Test] Fix test_build_image by adding required export logs policy to CustomS3Bucket
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update, 3.x

#6541 [Test] In test_capacity_blocks, replace t3.micro with t3.medium to prevent memory issues causing bootstrap errors.
  tests/integration-tests/tests/capacity_reservations/test_capacity_blocks/test_capacity_blocks/override_capacity_blocks.sh
  tests/integration-tests/tests/capacity_reservations/test_capacity_blocks/test_capacity_blocks/pcluster.config.yaml
Labels: skip-changelog-update, 3.x, Test

#6546 [Test] Move AD integ test from eu-central-1 to ap-northeast-1 because SimpleAD is not available in eu-central-1.
  tests/integration-tests/configs/ad_integration.yaml
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x, Test

#6540 [Scaling test] Reduce failures in Scaling stress tests
  tests/integration-tests/tests/performance_tests/test_scaling.py
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling_stress_test/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_scaling/test_static_scaling_stress_test/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6553 [integ-test-framework] Terminate processes where tests have finished
  tests/integration-tests/framework/fixture_utils.py
Labels: skip-changelog-update

#6554 [Scaling] Use more tolerant checks for testing
  tests/integration-tests/tests/common/scaling_common.py
  tests/integration-tests/tests/performance_tests/test_scaling.py
Labels: skip-changelog-update, 3.x

#6559 [Integ-tests] Use right permission to operate on log files
  tests/integration-tests/tests/basic/log_rotation_utils.py
Labels: skip-changelog-update

#6560 [Integ-tests] Fix build-image integration test
  tests/integration-tests/tests/createami/test_createami/test_build_image_custom_components/image.config.yaml
Labels: skip-changelog-update

#6561 [Integ-tests] Make capacity reservation according operating systems
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#6547 [Integ-Test] Fix test_dcv intermittent failure by filter running instance
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging.py
Labels: skip-changelog-update

#6563 [Integ-Test] Fix test_dcv intermittent failure by filter running instance
  tests/integration-tests/tests/cloudwatch_logging/test_cloudwatch_logging.py
Labels: skip-changelog-update, 3.x

#6565 [integ-tests] Rotate OSes for EFA tests
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/framework/tests_configuration/config_renderer.py
Labels: skip-changelog-update

#6566 [Integ-Test] Fix test_build_image_custom_components integration test
  tests/integration-tests/tests/createami/test_createami/test_build_image_custom_components/image.config.yaml
Labels: skip-changelog-update, 3.x

#6570 [Issues] Include wiki and closed issues in GitHub Issues template.
  .github/ISSUE_TEMPLATE/bug_report_2.md
  .github/ISSUE_TEMPLATE/bug_report_3.md
Labels: skip-changelog-update, 3.x

#6573 Renaming NICE to Amazon DCV
  cli/src/pcluster/cli/commands/dcv_connect.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/cli/test_dcv_connect/TestDcvConnectCommand/test_helper/pcluster-help.txt
  cli/tests/pcluster/cli/test_entrypoint/TestParallelClusterCli/test_helper/pcluster-help.txt
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  cli/tests/pcluster/validators/test_feature_validators.py
Labels: skip-changelog-update, 3.x

#6574 [Security] Add permissions to create/delete service linked role for ELB and ASG, required by login nodes
  CHANGELOG.md
  cloudformation/policies/parallelcluster-policies.yaml
Labels: bug, 3.x, Security

#6576 [Dependency] Add Changelog entry for update of Amazon DCV and Mysql
  CHANGELOG.md
Labels: 3.x

#6580 [Test] In test 'test_update_slurm', use instance types with higher availability to reduce the risk of ICEs.
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.yaml
Labels: skip-changelog-update, 3.x, Test

#6579 [Test] In test 'test_update_slurm', use instance types with higher availability to reduce the risk of ICEs.
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.yaml
Labels: skip-changelog-update, 3.x, Test

#6575 [develop] Add bad URL suffix pull request check
  .github/workflows/unsafe_patterns_checker.yml
Labels: skip-changelog-update, 3.x
