Repository aws/aws-parallelcluster, pull requests merged in 2024-09, with the labels that each got.

#6420 [integ-tests] Improve scaling tests
  tests/integration-tests/configs/scaling_stress_test.yaml
  tests/integration-tests/tests/common/scaling/scaling_test_config.yaml
  tests/integration-tests/tests/performance_tests/test_scaling.py
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling_stress_test/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_scaling/test_static_scaling_stress_test/pcluster.config.yaml
Labels: skip-changelog-update

#6421 [Develop] Fix test_slurm errors
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/pcluster.config.yaml
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm_from_login_nodes_in_private_network/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6423 [Develop] Fix No route tables found bug when specifying default VPC subnet to LoginNodes/Networking/SubnetIds
  CHANGELOG.md
  cli/src/pcluster/aws/ec2.py
Labels: 3.x

#6422 Update libfabric version in test_efa
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/install-fabtests.sh
Labels: skip-changelog-update

#6426 [integ-tests] Improve test_login_nodes_update and add it to daily run
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/isolated_regions.yaml
  tests/integration-tests/tests/update/test_update.py
  tests/integration-tests/tests/update/test_update/test_login_nodes_update/pcluster_create_without_login_nodes.config.yaml
  tests/integration-tests/tests/update/test_update/test_login_nodes_update/pcluster_update_login_nodes_count_to_0.config.yaml
  tests/integration-tests/tests/update/test_update/test_login_nodes_update/pcluster_update_login_nodes_count_to_1.config.yaml
  tests/integration-tests/tests/update/test_update/test_login_nodes_update/pcluster_update_login_nodes_count_to_3.config.yaml
Labels: skip-changelog-update

#6427 Add IAM policy elasticloadbalancing:DescribeTargetHealth
  cloudformation/policies/parallelcluster-policies.yaml
  tests/iam_policies/user-role.cfn.yaml
Labels: skip-changelog-update

#6425 Add the region flag to the imagebuilder component custom script download action
  cli/src/pcluster/resources/imagebuilder/custom_script.yaml
  cli/src/pcluster/templates/imagebuilder_stack.py
Labels: skip-changelog-update

#6424 Add the region flag to the imagebuilder component custom script download action
  cli/src/pcluster/resources/imagebuilder/custom_script.yaml
  cli/src/pcluster/templates/imagebuilder_stack.py
Labels: skip-changelog-update

#6430 Update the shared home test to check correct perms on /home
  tests/integration-tests/tests/storage/test_shared_home.py
Labels: skip-changelog-update

#6432 Refactor snapshot factory to use f strings instead of bizarre {}1 syntax
  tests/integration-tests/tests/storage/snapshots_factory.py
Labels: skip-changelog-update

#6434 Fix test_ebs_snapshot, output name instead of pkname from df call for fs check
  tests/integration-tests/tests/storage/test_ebs.py
Labels: skip-changelog-update

#6436 [Integ-test] Reduce sporadic failures from `test_slurm_memory_based_scheduling
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#6439 [Integ-test] Change createami integration test in govcloud to use alinux2
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#6440 [Integ-test] Change createami integration test in govcloud to use alinux2
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update

#6438 Upgrade rocky9 version in createami to 9.4
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#6441 Upgrade rocky9 version in createami to 9.4
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x, Test
