Repository aws/aws-parallelcluster, pull requests merged in 2025-09, with the labels that each got.

#6953 [3.14.0][Changelog] Address formatting/wording issue in 3.14.0 CLI changelog
  CHANGELOG.md
Labels: 3.x

#6952 [integ-test-framework] Remove check on the number of os, scheduler, instances, regions when existing cluster is specified
  tests/integration-tests/test_runner.py
Labels: skip-changelog-update

#6960 [Test] Disable nvidia and lustre installation for ubuntu2404 in createami test
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update

#6959 [IntegTest][GB200] Fix GB200 Integ Test and Improve the IMEX Setup Prolog Script
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/ultraserver/test_gb200.py
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/90-nvidia-imex.prolog.sh
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.final.yaml
Labels: skip-changelog-update, 3.x

#6961 [integ-test] Improve NCCL test to consider instance types with different numbers of GPUs
  tests/integration-tests/tests/common/schedulers_common.py
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update

#6957 [Test Gb200] Update test to skip simulated checks
  tests/integration-tests/tests/ultraserver/test_gb200.py
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/91_nvidia_imex_prolog.sh
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.final.yaml
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.update.yaml
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6963 [integ-test] Add Rocky/RHEL to NCCL test
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/init_nccl_benchmarks.sh
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update

#6965 Use rocky 8.10 AMI for createami tests
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update

#6967 Remove GdrSupport from p6e-gb200 instance as its automatically enable
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.final.yaml
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.update.yaml
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6969 [develop][ChangeLog] Update EFA version in the ChangeLog
  CHANGELOG.md
Labels: 3.x

#6970 [Gb200] Adding p6e-gb200 test in daily integration test if it exist
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/ultraserver/test_gb200.py
Labels: skip-changelog-update, 3.x

#6968 [integ-test] Run NCCL test with p6e-GB200
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/ultraserver/test_gb200.py
Labels: skip-changelog-update

#6975 [Gb200] Update Boto3 version to add support for EC2 describe_capacity_block_status
  api/client/requirements.txt
  api/client/resources/client-requirements.txt.patch
  api/client/src/requirements.txt
  awsbatch-cli/requirements.txt
  awsbatch-cli/setup.py
  cli/requirements.txt
  cli/setup.py
Labels: skip-changelog-update, 3.x

#6979 [integ-tests] Retain build image instance on failure for easy debugging
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: skip-changelog-update

#6980 [integ-tests] With test_gb200, only run MPI check when instance is GB200
  tests/integration-tests/tests/ultraserver/test_gb200.py
Labels: skip-changelog-update

#6986 [Gb200][Prolog] Use Slurm environment variables for getting queue and compute resource name
  tests/integration-tests/tests/ultraserver/test_gb200.py
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/91_nvidia_imex_prolog.sh
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/nvidia-imex-status.job
Labels: skip-changelog-update, 3.x

#6987 [integ-tests] Use m6g.16xlarge as head node for test gb200
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.final.yaml
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.update.yaml
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/pcluster.config.yaml
Labels: skip-changelog-update

#6988 [Gb200][Prolog] Use local variables for better readability
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/91_nvidia_imex_prolog.sh
Labels: skip-changelog-update, 3.x

#6991 Revert "[Develop][GB200] Add concurrent control mechanisms to nvidia-imex prolog script"
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/91_nvidia_imex_prolog.sh
Labels: skip-changelog-update, 3.x

#6992 [integ-test] Upgrade Fabtests to version 2.3.0
  tests/integration-tests/tests/efa/test_efa/test_efa/install-fabtests.sh
Labels: skip-changelog-update

#6993 [Gb200][Prolog] Redirect the Prolog logs in system logs
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/91_nvidia_imex_prolog.sh
Labels: skip-changelog-update, 3.x

#6996 [Gb200][Test] Add sleep for IMEX status Job
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/nvidia-imex-status.job
Labels: skip-changelog-update, 3.x

#6999 [integ-tests] Let serial_execution_by_instance to take effect on all p-series instances
  tests/integration-tests/conftest.py
Labels: skip-changelog-update

#7001 Bump version for awsbatch-cli to 1.5.0
  awsbatch-cli/setup.py
Labels: skip-changelog-update

#7006 [integ-tests] Find capacity blocks by OS platform
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/ultraserver/test_gb200.py
Labels: skip-changelog-update

#7008 [Integ-tests] Add Active state as filter for Capacity Reservations
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#7014 Add RDMAV_FORK_SAFE parameter to NCCL test
  tests/integration-tests/tests/common/data/nccl/nccl_tests_submit_openmpi.sh
Labels: skip-changelog-update

#7013 [GB200] Make IMEX prolog use local IMEx configurations + test fixes
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/ultraserver/test_gb200.py
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/91_nvidia_imex_prolog.sh
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/nvidia-imex-status.job
Labels: skip-changelog-update, 3.x, Test

#7023 [Gb200][Test] Add a bash script which checks for IMEX status is UP in a job
  tests/integration-tests/tests/common/data/mpi/mpi_submit_openmpi.sh
  tests/integration-tests/tests/common/data/nccl/nccl_tests_submit_openmpi.sh
  tests/integration-tests/tests/common/nccl_common.py
  tests/integration-tests/tests/ultraserver/test_gb200.py
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/91_nvidia_imex_prolog.sh
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/check_imex_status.sh
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/head_node_start.sh
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/nvidia-imex-status.job
Labels: skip-changelog-update, 3.x

#7024 [Gb200][Test] Check Imex status is UP in check_imex_status.sh
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/check_imex_status.sh
Labels: skip-changelog-update, 3.x

#7029 [Test] For EFS auxiliary stack, make instance depends on the instance profile to mitigate risks of instance bootstrap failures
  tests/integration-tests/tests/storage/storage_common.py
Labels: skip-changelog-update, 3.x, Test

#7032 [Test]Modify to use `--capacity-reservation-id` as part of get_capacity_reservation_id
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/efa/test_efa.py
  tests/integration-tests/tests/performance_tests/test_osu.py
  tests/integration-tests/tests/ultraserver/test_gb200.py
Labels: skip-changelog-update, 3.x

#7033 [Gb200][Test]For non-imex domain nodes we expect the IMEX status to be down
  tests/integration-tests/tests/ultraserver/test_gb200.py
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/check_imex_status.sh
  tests/integration-tests/tests/ultraserver/test_gb200/test_gb200/nvidia-imex-status.job
Labels: skip-changelog-update, 3.x

#7031 [Test][Release] Fix test_slurm_accounting ICE issue
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.update.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.update2.yaml
  tests/integration-tests/tests/schedulers/test_slurm_accounting/test_slurm_accounting/pcluster.config.yaml
Labels: skip-changelog-update, 3.x
