Repository aws/aws-parallelcluster, pull requests merged in 2025-02, with the labels that each got.

#6654 [Test] In test_build_image, specify the subnet and security group for the build instance to broaden the coverage of the feature.
  tests/iam_policies/user-role.cfn.yaml
  tests/integration-tests/tests/createami/test_createami/test_build_image/image.config.yaml
Labels: skip-changelog-update, 3.x, Test

#6662 [Test] Fix test_build_image_custom_components by ensuring that the right custom component script is executed on all Ubuntu versions.
  tests/integration-tests/tests/createami/test_createami.py
Labels: skip-changelog-update, 3.x, Test

#6655 [Scaling] Removing usage of cfn-init for compute fleet
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/templates/cdk_builder_utils.py
  cli/src/pcluster/templates/cluster_stack.py
  cli/src/pcluster/templates/queues_stack.py
  cli/tests/pcluster/templates/test_cluster_stack.py
  cli/tests/pcluster/templates/test_queues_stack.py
Labels: skip-changelog-update, 3.x

#6663 Fix ubuntu24 in parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update

#6664 [Scaling] Update changelog
  CHANGELOG.md
Labels: 3.x

#6669 Add "ap-southeast-5", "ap-southeast-7" to unsupported AWS Batch validator
  cli/src/pcluster/constants.py
Labels: skip-changelog-update

#6670 [Permissions] Add new parameter 'ParallelClusterFunctionAdditionalPolicies' to the ParallelCluster API stack to add custom permissions for the API Lambda role, on top of the default ones.
  CHANGELOG.md
  api/infrastructure/deploy-api.sh
  api/infrastructure/parallelcluster-api.yaml
  cloudformation/policies/parallelcluster-policies.yaml
Labels: enhancement, 3.x

#6674 Fix cuda deviceQuery test
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update

#6676 [integ-tests] Add ap-southeast-5 ap-southeast-7 regions to common.jinja2
  tests/integration-tests/configs/common.jinja2
Labels: skip-changelog-update

#6677 [Performance tests]Disabling Fast Failover for performance tests
  tests/integration-tests/tests/performance_tests/test_scaling.py
  tests/integration-tests/tests/performance_tests/test_scaling/test_scaling_stress_test/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6678 Fix cuda deviceQuery test
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update

#6680 Adding validator for the length of LoginNode pools to be 10
  CHANGELOG.md
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: 3.x
