Repository aws/aws-parallelcluster, pull requests merged in 2025-01, with the labels that each got.

#6632 Using Pseudo Function to get Service URL Domain
  cloudformation/ad/ad-integration.yaml
  cloudformation/proxy/proxy.yaml
  tests/iam_policies/cluster-roles.cfn.yaml
  tests/integration-tests/tests/ad_integration/test_ad_integration/test_ad_integration_on_login_nodes/ad_stack.yaml
Labels: skip-changelog-update, 3.x

#6633 [Develop] Move proxy setting to the beginning of user_data.sh to avoid cfn command failure issue
  CHANGELOG.md
  cli/src/pcluster/resources/compute_node/user_data.sh
  cli/src/pcluster/resources/login_node/user_data.sh
Labels: 3.x

#6636 [integ-tests] Remove build image test in China from released.yaml
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update

#6635 [integ-tests] Remove build image test in China from released.yaml
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update

#6637 [integ-tests] Add tests from develop.yaml to isolated_regions.yaml
  tests/integration-tests/configs/isolated_regions.yaml
Labels: skip-changelog-update

#6638 [integ-tests] Add update to the test_efs_access_point test
  tests/integration-tests/conftest_tests_config.py
  tests/integration-tests/framework/tests_configuration/config_utils.py
  tests/integration-tests/framework/tests_configuration/config_validator.py
  tests/integration-tests/tests/storage/test_efs.py
  tests/integration-tests/tests/storage/test_efs/test_efs_access_point/pcluster.config.update.yaml
Labels: skip-changelog-update

#6644 [integ-test] Fix test_cli_commands in iso regions
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
Labels: skip-changelog-update

#6643 [integ-test] Fix test_cli_commands in iso regions
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
Labels: skip-changelog-update

#6645 [integ-test] rotate instance types for some integration tests
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/framework/tests_configuration/config_renderer.py
  tests/integration-tests/tests/health_checks/test_gpu_health_checks.py
  tests/integration-tests/tests/health_checks/test_gpu_health_checks/test_cluster_with_gpu_health_checks/pcluster.config.yaml
Labels: skip-changelog-update

#6646 [integ-test] Fix test_cluster_with_gpu_health_checks
  tests/integration-tests/tests/health_checks/test_gpu_health_checks.py
Labels: skip-changelog-update

#6647 [integ-test] Run test_cluster_with_gpu_health_checks in us-west-2 instead of eu-west-1 to test more instance types
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update
