Repository aws/aws-parallelcluster, pull requests merged in 2025-04, with the labels that each got.

#6772 Use less powerful EFS and FSx in tests and example template
  cloudformation/storage/storage-stack.yaml
  tests/integration-tests/resources/file-cache-storage-cfn.yaml
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.update.yaml
  tests/integration-tests/tests/networking/test_security_groups/test_overwrite_sg/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_efs/test_multiple_efs/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre.py
  tests/integration-tests/tests/storage/test_fsx_lustre/test_fsx_lustre/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_fsx_lustre_backup/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_fsx_lustre_dra/pcluster.config.update.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_fsx_lustre_dra/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_multi_az_fsx/pcluster-managed-fsx.config.yaml
  tests/integration-tests/tests/storage/test_fsx_lustre/test_multiple_fsx/pcluster.config.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update/pcluster.config.update.yaml
  tests/integration-tests/tests/update/test_update/test_dynamic_file_systems_update_rollback/pcluster.config.update_rollback.yaml
  tests/integration-tests/tests/update/test_update/test_update_slurm/pcluster.config.update.yaml
Labels: skip-changelog-update

#6778 Fix File Cache templates
  cloudformation/storage/storage-stack.yaml
  tests/integration-tests/resources/file-cache-storage-cfn.yaml
Labels: skip-changelog-update

#6775 Deprecate Ubuntu 20.04
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_tag.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
  cli/src/pcluster/resources/imagebuilder/update_and_reboot.yaml
  cli/src/pcluster/templates/cw_dashboard_builder.py
  cli/tests/pcluster/aws/test_ec2.py
  cli/tests/pcluster/cli/configure/test_pcluster_configure.py
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_disabled_efa_no_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_efa_not_supported/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_default_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_existing_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_enabled_efa_non_existent_placement_group/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_filtered_subnets_by_az/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_no_automation_no_awsbatch_no_errors/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_no_input_no_automation_no_errors/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_subnet_automation_no_awsbatch_no_errors/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_subnet_automation_no_awsbatch_no_errors_empty_vpc/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_vpc_automation_no_awsbatch_no_errors/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_vpc_automation_no_vpc_in_region/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_vpc_automation_no_vpc_in_region_public/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure/test_with_region_arg/output.txt
  cli/tests/pcluster/cli/configure/test_pcluster_configure_utils.py
  cli/tests/pcluster/cli/test_describe_image.py
  cli/tests/pcluster/example_configs/awsbatch.full.yaml
  cli/tests/pcluster/schemas/test_cluster_schema.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder.py
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/ubuntu24.slurm.no_dashboard.yaml
  cli/tests/pcluster/templates/test_cw_dashboard_builder/test_cw_dashboard_builder/ubuntu24.slurm.simple.yaml
  cli/tests/pcluster/test_utils.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
  tests/integration-tests/README.md
  tests/integration-tests/configs/ad_integration.yaml
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/dummy.yaml
  tests/integration-tests/configs/installer.yaml
  tests/integration-tests/configs/new_instance_types.yaml
  tests/integration-tests/configs/new_region.yaml
  tests/integration-tests/configs/openfoam.yaml
  tests/integration-tests/configs/released.yaml
  tests/integration-tests/configs/starccm.yaml
  tests/integration-tests/configs/startup_time_performance.yaml
  tests/integration-tests/tests/common/utils.py
  tests/integration-tests/tests/create/test_create.py
  tests/integration-tests/utils.py
Labels: 3.x

#6781 Test api login nodes format
  tests/integration-tests/tests/pcluster_api/test_api.py
Labels: skip-changelog-update

#6782 [Bug Fix] Rocky AMI's work with Linux/Unix Platform
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: 3.x

#6783 [integ-tests-framework] Create capacity reservation before test execution
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/openfoam.yaml
  tests/integration-tests/configs/osu.yaml
  tests/integration-tests/configs/starccm.yaml
  tests/integration-tests/conftest.py
  tests/integration-tests/framework/tests_configuration/config_renderer.py
  tests/integration-tests/tests/efa/test_efa/test_efa/pcluster.config.yaml
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/pcluster.config.yaml
Labels: skip-changelog-update

#6786 [integ-tests] Speed up integration tests by reducing GracetimePeriod for login nodes
  tests/integration-tests/tests/storage/test_ebs/test_ebs_single/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_ebs/test_ebs_snapshot/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_efs/test_efs_use_login_nodes/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_internal_efs/test_internal_efs/pcluster.config.yaml
  tests/integration-tests/tests/storage/test_shared_home/test_shared_home/pcluster.config.yaml
  tests/integration-tests/tests/users/test_default_user_home/test_default_user_local_home/pcluster.config.yaml
Labels: skip-changelog-update

#6785 [integ-tests-framework] Fix capacity reservation creation logic
  tests/integration-tests/framework/tests_configuration/config_renderer.py
Labels: skip-changelog-update

#6788 [Region Support][release-3.13] Re-add KUL region support and include it in integ-tests
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/supported-regions
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
Labels: 3.x

#6787 [Region Support][develop] Re-add KUL region support and include it in integ-tests
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/supported-regions
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
Labels: 3.x

#6789 Check that cluster has login nodes
  tests/integration-tests/tests/pcluster_api/test_api.py
Labels: skip-changelog-update

#6791 [Integ-test] Add ap-southeast-3, ap-southeast-5, ap-southeast-7 in ZONE_ID_MAPPING
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update, 3.x

#6792 [Integ-test] Add ap-southeast-3, ap-southeast-5, ap-southeast-7 in ZONE_ID_MAPPING
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update, 3.x

#6793 [Integ-test] Add ap-southeast-3, ap-southeast-5, ap-southeast-7 in ZONE_ID_MAPPING
  tests/integration-tests/conftest_networking.py
Labels: skip-changelog-update, 3.x

#6790 [integ-tests-framework] Add --pcluster-installer-path and run test_slurm_cli_commands with installer
  tests/integration-tests/conftest.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
Labels: skip-changelog-update

#6795 [test] Change OS to 22 and 24 as we no longer support 20
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-installation.sh
Labels: skip-changelog-update, 3.x

#6796 [Isolated][Tests] Adding Partition for Proxy tests
  cloudformation/proxy/proxy.yaml
Labels: skip-changelog-update, 3.x

#6797 [Isolated][Tests] Adding Partition for Proxy tests
  cloudformation/proxy/proxy.yaml
  tests/integration-tests/framework/credential_providers.py
Labels: skip-changelog-update, 3.x

#6800 [integ-tests-framework] Fix CloudWatch name retrieval
  tests/integration-tests/clusters_factory.py
Labels: skip-changelog-update

#6801 [integ-tests-framework] Make capacity reservation consider more information
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/framework/tests_configuration/config_renderer.py
Labels: skip-changelog-update

#6803 [AD] In 1-click template used to deploy AD infrastructure, enforce the desired domain name in adcli commands to prevent connection errors.
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update, 3.x, Test

#6805 [AD] In 1-click template used to deploy AD infrastructure, enforce the desired domain name in adcli commands to prevent connection errors.
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update, 3.x
