Repository aws/aws-parallelcluster, pull requests merged in 2025-03, with the labels that each got.

#6681 [ActiveDirectory] In AD template, create users without joining the domain
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update, 3.x, Test

#6683 [Test] Fix test_efa by using the right architecture for instance type c6gn.16xlarge and an AZ where the instance is generally more available.
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x, Test

#6684 [Ubuntu24] Add Ubuntu24.04 to the maps used to determine the official AMI name for the OS.
  cli/src/pcluster/constants.py
Labels: bug, skip-changelog-update, 3.x

#6685 Install cmake using cookbook_virtual_env for validating Cuda
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
Labels: skip-changelog-update, 3.x

#6687 [Integ test] Moving check of Job state after cluster update
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#6689 [Test][ActiveDirectory] In test AD, replace the use of service command with systemctl to prevent failures on Rocky9 where service command is not found.
  tests/integration-tests/tests/ad_integration/test_ad_integration.py
Labels: skip-changelog-update, 3.x, Test

#6686 [ActiveDirectory] Make AD user creation more robust, wrapping the logic into a retry block.
  cloudformation/ad/ad-integration.yaml
Labels: skip-changelog-update, 3.x, Test

#6690 [integ-tests] Fix sporadic failures of test_multiple_nics
  tests/integration-tests/tests/multiple_nics/test_multiple_nics.py
Labels: skip-changelog-update

#6691 [integ-tests] Adding only NVIDIA GPU instances for testing
  tests/integration-tests/framework/tests_configuration/config_renderer.py
  tests/integration-tests/tests/health_checks/test_gpu_health_checks/test_cluster_with_gpu_health_checks/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6692 [Test] In test_efa, when running on Ubuntu 24.04, remove the EXTERNALLY-MANAGED flag of the system installation of Python to unblock installation of Fabtests.
  tests/integration-tests/tests/efa/test_efa/test_efa/install-fabtests.sh
Labels: skip-changelog-update, 3.x, Test

#6694 Add ubuntu24 tags
  cli/src/pcluster/resources/imagebuilder/parallelcluster_tag.yaml
Labels: skip-changelog-update

#6697 [integ-tests] fix test_iam_policies
  tests/integration-tests/tests/iam/test_iam.py
Labels: skip-changelog-update

#6698 [Integ Test] Increase stop_max_delay to fix test_error_handling
  tests/integration-tests/tests/common/hit_common.py
Labels: skip-changelog-update, 3.x

#6700 [Test] In test_essential_features, increase the max time to wait for the failing instance to be terminated from 5min to 6min.
  tests/integration-tests/tests/common/assertions.py
Labels: skip-changelog-update, 3.x, Test

#6702 [Integ-Test] Decrease max delay to 6 minutes
  tests/integration-tests/tests/common/hit_common.py
Labels: skip-changelog-update, 3.x

#6699 [Integ Test] Increase stop_max_delay to fix test_error_handling
  tests/integration-tests/tests/common/hit_common.py
Labels: skip-changelog-update, 3.x

#6705 [Docs] Update changelog for release 3.13.0.
  CHANGELOG.md
Labels: docs, 3.x

#6707 [Test] Relax test_slurm_scaling for Rocky
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x, Test

#6709 [Test] Relax test_slurm_scaling for Rocky
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x, Test

#6711 [Test] Add Ubuntu24, RHEL9 and Rocky9 to StarCCM performance tests.
  tests/integration-tests/configs/starccm.yaml
  tests/integration-tests/tests/performance_tests/test_starccm.py
Labels: skip-changelog-update, 3.x, Test

#6716 [Test] Fix Neuron installation and execution for trainium test.
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-ccl.sh
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-installation.sh
Labels: skip-changelog-update, 3.x, Test

#6717 [Test] Fix Neuron installation and execution for trainium test.
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-ccl.sh
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-installation.sh
Labels: skip-changelog-update, 3.x, Test

#6718 [Test] Fix syntax error in test slurm scaling.
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: bug, skip-changelog-update, 3.x, Test

#6719 [Test] Fix syntax error in test slurm scaling.
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x, Test

#6720 [Integ-Test] Fix test_queue_parameters_update
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#6721 [Integ-Test] Fix test_queue_parameters_update
  tests/integration-tests/tests/update/test_update.py
Labels: skip-changelog-update, 3.x

#6724 [Test] Removing command which is not part a variable
  tests/integration-tests/tests/trainium/test_trainium/test_trainium/neuron-ccl.sh
Labels: skip-changelog-update, 3.x

#6722 [Storage] Restore default EBS volume size to 40GB. This is the size used for shared storage.
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
Labels: skip-changelog-update, 3.x

#6726 [Storage] Restore default EBS volume size to 40GB. This is the size used for shared storage
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
Labels: skip-changelog-update, 3.x

#6729 [Test] Adding Ubu24 to the set of default OSes covered by tests.
  tests/integration-tests/configs/common.jinja2
Labels: skip-changelog-update, Test

#6732 [Test] Fix script used to run OSU benchmark with IntelMPI.
  tests/integration-tests/tests/common/data/osu/osu_pt2pt_submit_intelmpi.sh
Labels: bug, skip-changelog-update, 3.x, Test

#6733 [Test] Fix script used to run OSU benchmark with IntelMPI.
  tests/integration-tests/tests/common/data/osu/osu_pt2pt_submit_intelmpi.sh
Labels: bug, skip-changelog-update, 3.x, Test

#6728 [Test] Fix test shared home by setting the expected size for the shared ebs volume.
  tests/integration-tests/tests/storage/test_shared_home.py
Labels: skip-changelog-update, 3.x, Test

#6730 [Test] Remove AL23 from test OpenFOAM as it is not supported
  tests/integration-tests/configs/openfoam.yaml
Labels: skip-changelog-update, 3.x, Test

#6734 [Test] Adding Ubuntu24 AMI for REMARKABLE amis
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#6736 [integ-tests] Relax test condition to allow EBS volume size reporting discrepancy
  tests/integration-tests/tests/storage/test_shared_home.py
Labels: skip-changelog-update

#6735 [Test] Adding Ubuntu24 AMI for REMARKABLE amis
  tests/integration-tests/tests/common/utils.py
Labels: skip-changelog-update, 3.x

#6738 Add syslogs of Ubuntu24 in cw widget
  cli/src/pcluster/templates/cw_dashboard_builder.py
Labels: skip-changelog-update, 3.x

#6739 Add syslogs of Ubuntu24 in cw widget
  cli/src/pcluster/templates/cw_dashboard_builder.py
Labels: skip-changelog-update, 3.x

#6744 [Test] Fix script used to run OSU benchmark with IntelMPI.
  tests/integration-tests/tests/common/data/osu/osu_pt2pt_submit_intelmpi.sh
Labels: skip-changelog-update, 3.x, Test

#6745 [Test] Changed logging level for metadata table manager from info to debug to reduce noise on tests logs.
  tests/integration-tests/framework/metadata_table_manager.py
Labels: skip-changelog-update, 3.x, Test

#6746 [Test] Changed logging level for metadata table manager from info to debug to reduce noise on tests logs.
  tests/integration-tests/framework/metadata_table_manager.py
Labels: skip-changelog-update, 3.x, Test

#6737 [Integ-Test] Fix test_slurm_scaling by increasing job running time and setting stop_max_delay_secs based on the OS
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#6749 [Integ-Test] Fix test_slurm_scaling
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update, 3.x

#6747 Add Validator to check OS & Capacity Reservation Platform match
  cli/src/pcluster/aws/aws_resources.py
  cli/src/pcluster/config/cluster_config.py
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_all_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update, 3.x

#6750 [integ-tests] Run Ubuntu2404 with Lustre tests
  cli/src/pcluster/constants.py
Labels: skip-changelog-update

#6752 [Integ-Test] Move test_trainium to use2-az3 as there are more trn1.32xlarge instances
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x

#6753 [Integ-Test] Move test_trainium to use2-az3 as there are more trn1.32xlarge instances
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x

#6754 [Ubuntu24] Add Ubuntu24 for other validators
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update, 3.x

#6757 [Ubuntu24] Add Ubuntu24 for other validators
  cli/src/pcluster/constants.py
  cli/src/pcluster/validators/ec2_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
  cli/tests/pcluster/validators/test_ec2_validators.py
Labels: skip-changelog-update, 3.x

#6755 [Test] In test_pyxis, when run on Ubuntu24.04, disable kernel setting 'apparmor_restrict_unprivileged_userns'
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/compute_node_start.sh
Labels: skip-changelog-update, 3.x, Test

#6756 [Test] In test_pyxis, when run on Ubuntu24.04, disable kernel setting 'apparmor_restrict_unprivileged_userns'
  tests/integration-tests/tests/pyxis/test_pyxis/test_pyxis/compute_node_start.sh
Labels: skip-changelog-update, 3.x, Test

#6759 [build-image] Add internal parameter to distinguish official AMI build
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
  cli/src/pcluster/templates/imagebuilder_stack.py
  cli/tests/pcluster/templates/test_imagebuilder_stack.py
Labels: skip-changelog-update

#6761 [integ-tests] Reduce timeout limit
  tests/integration-tests/tests/common/hit_common.py
  tests/integration-tests/tests/schedulers/test_slurm.py
Labels: skip-changelog-update

#6762 [Docs] Fix changelog for 3.13.0
  CHANGELOG.md
Labels: docs, 3.x

#6763 [Test] Add HNBootstrap timeout for multi-nic tests
  tests/integration-tests/tests/multiple_nics/test_multiple_nics/test_multiple_nics/pcluster.config.yaml
Labels: skip-changelog-update, 3.x

#6765 [release-3.13] Remove KUL region support and change related integ-test
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/supported-regions
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
Labels: 3.x

#6766 [develop] Remove KUL region support and change related integ-test.
  CHANGELOG.md
  cli/src/pcluster/constants.py
  cli/src/pcluster/resources/supported-regions
  tests/integration-tests/configs/common.jinja2
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
Labels: 3.x

#6767 [release-3.13] Update CHANGELOG to add ap-southeast-7 support
  CHANGELOG.md
Labels: 3.x

#6764 [Test] Execute all Ad integ tests in ap-southeast-1
  tests/integration-tests/configs/develop.yaml
Labels: skip-changelog-update, 3.x, Test
