Repository aws/aws-parallelcluster, pull requests merged in 2025-05, with the labels that each got.

#6806 [Bug Fix] Fix ExistingFsxNetworkingValidator
  CHANGELOG.md
  cli/src/pcluster/validators/cluster_validators.py
  cli/tests/pcluster/validators/test_cluster_validators.py
Labels: 3.x

#6808 [integ-tests-framework] Set fallback for OS rotation when no supported AMI is available
  tests/integration-tests/framework/tests_configuration/config_renderer.py
Labels: skip-changelog-update

#6810 [perf test] Use the right placement group for capacity reservation
  tests/integration-tests/tests/performance_tests/test_openfoam/test_openfoam/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_osu/test_osu/pcluster.config.yaml
  tests/integration-tests/tests/performance_tests/test_starccm/test_starccm/pcluster.config.yaml
Labels: skip-changelog-update

#6818 [build-image] Move logic from validation to test phase
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_validate.yaml
  cli/src/pcluster/templates/imagebuilder_stack.py
  cli/tests/pcluster/templates/test_imagebuilder_stack.py
Labels: skip-changelog-update

#6821 [integ-tests-framework] Add --pcluster-installer-path and run test_slurm_cli_commands with installer
  tests/integration-tests/conftest.py
  tests/integration-tests/test_runner.py
  tests/integration-tests/tests/cli_commands/test_cli_commands.py
Labels: skip-changelog-update, 3.x, Test

#6827 Change awsbatch test to region eu-west-3 so that it doesnt use c4 instances
  tests/integration-tests/configs/develop.yaml
  tests/integration-tests/configs/released.yaml
Labels: skip-changelog-update

#6826 [BuildImage] Add logic to install a specific version of CMake for Ubuntu20.04 in component parallelcluster_test.yaml
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update, 3.x

#6829 [BuildImage] Add logic to install a specific version of CMake for Ubuntu20.04 in component parallelcluster_test.yaml + reduced size of test component
  cli/src/pcluster/resources/imagebuilder/parallelcluster_test.yaml
Labels: skip-changelog-update

#6834 [Integ-Test] Increase the ComputeNodes launching time timeout to 6 minutes
  tests/integration-tests/tests/common/assertions.py
  tests/integration-tests/tests/common/hit_common.py
Labels: skip-changelog-update, 3.x

#6835 Upgrade libfabric version to 2.1.0
  tests/integration-tests/tests/efa/test_efa/test_efa/install-fabtests.sh
Labels: skip-changelog-update

#6846 Do not install curl on Amazon Linux 2023 to avoid conflicts
  cli/src/pcluster/resources/imagebuilder/parallelcluster.yaml
Labels: skip-changelog-update

#6849 [integ-tests] Remove compilation of OFI because EFA has included the ofi-nccl plugin in the installer
  tests/integration-tests/tests/efa/test_efa/test_efa/nccl_benchmarks/init_nccl_benchmarks.sh
Labels: skip-changelog-update

#6836 [Test] Remove validation of Torque wrapper from slurm tests.
  tests/integration-tests/tests/schedulers/test_slurm.py
  tests/integration-tests/tests/schedulers/test_slurm/test_slurm/torque_job.sh
Labels: skip-changelog-update, 3.x, Test
